// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: app_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppUserByPublicID = `-- name: GetAppUserByPublicID :one
SELECT id, public_id, zitadel_subject, display_name, created_at, updated_at
FROM app_users
WHERE public_id = $1
`

func (q *Queries) GetAppUserByPublicID(ctx context.Context, publicID pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByPublicID, publicID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ZitadelSubject,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
