// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    actor_type,
    actor_user_id,
    actor_machine_client_id,
    tenant_id,
    action,
    target_type,
    target_id,
    request_id,
    client_ip,
    user_agent,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    id,
    public_id,
    actor_type,
    actor_user_id,
    actor_machine_client_id,
    tenant_id,
    action,
    target_type,
    target_id,
    request_id,
    client_ip,
    user_agent,
    metadata,
    occurred_at,
    created_at
`

type CreateAuditEventParams struct {
	ActorType            string      `json:"actor_type"`
	ActorUserID          pgtype.Int8 `json:"actor_user_id"`
	ActorMachineClientID pgtype.Int8 `json:"actor_machine_client_id"`
	TenantID             pgtype.Int8 `json:"tenant_id"`
	Action               string      `json:"action"`
	TargetType           string      `json:"target_type"`
	TargetID             string      `json:"target_id"`
	RequestID            string      `json:"request_id"`
	ClientIp             string      `json:"client_ip"`
	UserAgent            string      `json:"user_agent"`
	Metadata             []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ActorType,
		arg.ActorUserID,
		arg.ActorMachineClientID,
		arg.TenantID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.ClientIp,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ActorType,
		&i.ActorUserID,
		&i.ActorMachineClientID,
		&i.TenantID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.RequestID,
		&i.ClientIp,
		&i.UserAgent,
		&i.Metadata,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByTarget = `-- name: ListAuditEventsByTarget :many
SELECT
    id,
    public_id,
    actor_type,
    actor_user_id,
    actor_machine_client_id,
    tenant_id,
    action,
    target_type,
    target_id,
    request_id,
    client_ip,
    user_agent,
    metadata,
    occurred_at,
    created_at
FROM audit_events
WHERE target_type = $1
  AND target_id = $2
ORDER BY occurred_at DESC, id DESC
LIMIT $3
`

type ListAuditEventsByTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListAuditEventsByTarget(ctx context.Context, arg ListAuditEventsByTargetParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTarget, arg.TargetType, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActorType,
			&i.ActorUserID,
			&i.ActorMachineClientID,
			&i.TenantID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.ClientIp,
			&i.UserAgent,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByTenantID = `-- name: ListAuditEventsByTenantID :many
SELECT
    id,
    public_id,
    actor_type,
    actor_user_id,
    actor_machine_client_id,
    tenant_id,
    action,
    target_type,
    target_id,
    request_id,
    client_ip,
    user_agent,
    metadata,
    occurred_at,
    created_at
FROM audit_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListAuditEventsByTenantIDParams struct {
	TenantID pgtype.Int8 `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListAuditEventsByTenantID(ctx context.Context, arg ListAuditEventsByTenantIDParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTenantID, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActorType,
			&i.ActorUserID,
			&i.ActorMachineClientID,
			&i.TenantID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.ClientIp,
			&i.UserAgent,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditEvents = `-- name: ListRecentAuditEvents :many
SELECT
    id,
    public_id,
    actor_type,
    actor_user_id,
    actor_machine_client_id,
    tenant_id,
    action,
    target_type,
    target_id,
    request_id,
    client_ip,
    user_agent,
    metadata,
    occurred_at,
    created_at
FROM audit_events
ORDER BY occurred_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListRecentAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listRecentAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActorType,
			&i.ActorUserID,
			&i.ActorMachineClientID,
			&i.TenantID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.ClientIp,
			&i.UserAgent,
			&i.Metadata,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
