// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: customer_signal_saved_filters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomerSignalSavedFilter = `-- name: CreateCustomerSignalSavedFilter :one
INSERT INTO customer_signal_saved_filters (
    tenant_id,
    owner_user_id,
    name,
    query,
    filters
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, public_id, tenant_id, owner_user_id, name, query, filters, created_at, updated_at, deleted_at
`

type CreateCustomerSignalSavedFilterParams struct {
	TenantID    int64  `json:"tenant_id"`
	OwnerUserID int64  `json:"owner_user_id"`
	Name        string `json:"name"`
	Query       string `json:"query"`
	Filters     []byte `json:"filters"`
}

func (q *Queries) CreateCustomerSignalSavedFilter(ctx context.Context, arg CreateCustomerSignalSavedFilterParams) (CustomerSignalSavedFilter, error) {
	row := q.db.QueryRow(ctx, createCustomerSignalSavedFilter,
		arg.TenantID,
		arg.OwnerUserID,
		arg.Name,
		arg.Query,
		arg.Filters,
	)
	var i CustomerSignalSavedFilter
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.OwnerUserID,
		&i.Name,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCustomerSignalSavedFilter = `-- name: DeleteCustomerSignalSavedFilter :execrows
UPDATE customer_signal_saved_filters
SET
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE public_id = $1
  AND tenant_id = $2
  AND owner_user_id = $3
  AND deleted_at IS NULL
`

type DeleteCustomerSignalSavedFilterParams struct {
	PublicID    uuid.UUID `json:"public_id"`
	TenantID    int64     `json:"tenant_id"`
	OwnerUserID int64     `json:"owner_user_id"`
}

func (q *Queries) DeleteCustomerSignalSavedFilter(ctx context.Context, arg DeleteCustomerSignalSavedFilterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomerSignalSavedFilter, arg.PublicID, arg.TenantID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomerSignalSavedFilterForOwner = `-- name: GetCustomerSignalSavedFilterForOwner :one
SELECT id, public_id, tenant_id, owner_user_id, name, query, filters, created_at, updated_at, deleted_at
FROM customer_signal_saved_filters
WHERE public_id = $1
  AND tenant_id = $2
  AND owner_user_id = $3
  AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerSignalSavedFilterForOwnerParams struct {
	PublicID    uuid.UUID `json:"public_id"`
	TenantID    int64     `json:"tenant_id"`
	OwnerUserID int64     `json:"owner_user_id"`
}

func (q *Queries) GetCustomerSignalSavedFilterForOwner(ctx context.Context, arg GetCustomerSignalSavedFilterForOwnerParams) (CustomerSignalSavedFilter, error) {
	row := q.db.QueryRow(ctx, getCustomerSignalSavedFilterForOwner, arg.PublicID, arg.TenantID, arg.OwnerUserID)
	var i CustomerSignalSavedFilter
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.OwnerUserID,
		&i.Name,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomerSignalSavedFilters = `-- name: ListCustomerSignalSavedFilters :many
SELECT id, public_id, tenant_id, owner_user_id, name, query, filters, created_at, updated_at, deleted_at
FROM customer_signal_saved_filters
WHERE tenant_id = $1
  AND owner_user_id = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListCustomerSignalSavedFiltersParams struct {
	TenantID    int64 `json:"tenant_id"`
	OwnerUserID int64 `json:"owner_user_id"`
}

func (q *Queries) ListCustomerSignalSavedFilters(ctx context.Context, arg ListCustomerSignalSavedFiltersParams) ([]CustomerSignalSavedFilter, error) {
	rows, err := q.db.Query(ctx, listCustomerSignalSavedFilters, arg.TenantID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerSignalSavedFilter
	for rows.Next() {
		var i CustomerSignalSavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.OwnerUserID,
			&i.Name,
			&i.Query,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerSignalSavedFilter = `-- name: UpdateCustomerSignalSavedFilter :one
UPDATE customer_signal_saved_filters
SET
    name = $4,
    query = $5,
    filters = $6,
    updated_at = now()
WHERE public_id = $1
  AND tenant_id = $2
  AND owner_user_id = $3
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, owner_user_id, name, query, filters, created_at, updated_at, deleted_at
`

type UpdateCustomerSignalSavedFilterParams struct {
	PublicID    uuid.UUID `json:"public_id"`
	TenantID    int64     `json:"tenant_id"`
	OwnerUserID int64     `json:"owner_user_id"`
	Name        string    `json:"name"`
	Query       string    `json:"query"`
	Filters     []byte    `json:"filters"`
}

func (q *Queries) UpdateCustomerSignalSavedFilter(ctx context.Context, arg UpdateCustomerSignalSavedFilterParams) (CustomerSignalSavedFilter, error) {
	row := q.db.QueryRow(ctx, updateCustomerSignalSavedFilter,
		arg.PublicID,
		arg.TenantID,
		arg.OwnerUserID,
		arg.Name,
		arg.Query,
		arg.Filters,
	)
	var i CustomerSignalSavedFilter
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.OwnerUserID,
		&i.Name,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
