// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_signal_imports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCustomerSignalImportJob = `-- name: CompleteCustomerSignalImportJob :one
UPDATE customer_signal_import_jobs
SET
    status = 'completed',
    total_rows = $2,
    valid_rows = $3,
    invalid_rows = $4,
    inserted_rows = $5,
    error_file_object_id = $6,
    error_summary = $7,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
`

type CompleteCustomerSignalImportJobParams struct {
	ID                int64       `json:"id"`
	TotalRows         int32       `json:"total_rows"`
	ValidRows         int32       `json:"valid_rows"`
	InvalidRows       int32       `json:"invalid_rows"`
	InsertedRows      int32       `json:"inserted_rows"`
	ErrorFileObjectID pgtype.Int8 `json:"error_file_object_id"`
	ErrorSummary      pgtype.Text `json:"error_summary"`
}

func (q *Queries) CompleteCustomerSignalImportJob(ctx context.Context, arg CompleteCustomerSignalImportJobParams) (CustomerSignalImportJob, error) {
	row := q.db.QueryRow(ctx, completeCustomerSignalImportJob,
		arg.ID,
		arg.TotalRows,
		arg.ValidRows,
		arg.InvalidRows,
		arg.InsertedRows,
		arg.ErrorFileObjectID,
		arg.ErrorSummary,
	)
	var i CustomerSignalImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.InputFileObjectID,
		&i.ErrorFileObjectID,
		&i.OutboxEventID,
		&i.Status,
		&i.ValidateOnly,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.InsertedRows,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCustomerSignalImportJob = `-- name: CreateCustomerSignalImportJob :one
INSERT INTO customer_signal_import_jobs (
    tenant_id,
    requested_by_user_id,
    input_file_object_id,
    validate_only
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
`

type CreateCustomerSignalImportJobParams struct {
	TenantID          int64       `json:"tenant_id"`
	RequestedByUserID pgtype.Int8 `json:"requested_by_user_id"`
	InputFileObjectID int64       `json:"input_file_object_id"`
	ValidateOnly      bool        `json:"validate_only"`
}

func (q *Queries) CreateCustomerSignalImportJob(ctx context.Context, arg CreateCustomerSignalImportJobParams) (CustomerSignalImportJob, error) {
	row := q.db.QueryRow(ctx, createCustomerSignalImportJob,
		arg.TenantID,
		arg.RequestedByUserID,
		arg.InputFileObjectID,
		arg.ValidateOnly,
	)
	var i CustomerSignalImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.InputFileObjectID,
		&i.ErrorFileObjectID,
		&i.OutboxEventID,
		&i.Status,
		&i.ValidateOnly,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.InsertedRows,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const failCustomerSignalImportJob = `-- name: FailCustomerSignalImportJob :one
UPDATE customer_signal_import_jobs
SET
    status = 'failed',
    error_summary = left($2, 1000),
    completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
`

type FailCustomerSignalImportJobParams struct {
	ID   int64  `json:"id"`
	Left string `json:"left"`
}

func (q *Queries) FailCustomerSignalImportJob(ctx context.Context, arg FailCustomerSignalImportJobParams) (CustomerSignalImportJob, error) {
	row := q.db.QueryRow(ctx, failCustomerSignalImportJob, arg.ID, arg.Left)
	var i CustomerSignalImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.InputFileObjectID,
		&i.ErrorFileObjectID,
		&i.OutboxEventID,
		&i.Status,
		&i.ValidateOnly,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.InsertedRows,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerSignalImportJobByIDForTenant = `-- name: GetCustomerSignalImportJobByIDForTenant :one
SELECT id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
FROM customer_signal_import_jobs
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerSignalImportJobByIDForTenantParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetCustomerSignalImportJobByIDForTenant(ctx context.Context, arg GetCustomerSignalImportJobByIDForTenantParams) (CustomerSignalImportJob, error) {
	row := q.db.QueryRow(ctx, getCustomerSignalImportJobByIDForTenant, arg.ID, arg.TenantID)
	var i CustomerSignalImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.InputFileObjectID,
		&i.ErrorFileObjectID,
		&i.OutboxEventID,
		&i.Status,
		&i.ValidateOnly,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.InsertedRows,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerSignalImportJobForTenant = `-- name: GetCustomerSignalImportJobForTenant :one
SELECT id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
FROM customer_signal_import_jobs
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerSignalImportJobForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetCustomerSignalImportJobForTenant(ctx context.Context, arg GetCustomerSignalImportJobForTenantParams) (CustomerSignalImportJob, error) {
	row := q.db.QueryRow(ctx, getCustomerSignalImportJobForTenant, arg.PublicID, arg.TenantID)
	var i CustomerSignalImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.InputFileObjectID,
		&i.ErrorFileObjectID,
		&i.OutboxEventID,
		&i.Status,
		&i.ValidateOnly,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.InsertedRows,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomerSignalImportJobs = `-- name: ListCustomerSignalImportJobs :many
SELECT id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
FROM customer_signal_import_jobs
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListCustomerSignalImportJobsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListCustomerSignalImportJobs(ctx context.Context, arg ListCustomerSignalImportJobsParams) ([]CustomerSignalImportJob, error) {
	rows, err := q.db.Query(ctx, listCustomerSignalImportJobs, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerSignalImportJob
	for rows.Next() {
		var i CustomerSignalImportJob
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.RequestedByUserID,
			&i.InputFileObjectID,
			&i.ErrorFileObjectID,
			&i.OutboxEventID,
			&i.Status,
			&i.ValidateOnly,
			&i.TotalRows,
			&i.ValidRows,
			&i.InvalidRows,
			&i.InsertedRows,
			&i.ErrorSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomerSignalImportJobProcessing = `-- name: MarkCustomerSignalImportJobProcessing :one
UPDATE customer_signal_import_jobs
SET
    status = 'processing',
    outbox_event_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, input_file_object_id, error_file_object_id, outbox_event_id, status, validate_only, total_rows, valid_rows, invalid_rows, inserted_rows, error_summary, created_at, updated_at, completed_at, deleted_at
`

type MarkCustomerSignalImportJobProcessingParams struct {
	ID            int64       `json:"id"`
	OutboxEventID pgtype.Int8 `json:"outbox_event_id"`
}

func (q *Queries) MarkCustomerSignalImportJobProcessing(ctx context.Context, arg MarkCustomerSignalImportJobProcessingParams) (CustomerSignalImportJob, error) {
	row := q.db.QueryRow(ctx, markCustomerSignalImportJobProcessing, arg.ID, arg.OutboxEventID)
	var i CustomerSignalImportJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.InputFileObjectID,
		&i.ErrorFileObjectID,
		&i.OutboxEventID,
		&i.Status,
		&i.ValidateOnly,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.InsertedRows,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}
