// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_signals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerSignal = `-- name: CreateCustomerSignal :one
INSERT INTO customer_signals (
    tenant_id,
    created_by_user_id,
    customer_name,
    title,
    body,
    source,
    priority,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    public_id,
    tenant_id,
    created_by_user_id,
    customer_name,
    title,
    body,
    source,
    priority,
    status,
    created_at,
    updated_at,
    deleted_at
`

type CreateCustomerSignalParams struct {
	TenantID        int64       `json:"tenant_id"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
	CustomerName    string      `json:"customer_name"`
	Title           string      `json:"title"`
	Body            string      `json:"body"`
	Source          string      `json:"source"`
	Priority        string      `json:"priority"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateCustomerSignal(ctx context.Context, arg CreateCustomerSignalParams) (CustomerSignal, error) {
	row := q.db.QueryRow(ctx, createCustomerSignal,
		arg.TenantID,
		arg.CreatedByUserID,
		arg.CustomerName,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Priority,
		arg.Status,
	)
	var i CustomerSignal
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.CustomerName,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerSignalByPublicIDForTenant = `-- name: GetCustomerSignalByPublicIDForTenant :one
SELECT
    id,
    public_id,
    tenant_id,
    created_by_user_id,
    customer_name,
    title,
    body,
    source,
    priority,
    status,
    created_at,
    updated_at,
    deleted_at
FROM customer_signals
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerSignalByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetCustomerSignalByPublicIDForTenant(ctx context.Context, arg GetCustomerSignalByPublicIDForTenantParams) (CustomerSignal, error) {
	row := q.db.QueryRow(ctx, getCustomerSignalByPublicIDForTenant, arg.PublicID, arg.TenantID)
	var i CustomerSignal
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.CustomerName,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomerSignalsByTenantID = `-- name: ListCustomerSignalsByTenantID :many
SELECT
    id,
    public_id,
    tenant_id,
    created_by_user_id,
    customer_name,
    title,
    body,
    source,
    priority,
    status,
    created_at,
    updated_at,
    deleted_at
FROM customer_signals
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCustomerSignalsByTenantID(ctx context.Context, tenantID int64) ([]CustomerSignal, error) {
	rows, err := q.db.Query(ctx, listCustomerSignalsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerSignal
	for rows.Next() {
		var i CustomerSignal
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.CreatedByUserID,
			&i.CustomerName,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomerSignals = `-- name: SearchCustomerSignals :many
SELECT
    id,
    public_id,
    tenant_id,
    created_by_user_id,
    customer_name,
    title,
    body,
    source,
    priority,
    status,
    created_at,
    updated_at,
    deleted_at
FROM customer_signals
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND (
      $2::text IS NULL
      OR btrim($2::text) = ''
      OR to_tsvector('simple', customer_name || ' ' || title || ' ' || body)
         @@ websearch_to_tsquery('simple', $2::text)
  )
  AND (
      $3::text IS NULL
      OR status = $3::text
  )
  AND (
      $4::text IS NULL
      OR priority = $4::text
  )
  AND (
      $5::text IS NULL
      OR source = $5::text
  )
  AND (
      $6::timestamptz IS NULL
      OR (created_at, id) < ($6::timestamptz, $7::bigint)
  )
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type SearchCustomerSignalsParams struct {
	TenantID        int64              `json:"tenant_id"`
	Q               pgtype.Text        `json:"q"`
	Status          pgtype.Text        `json:"status"`
	Priority        pgtype.Text        `json:"priority"`
	Source          pgtype.Text        `json:"source"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.Int8        `json:"cursor_id"`
	ResultLimit     int32              `json:"result_limit"`
}

func (q *Queries) SearchCustomerSignals(ctx context.Context, arg SearchCustomerSignalsParams) ([]CustomerSignal, error) {
	rows, err := q.db.Query(ctx, searchCustomerSignals,
		arg.TenantID,
		arg.Q,
		arg.Status,
		arg.Priority,
		arg.Source,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerSignal
	for rows.Next() {
		var i CustomerSignal
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.CreatedByUserID,
			&i.CustomerName,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomerSignalByPublicIDForTenant = `-- name: SoftDeleteCustomerSignalByPublicIDForTenant :execrows
UPDATE customer_signals
SET
    deleted_at = now(),
    updated_at = now()
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteCustomerSignalByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) SoftDeleteCustomerSignalByPublicIDForTenant(ctx context.Context, arg SoftDeleteCustomerSignalByPublicIDForTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCustomerSignalByPublicIDForTenant, arg.PublicID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCustomerSignalByPublicIDForTenant = `-- name: UpdateCustomerSignalByPublicIDForTenant :one
UPDATE customer_signals
SET
    customer_name = $3,
    title = $4,
    body = $5,
    source = $6,
    priority = $7,
    status = $8,
    updated_at = now()
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
RETURNING
    id,
    public_id,
    tenant_id,
    created_by_user_id,
    customer_name,
    title,
    body,
    source,
    priority,
    status,
    created_at,
    updated_at,
    deleted_at
`

type UpdateCustomerSignalByPublicIDForTenantParams struct {
	PublicID     uuid.UUID `json:"public_id"`
	TenantID     int64     `json:"tenant_id"`
	CustomerName string    `json:"customer_name"`
	Title        string    `json:"title"`
	Body         string    `json:"body"`
	Source       string    `json:"source"`
	Priority     string    `json:"priority"`
	Status       string    `json:"status"`
}

func (q *Queries) UpdateCustomerSignalByPublicIDForTenant(ctx context.Context, arg UpdateCustomerSignalByPublicIDForTenantParams) (CustomerSignal, error) {
	row := q.db.QueryRow(ctx, updateCustomerSignalByPublicIDForTenant,
		arg.PublicID,
		arg.TenantID,
		arg.CustomerName,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Priority,
		arg.Status,
	)
	var i CustomerSignal
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.CustomerName,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
