// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: data_pipelines.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveDataPipeline = `-- name: ArchiveDataPipeline :one
UPDATE data_pipelines
SET
    status = 'archived',
    updated_by_user_id = $1,
    updated_at = now(),
    archived_at = COALESCE(archived_at, now())
WHERE tenant_id = $2
  AND public_id = $3
  AND archived_at IS NULL
RETURNING id, public_id, tenant_id, created_by_user_id, updated_by_user_id, name, description, status, published_version_id, created_at, updated_at, archived_at
`

type ArchiveDataPipelineParams struct {
	UpdatedByUserID pgtype.Int8 `json:"updated_by_user_id"`
	TenantID        int64       `json:"tenant_id"`
	PublicID        uuid.UUID   `json:"public_id"`
}

func (q *Queries) ArchiveDataPipeline(ctx context.Context, arg ArchiveDataPipelineParams) (DataPipeline, error) {
	row := q.db.QueryRow(ctx, archiveDataPipeline, arg.UpdatedByUserID, arg.TenantID, arg.PublicID)
	var i DataPipeline
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const archivePublishedDataPipelineVersionsExcept = `-- name: ArchivePublishedDataPipelineVersionsExcept :exec
UPDATE data_pipeline_versions
SET status = 'archived'
WHERE tenant_id = $1
  AND pipeline_id = $2
  AND id <> $3
  AND status = 'published'
`

type ArchivePublishedDataPipelineVersionsExceptParams struct {
	TenantID   int64 `json:"tenant_id"`
	PipelineID int64 `json:"pipeline_id"`
	VersionID  int64 `json:"version_id"`
}

func (q *Queries) ArchivePublishedDataPipelineVersionsExcept(ctx context.Context, arg ArchivePublishedDataPipelineVersionsExceptParams) error {
	_, err := q.db.Exec(ctx, archivePublishedDataPipelineVersionsExcept, arg.TenantID, arg.PipelineID, arg.VersionID)
	return err
}

const claimDueDataPipelineSchedules = `-- name: ClaimDueDataPipelineSchedules :many
SELECT id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
FROM data_pipeline_schedules
WHERE enabled
  AND next_run_at <= $1::timestamptz
ORDER BY next_run_at, id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimDueDataPipelineSchedulesParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	BatchLimit int32              `json:"batch_limit"`
}

func (q *Queries) ClaimDueDataPipelineSchedules(ctx context.Context, arg ClaimDueDataPipelineSchedulesParams) ([]DataPipelineSchedule, error) {
	rows, err := q.db.Query(ctx, claimDueDataPipelineSchedules, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineSchedule
	for rows.Next() {
		var i DataPipelineSchedule
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineID,
			&i.VersionID,
			&i.CreatedByUserID,
			&i.Frequency,
			&i.Timezone,
			&i.RunTime,
			&i.Weekday,
			&i.MonthDay,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastErrorSummary,
			&i.LastRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDataPipelineRun = `-- name: CompleteDataPipelineRun :one
UPDATE data_pipeline_runs
SET
    status = 'completed',
    output_work_table_id = $1,
    row_count = $2,
    error_summary = NULL,
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $3
  AND id = $4
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
`

type CompleteDataPipelineRunParams struct {
	OutputWorkTableID pgtype.Int8 `json:"output_work_table_id"`
	RowCount          int64       `json:"row_count"`
	TenantID          int64       `json:"tenant_id"`
	ID                int64       `json:"id"`
}

func (q *Queries) CompleteDataPipelineRun(ctx context.Context, arg CompleteDataPipelineRunParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, completeDataPipelineRun,
		arg.OutputWorkTableID,
		arg.RowCount,
		arg.TenantID,
		arg.ID,
	)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeDataPipelineRunOutput = `-- name: CompleteDataPipelineRunOutput :one
UPDATE data_pipeline_run_outputs
SET
    status = 'completed',
    output_work_table_id = $1,
    row_count = $2,
    error_summary = NULL,
    metadata = $3,
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $4
  AND run_id = $5
  AND node_id = $6
RETURNING id, tenant_id, run_id, node_id, status, output_work_table_id, row_count, error_summary, metadata, started_at, completed_at, created_at, updated_at
`

type CompleteDataPipelineRunOutputParams struct {
	OutputWorkTableID pgtype.Int8 `json:"output_work_table_id"`
	RowCount          int64       `json:"row_count"`
	Metadata          []byte      `json:"metadata"`
	TenantID          int64       `json:"tenant_id"`
	RunID             int64       `json:"run_id"`
	NodeID            string      `json:"node_id"`
}

func (q *Queries) CompleteDataPipelineRunOutput(ctx context.Context, arg CompleteDataPipelineRunOutputParams) (DataPipelineRunOutput, error) {
	row := q.db.QueryRow(ctx, completeDataPipelineRunOutput,
		arg.OutputWorkTableID,
		arg.RowCount,
		arg.Metadata,
		arg.TenantID,
		arg.RunID,
		arg.NodeID,
	)
	var i DataPipelineRunOutput
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.Status,
		&i.OutputWorkTableID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeDataPipelineRunStep = `-- name: CompleteDataPipelineRunStep :one
UPDATE data_pipeline_run_steps
SET
    status = 'completed',
    row_count = $1,
    error_summary = NULL,
    metadata = $2,
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $3
  AND run_id = $4
  AND node_id = $5
RETURNING id, tenant_id, run_id, node_id, step_type, status, row_count, error_summary, error_sample, metadata, started_at, completed_at, created_at, updated_at
`

type CompleteDataPipelineRunStepParams struct {
	RowCount int64  `json:"row_count"`
	Metadata []byte `json:"metadata"`
	TenantID int64  `json:"tenant_id"`
	RunID    int64  `json:"run_id"`
	NodeID   string `json:"node_id"`
}

func (q *Queries) CompleteDataPipelineRunStep(ctx context.Context, arg CompleteDataPipelineRunStepParams) (DataPipelineRunStep, error) {
	row := q.db.QueryRow(ctx, completeDataPipelineRunStep,
		arg.RowCount,
		arg.Metadata,
		arg.TenantID,
		arg.RunID,
		arg.NodeID,
	)
	var i DataPipelineRunStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.StepType,
		&i.Status,
		&i.RowCount,
		&i.ErrorSummary,
		&i.ErrorSample,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveDataPipelineRunsForSchedule = `-- name: CountActiveDataPipelineRunsForSchedule :one
SELECT count(*)::bigint
FROM data_pipeline_runs
WHERE tenant_id = $1
  AND schedule_id = $2
  AND status IN ('pending', 'processing')
`

type CountActiveDataPipelineRunsForScheduleParams struct {
	TenantID   int64       `json:"tenant_id"`
	ScheduleID pgtype.Int8 `json:"schedule_id"`
}

func (q *Queries) CountActiveDataPipelineRunsForSchedule(ctx context.Context, arg CountActiveDataPipelineRunsForScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDataPipelineRunsForSchedule, arg.TenantID, arg.ScheduleID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countDataPipelineMappingEvidence = `-- name: CountDataPipelineMappingEvidence :many
SELECT
    schema_column_id,
    decision,
    count(*)::bigint AS evidence_count
FROM data_pipeline_mapping_examples
WHERE tenant_id = $1
  AND schema_column_id = ANY($2::bigint[])
  AND (
      shared_scope = 'tenant'
      OR pipeline_id = $3::bigint
  )
GROUP BY schema_column_id, decision
`

type CountDataPipelineMappingEvidenceParams struct {
	TenantID        int64       `json:"tenant_id"`
	SchemaColumnIds []int64     `json:"schema_column_ids"`
	PipelineID      pgtype.Int8 `json:"pipeline_id"`
}

type CountDataPipelineMappingEvidenceRow struct {
	SchemaColumnID int64  `json:"schema_column_id"`
	Decision       string `json:"decision"`
	EvidenceCount  int64  `json:"evidence_count"`
}

func (q *Queries) CountDataPipelineMappingEvidence(ctx context.Context, arg CountDataPipelineMappingEvidenceParams) ([]CountDataPipelineMappingEvidenceRow, error) {
	rows, err := q.db.Query(ctx, countDataPipelineMappingEvidence, arg.TenantID, arg.SchemaColumnIds, arg.PipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDataPipelineMappingEvidenceRow
	for rows.Next() {
		var i CountDataPipelineMappingEvidenceRow
		if err := rows.Scan(&i.SchemaColumnID, &i.Decision, &i.EvidenceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDataPipeline = `-- name: CreateDataPipeline :one
INSERT INTO data_pipelines (
    tenant_id,
    created_by_user_id,
    updated_by_user_id,
    name,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, public_id, tenant_id, created_by_user_id, updated_by_user_id, name, description, status, published_version_id, created_at, updated_at, archived_at
`

type CreateDataPipelineParams struct {
	TenantID        int64       `json:"tenant_id"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
	UpdatedByUserID pgtype.Int8 `json:"updated_by_user_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
}

func (q *Queries) CreateDataPipeline(ctx context.Context, arg CreateDataPipelineParams) (DataPipeline, error) {
	row := q.db.QueryRow(ctx, createDataPipeline,
		arg.TenantID,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
		arg.Name,
		arg.Description,
	)
	var i DataPipeline
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createDataPipelineRun = `-- name: CreateDataPipelineRun :one
INSERT INTO data_pipeline_runs (
    tenant_id,
    pipeline_id,
    version_id,
    schedule_id,
    requested_by_user_id,
    trigger_kind
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
`

type CreateDataPipelineRunParams struct {
	TenantID          int64       `json:"tenant_id"`
	PipelineID        int64       `json:"pipeline_id"`
	VersionID         int64       `json:"version_id"`
	ScheduleID        pgtype.Int8 `json:"schedule_id"`
	RequestedByUserID pgtype.Int8 `json:"requested_by_user_id"`
	TriggerKind       string      `json:"trigger_kind"`
}

func (q *Queries) CreateDataPipelineRun(ctx context.Context, arg CreateDataPipelineRunParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, createDataPipelineRun,
		arg.TenantID,
		arg.PipelineID,
		arg.VersionID,
		arg.ScheduleID,
		arg.RequestedByUserID,
		arg.TriggerKind,
	)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDataPipelineRunOutput = `-- name: CreateDataPipelineRunOutput :one
INSERT INTO data_pipeline_run_outputs (
    tenant_id,
    run_id,
    node_id
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (run_id, node_id) DO UPDATE
SET updated_at = now()
RETURNING id, tenant_id, run_id, node_id, status, output_work_table_id, row_count, error_summary, metadata, started_at, completed_at, created_at, updated_at
`

type CreateDataPipelineRunOutputParams struct {
	TenantID int64  `json:"tenant_id"`
	RunID    int64  `json:"run_id"`
	NodeID   string `json:"node_id"`
}

func (q *Queries) CreateDataPipelineRunOutput(ctx context.Context, arg CreateDataPipelineRunOutputParams) (DataPipelineRunOutput, error) {
	row := q.db.QueryRow(ctx, createDataPipelineRunOutput, arg.TenantID, arg.RunID, arg.NodeID)
	var i DataPipelineRunOutput
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.Status,
		&i.OutputWorkTableID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDataPipelineRunStep = `-- name: CreateDataPipelineRunStep :one
INSERT INTO data_pipeline_run_steps (
    tenant_id,
    run_id,
    node_id,
    step_type
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (run_id, node_id) DO UPDATE
SET
    step_type = EXCLUDED.step_type,
    updated_at = now()
RETURNING id, tenant_id, run_id, node_id, step_type, status, row_count, error_summary, error_sample, metadata, started_at, completed_at, created_at, updated_at
`

type CreateDataPipelineRunStepParams struct {
	TenantID int64  `json:"tenant_id"`
	RunID    int64  `json:"run_id"`
	NodeID   string `json:"node_id"`
	StepType string `json:"step_type"`
}

func (q *Queries) CreateDataPipelineRunStep(ctx context.Context, arg CreateDataPipelineRunStepParams) (DataPipelineRunStep, error) {
	row := q.db.QueryRow(ctx, createDataPipelineRunStep,
		arg.TenantID,
		arg.RunID,
		arg.NodeID,
		arg.StepType,
	)
	var i DataPipelineRunStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.StepType,
		&i.Status,
		&i.RowCount,
		&i.ErrorSummary,
		&i.ErrorSample,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDataPipelineSchedule = `-- name: CreateDataPipelineSchedule :one
INSERT INTO data_pipeline_schedules (
    tenant_id,
    pipeline_id,
    version_id,
    created_by_user_id,
    frequency,
    timezone,
    run_time,
    weekday,
    month_day,
    enabled,
    next_run_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
`

type CreateDataPipelineScheduleParams struct {
	TenantID        int64              `json:"tenant_id"`
	PipelineID      int64              `json:"pipeline_id"`
	VersionID       int64              `json:"version_id"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	Frequency       string             `json:"frequency"`
	Timezone        string             `json:"timezone"`
	RunTime         string             `json:"run_time"`
	Weekday         pgtype.Int2        `json:"weekday"`
	MonthDay        pgtype.Int2        `json:"month_day"`
	Enabled         bool               `json:"enabled"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) CreateDataPipelineSchedule(ctx context.Context, arg CreateDataPipelineScheduleParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, createDataPipelineSchedule,
		arg.TenantID,
		arg.PipelineID,
		arg.VersionID,
		arg.CreatedByUserID,
		arg.Frequency,
		arg.Timezone,
		arg.RunTime,
		arg.Weekday,
		arg.MonthDay,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDataPipelineVersion = `-- name: CreateDataPipelineVersion :one
INSERT INTO data_pipeline_versions (
    tenant_id,
    pipeline_id,
    version_number,
    status,
    graph,
    validation_summary,
    created_by_user_id
) VALUES (
    $1,
    $2,
    (
        SELECT COALESCE(MAX(version_number), 0) + 1
        FROM data_pipeline_versions
        WHERE pipeline_id = $2
    ),
    'draft',
    $3,
    $4,
    $5
)
RETURNING id, public_id, tenant_id, pipeline_id, version_number, status, graph, validation_summary, created_by_user_id, published_by_user_id, created_at, published_at
`

type CreateDataPipelineVersionParams struct {
	TenantID          int64       `json:"tenant_id"`
	PipelineID        int64       `json:"pipeline_id"`
	Graph             []byte      `json:"graph"`
	ValidationSummary []byte      `json:"validation_summary"`
	CreatedByUserID   pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateDataPipelineVersion(ctx context.Context, arg CreateDataPipelineVersionParams) (DataPipelineVersion, error) {
	row := q.db.QueryRow(ctx, createDataPipelineVersion,
		arg.TenantID,
		arg.PipelineID,
		arg.Graph,
		arg.ValidationSummary,
		arg.CreatedByUserID,
	)
	var i DataPipelineVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionNumber,
		&i.Status,
		&i.Graph,
		&i.ValidationSummary,
		&i.CreatedByUserID,
		&i.PublishedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const disableDataPipelineSchedule = `-- name: DisableDataPipelineSchedule :one
UPDATE data_pipeline_schedules
SET
    enabled = false,
    updated_at = now()
WHERE tenant_id = $1
  AND public_id = $2
RETURNING id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
`

type DisableDataPipelineScheduleParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) DisableDataPipelineSchedule(ctx context.Context, arg DisableDataPipelineScheduleParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, disableDataPipelineSchedule, arg.TenantID, arg.PublicID)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failDataPipelineRun = `-- name: FailDataPipelineRun :one
UPDATE data_pipeline_runs
SET
    status = 'failed',
    error_summary = left($1, 1000),
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $2
  AND id = $3
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
`

type FailDataPipelineRunParams struct {
	ErrorSummary string `json:"error_summary"`
	TenantID     int64  `json:"tenant_id"`
	ID           int64  `json:"id"`
}

func (q *Queries) FailDataPipelineRun(ctx context.Context, arg FailDataPipelineRunParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, failDataPipelineRun, arg.ErrorSummary, arg.TenantID, arg.ID)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failDataPipelineRunOutput = `-- name: FailDataPipelineRunOutput :one
UPDATE data_pipeline_run_outputs
SET
    status = 'failed',
    error_summary = left($1, 1000),
    metadata = $2,
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $3
  AND run_id = $4
  AND node_id = $5
RETURNING id, tenant_id, run_id, node_id, status, output_work_table_id, row_count, error_summary, metadata, started_at, completed_at, created_at, updated_at
`

type FailDataPipelineRunOutputParams struct {
	ErrorSummary string `json:"error_summary"`
	Metadata     []byte `json:"metadata"`
	TenantID     int64  `json:"tenant_id"`
	RunID        int64  `json:"run_id"`
	NodeID       string `json:"node_id"`
}

func (q *Queries) FailDataPipelineRunOutput(ctx context.Context, arg FailDataPipelineRunOutputParams) (DataPipelineRunOutput, error) {
	row := q.db.QueryRow(ctx, failDataPipelineRunOutput,
		arg.ErrorSummary,
		arg.Metadata,
		arg.TenantID,
		arg.RunID,
		arg.NodeID,
	)
	var i DataPipelineRunOutput
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.Status,
		&i.OutputWorkTableID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failDataPipelineRunStep = `-- name: FailDataPipelineRunStep :one
UPDATE data_pipeline_run_steps
SET
    status = 'failed',
    error_summary = left($1, 1000),
    error_sample = $2,
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $3
  AND run_id = $4
  AND node_id = $5
RETURNING id, tenant_id, run_id, node_id, step_type, status, row_count, error_summary, error_sample, metadata, started_at, completed_at, created_at, updated_at
`

type FailDataPipelineRunStepParams struct {
	ErrorSummary string `json:"error_summary"`
	ErrorSample  []byte `json:"error_sample"`
	TenantID     int64  `json:"tenant_id"`
	RunID        int64  `json:"run_id"`
	NodeID       string `json:"node_id"`
}

func (q *Queries) FailDataPipelineRunStep(ctx context.Context, arg FailDataPipelineRunStepParams) (DataPipelineRunStep, error) {
	row := q.db.QueryRow(ctx, failDataPipelineRunStep,
		arg.ErrorSummary,
		arg.ErrorSample,
		arg.TenantID,
		arg.RunID,
		arg.NodeID,
	)
	var i DataPipelineRunStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.StepType,
		&i.Status,
		&i.RowCount,
		&i.ErrorSummary,
		&i.ErrorSample,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishDataPipelineRun = `-- name: FinishDataPipelineRun :one
UPDATE data_pipeline_runs
SET
    status = $1,
    output_work_table_id = $2,
    row_count = $3,
    error_summary = NULLIF(left($4, 1000), ''),
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $5
  AND id = $6
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
`

type FinishDataPipelineRunParams struct {
	Status            string      `json:"status"`
	OutputWorkTableID pgtype.Int8 `json:"output_work_table_id"`
	RowCount          int64       `json:"row_count"`
	ErrorSummary      string      `json:"error_summary"`
	TenantID          int64       `json:"tenant_id"`
	ID                int64       `json:"id"`
}

func (q *Queries) FinishDataPipelineRun(ctx context.Context, arg FinishDataPipelineRunParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, finishDataPipelineRun,
		arg.Status,
		arg.OutputWorkTableID,
		arg.RowCount,
		arg.ErrorSummary,
		arg.TenantID,
		arg.ID,
	)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataPipelineByIDForTenant = `-- name: GetDataPipelineByIDForTenant :one
SELECT id, public_id, tenant_id, created_by_user_id, updated_by_user_id, name, description, status, published_version_id, created_at, updated_at, archived_at
FROM data_pipelines
WHERE tenant_id = $1
  AND id = $2
  AND archived_at IS NULL
LIMIT 1
`

type GetDataPipelineByIDForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetDataPipelineByIDForTenant(ctx context.Context, arg GetDataPipelineByIDForTenantParams) (DataPipeline, error) {
	row := q.db.QueryRow(ctx, getDataPipelineByIDForTenant, arg.TenantID, arg.ID)
	var i DataPipeline
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getDataPipelineForTenant = `-- name: GetDataPipelineForTenant :one
SELECT id, public_id, tenant_id, created_by_user_id, updated_by_user_id, name, description, status, published_version_id, created_at, updated_at, archived_at
FROM data_pipelines
WHERE tenant_id = $1
  AND public_id = $2
  AND archived_at IS NULL
LIMIT 1
`

type GetDataPipelineForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDataPipelineForTenant(ctx context.Context, arg GetDataPipelineForTenantParams) (DataPipeline, error) {
	row := q.db.QueryRow(ctx, getDataPipelineForTenant, arg.TenantID, arg.PublicID)
	var i DataPipeline
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getDataPipelineMappingExampleByPublicIDForTenant = `-- name: GetDataPipelineMappingExampleByPublicIDForTenant :one
SELECT
    e.id, e.public_id, e.tenant_id, e.pipeline_id, e.version_id, e.schema_column_id, e.source_column, e.sheet_name, e.sample_values, e.neighbor_columns, e.decision, e.decided_by_user_id, e.decided_at, e.shared_scope, e.shared_by_user_id, e.shared_at, e.created_at, e.updated_at,
    c.public_id AS schema_column_public_id,
    c.target_column
FROM data_pipeline_mapping_examples e
JOIN data_pipeline_schema_columns c
  ON c.tenant_id = e.tenant_id
 AND c.id = e.schema_column_id
WHERE e.tenant_id = $1
  AND e.public_id = $2
LIMIT 1
`

type GetDataPipelineMappingExampleByPublicIDForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

type GetDataPipelineMappingExampleByPublicIDForTenantRow struct {
	ID                   int64              `json:"id"`
	PublicID             uuid.UUID          `json:"public_id"`
	TenantID             int64              `json:"tenant_id"`
	PipelineID           int64              `json:"pipeline_id"`
	VersionID            pgtype.Int8        `json:"version_id"`
	SchemaColumnID       int64              `json:"schema_column_id"`
	SourceColumn         string             `json:"source_column"`
	SheetName            string             `json:"sheet_name"`
	SampleValues         []byte             `json:"sample_values"`
	NeighborColumns      []byte             `json:"neighbor_columns"`
	Decision             string             `json:"decision"`
	DecidedByUserID      pgtype.Int8        `json:"decided_by_user_id"`
	DecidedAt            pgtype.Timestamptz `json:"decided_at"`
	SharedScope          string             `json:"shared_scope"`
	SharedByUserID       pgtype.Int8        `json:"shared_by_user_id"`
	SharedAt             pgtype.Timestamptz `json:"shared_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	SchemaColumnPublicID uuid.UUID          `json:"schema_column_public_id"`
	TargetColumn         string             `json:"target_column"`
}

func (q *Queries) GetDataPipelineMappingExampleByPublicIDForTenant(ctx context.Context, arg GetDataPipelineMappingExampleByPublicIDForTenantParams) (GetDataPipelineMappingExampleByPublicIDForTenantRow, error) {
	row := q.db.QueryRow(ctx, getDataPipelineMappingExampleByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetDataPipelineMappingExampleByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.SchemaColumnID,
		&i.SourceColumn,
		&i.SheetName,
		&i.SampleValues,
		&i.NeighborColumns,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.SharedScope,
		&i.SharedByUserID,
		&i.SharedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchemaColumnPublicID,
		&i.TargetColumn,
	)
	return i, err
}

const getDataPipelineRunByIDForTenant = `-- name: GetDataPipelineRunByIDForTenant :one
SELECT id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
FROM data_pipeline_runs
WHERE tenant_id = $1
  AND id = $2
LIMIT 1
`

type GetDataPipelineRunByIDForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetDataPipelineRunByIDForTenant(ctx context.Context, arg GetDataPipelineRunByIDForTenantParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, getDataPipelineRunByIDForTenant, arg.TenantID, arg.ID)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataPipelineRunForTenant = `-- name: GetDataPipelineRunForTenant :one
SELECT id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
FROM data_pipeline_runs
WHERE tenant_id = $1
  AND public_id = $2
LIMIT 1
`

type GetDataPipelineRunForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDataPipelineRunForTenant(ctx context.Context, arg GetDataPipelineRunForTenantParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, getDataPipelineRunForTenant, arg.TenantID, arg.PublicID)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataPipelineScheduleForTenant = `-- name: GetDataPipelineScheduleForTenant :one
SELECT id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
FROM data_pipeline_schedules
WHERE tenant_id = $1
  AND public_id = $2
LIMIT 1
`

type GetDataPipelineScheduleForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDataPipelineScheduleForTenant(ctx context.Context, arg GetDataPipelineScheduleForTenantParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, getDataPipelineScheduleForTenant, arg.TenantID, arg.PublicID)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataPipelineSchemaColumnByIDForTenant = `-- name: GetDataPipelineSchemaColumnByIDForTenant :one
SELECT id, public_id, tenant_id, domain, schema_type, target_column, description, aliases, examples, language, version, archived_at, created_at, updated_at
FROM data_pipeline_schema_columns
WHERE tenant_id = $1
  AND id = $2
  AND archived_at IS NULL
LIMIT 1
`

type GetDataPipelineSchemaColumnByIDForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetDataPipelineSchemaColumnByIDForTenant(ctx context.Context, arg GetDataPipelineSchemaColumnByIDForTenantParams) (DataPipelineSchemaColumn, error) {
	row := q.db.QueryRow(ctx, getDataPipelineSchemaColumnByIDForTenant, arg.TenantID, arg.ID)
	var i DataPipelineSchemaColumn
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Domain,
		&i.SchemaType,
		&i.TargetColumn,
		&i.Description,
		&i.Aliases,
		&i.Examples,
		&i.Language,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataPipelineSchemaColumnByPublicIDForTenant = `-- name: GetDataPipelineSchemaColumnByPublicIDForTenant :one
SELECT id, public_id, tenant_id, domain, schema_type, target_column, description, aliases, examples, language, version, archived_at, created_at, updated_at
FROM data_pipeline_schema_columns
WHERE tenant_id = $1
  AND public_id = $2
  AND archived_at IS NULL
LIMIT 1
`

type GetDataPipelineSchemaColumnByPublicIDForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDataPipelineSchemaColumnByPublicIDForTenant(ctx context.Context, arg GetDataPipelineSchemaColumnByPublicIDForTenantParams) (DataPipelineSchemaColumn, error) {
	row := q.db.QueryRow(ctx, getDataPipelineSchemaColumnByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i DataPipelineSchemaColumn
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Domain,
		&i.SchemaType,
		&i.TargetColumn,
		&i.Description,
		&i.Aliases,
		&i.Examples,
		&i.Language,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataPipelineVersionByIDForTenant = `-- name: GetDataPipelineVersionByIDForTenant :one
SELECT id, public_id, tenant_id, pipeline_id, version_number, status, graph, validation_summary, created_by_user_id, published_by_user_id, created_at, published_at
FROM data_pipeline_versions
WHERE tenant_id = $1
  AND id = $2
LIMIT 1
`

type GetDataPipelineVersionByIDForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetDataPipelineVersionByIDForTenant(ctx context.Context, arg GetDataPipelineVersionByIDForTenantParams) (DataPipelineVersion, error) {
	row := q.db.QueryRow(ctx, getDataPipelineVersionByIDForTenant, arg.TenantID, arg.ID)
	var i DataPipelineVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionNumber,
		&i.Status,
		&i.Graph,
		&i.ValidationSummary,
		&i.CreatedByUserID,
		&i.PublishedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getDataPipelineVersionForTenant = `-- name: GetDataPipelineVersionForTenant :one
SELECT id, public_id, tenant_id, pipeline_id, version_number, status, graph, validation_summary, created_by_user_id, published_by_user_id, created_at, published_at
FROM data_pipeline_versions
WHERE tenant_id = $1
  AND public_id = $2
LIMIT 1
`

type GetDataPipelineVersionForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDataPipelineVersionForTenant(ctx context.Context, arg GetDataPipelineVersionForTenantParams) (DataPipelineVersion, error) {
	row := q.db.QueryRow(ctx, getDataPipelineVersionForTenant, arg.TenantID, arg.PublicID)
	var i DataPipelineVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionNumber,
		&i.Status,
		&i.Graph,
		&i.ValidationSummary,
		&i.CreatedByUserID,
		&i.PublishedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listDataPipelineMappingExamplesForIndex = `-- name: ListDataPipelineMappingExamplesForIndex :many
SELECT
    e.id,
    e.public_id,
    e.tenant_id,
    e.pipeline_id,
    e.version_id,
    e.schema_column_id,
    e.source_column,
    e.sheet_name,
    e.sample_values,
    e.neighbor_columns,
    e.decision,
    e.decided_by_user_id,
    e.decided_at,
    e.shared_scope,
    e.shared_by_user_id,
    e.shared_at,
    e.created_at,
    e.updated_at,
    c.target_column
FROM data_pipeline_mapping_examples e
JOIN data_pipeline_schema_columns c
  ON c.tenant_id = e.tenant_id
 AND c.id = e.schema_column_id
 AND c.archived_at IS NULL
WHERE e.tenant_id = $1
ORDER BY e.id
LIMIT $2
`

type ListDataPipelineMappingExamplesForIndexParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

type ListDataPipelineMappingExamplesForIndexRow struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	PipelineID      int64              `json:"pipeline_id"`
	VersionID       pgtype.Int8        `json:"version_id"`
	SchemaColumnID  int64              `json:"schema_column_id"`
	SourceColumn    string             `json:"source_column"`
	SheetName       string             `json:"sheet_name"`
	SampleValues    []byte             `json:"sample_values"`
	NeighborColumns []byte             `json:"neighbor_columns"`
	Decision        string             `json:"decision"`
	DecidedByUserID pgtype.Int8        `json:"decided_by_user_id"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	SharedScope     string             `json:"shared_scope"`
	SharedByUserID  pgtype.Int8        `json:"shared_by_user_id"`
	SharedAt        pgtype.Timestamptz `json:"shared_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TargetColumn    string             `json:"target_column"`
}

func (q *Queries) ListDataPipelineMappingExamplesForIndex(ctx context.Context, arg ListDataPipelineMappingExamplesForIndexParams) ([]ListDataPipelineMappingExamplesForIndexRow, error) {
	rows, err := q.db.Query(ctx, listDataPipelineMappingExamplesForIndex, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDataPipelineMappingExamplesForIndexRow
	for rows.Next() {
		var i ListDataPipelineMappingExamplesForIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineID,
			&i.VersionID,
			&i.SchemaColumnID,
			&i.SourceColumn,
			&i.SheetName,
			&i.SampleValues,
			&i.NeighborColumns,
			&i.Decision,
			&i.DecidedByUserID,
			&i.DecidedAt,
			&i.SharedScope,
			&i.SharedByUserID,
			&i.SharedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetColumn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineRunOutputs = `-- name: ListDataPipelineRunOutputs :many
SELECT id, tenant_id, run_id, node_id, status, output_work_table_id, row_count, error_summary, metadata, started_at, completed_at, created_at, updated_at
FROM data_pipeline_run_outputs
WHERE tenant_id = $1
  AND run_id = $2
ORDER BY id ASC
`

type ListDataPipelineRunOutputsParams struct {
	TenantID int64 `json:"tenant_id"`
	RunID    int64 `json:"run_id"`
}

func (q *Queries) ListDataPipelineRunOutputs(ctx context.Context, arg ListDataPipelineRunOutputsParams) ([]DataPipelineRunOutput, error) {
	rows, err := q.db.Query(ctx, listDataPipelineRunOutputs, arg.TenantID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineRunOutput
	for rows.Next() {
		var i DataPipelineRunOutput
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RunID,
			&i.NodeID,
			&i.Status,
			&i.OutputWorkTableID,
			&i.RowCount,
			&i.ErrorSummary,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineRunSteps = `-- name: ListDataPipelineRunSteps :many
SELECT id, tenant_id, run_id, node_id, step_type, status, row_count, error_summary, error_sample, metadata, started_at, completed_at, created_at, updated_at
FROM data_pipeline_run_steps
WHERE tenant_id = $1
  AND run_id = $2
ORDER BY id ASC
`

type ListDataPipelineRunStepsParams struct {
	TenantID int64 `json:"tenant_id"`
	RunID    int64 `json:"run_id"`
}

func (q *Queries) ListDataPipelineRunSteps(ctx context.Context, arg ListDataPipelineRunStepsParams) ([]DataPipelineRunStep, error) {
	rows, err := q.db.Query(ctx, listDataPipelineRunSteps, arg.TenantID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineRunStep
	for rows.Next() {
		var i DataPipelineRunStep
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RunID,
			&i.NodeID,
			&i.StepType,
			&i.Status,
			&i.RowCount,
			&i.ErrorSummary,
			&i.ErrorSample,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineRuns = `-- name: ListDataPipelineRuns :many
SELECT id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
FROM data_pipeline_runs
WHERE tenant_id = $1
  AND pipeline_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListDataPipelineRunsParams struct {
	TenantID   int64 `json:"tenant_id"`
	PipelineID int64 `json:"pipeline_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListDataPipelineRuns(ctx context.Context, arg ListDataPipelineRunsParams) ([]DataPipelineRun, error) {
	rows, err := q.db.Query(ctx, listDataPipelineRuns, arg.TenantID, arg.PipelineID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineRun
	for rows.Next() {
		var i DataPipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineID,
			&i.VersionID,
			&i.ScheduleID,
			&i.RequestedByUserID,
			&i.TriggerKind,
			&i.Status,
			&i.OutputWorkTableID,
			&i.OutboxEventID,
			&i.RowCount,
			&i.ErrorSummary,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineSchedules = `-- name: ListDataPipelineSchedules :many
SELECT id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
FROM data_pipeline_schedules
WHERE tenant_id = $1
  AND pipeline_id = $2
ORDER BY updated_at DESC, id DESC
`

type ListDataPipelineSchedulesParams struct {
	TenantID   int64 `json:"tenant_id"`
	PipelineID int64 `json:"pipeline_id"`
}

func (q *Queries) ListDataPipelineSchedules(ctx context.Context, arg ListDataPipelineSchedulesParams) ([]DataPipelineSchedule, error) {
	rows, err := q.db.Query(ctx, listDataPipelineSchedules, arg.TenantID, arg.PipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineSchedule
	for rows.Next() {
		var i DataPipelineSchedule
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineID,
			&i.VersionID,
			&i.CreatedByUserID,
			&i.Frequency,
			&i.Timezone,
			&i.RunTime,
			&i.Weekday,
			&i.MonthDay,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastErrorSummary,
			&i.LastRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineSchemaColumnsForIndex = `-- name: ListDataPipelineSchemaColumnsForIndex :many
SELECT id, public_id, tenant_id, domain, schema_type, target_column, description, aliases, examples, language, version, archived_at, created_at, updated_at
FROM data_pipeline_schema_columns
WHERE tenant_id = $1
  AND archived_at IS NULL
ORDER BY id
LIMIT $2
`

type ListDataPipelineSchemaColumnsForIndexParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListDataPipelineSchemaColumnsForIndex(ctx context.Context, arg ListDataPipelineSchemaColumnsForIndexParams) ([]DataPipelineSchemaColumn, error) {
	rows, err := q.db.Query(ctx, listDataPipelineSchemaColumnsForIndex, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineSchemaColumn
	for rows.Next() {
		var i DataPipelineSchemaColumn
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Domain,
			&i.SchemaType,
			&i.TargetColumn,
			&i.Description,
			&i.Aliases,
			&i.Examples,
			&i.Language,
			&i.Version,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineVersions = `-- name: ListDataPipelineVersions :many
SELECT id, public_id, tenant_id, pipeline_id, version_number, status, graph, validation_summary, created_by_user_id, published_by_user_id, created_at, published_at
FROM data_pipeline_versions
WHERE tenant_id = $1
  AND pipeline_id = $2
ORDER BY version_number DESC, id DESC
LIMIT $3
`

type ListDataPipelineVersionsParams struct {
	TenantID   int64 `json:"tenant_id"`
	PipelineID int64 `json:"pipeline_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListDataPipelineVersions(ctx context.Context, arg ListDataPipelineVersionsParams) ([]DataPipelineVersion, error) {
	rows, err := q.db.Query(ctx, listDataPipelineVersions, arg.TenantID, arg.PipelineID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineVersion
	for rows.Next() {
		var i DataPipelineVersion
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineID,
			&i.VersionNumber,
			&i.Status,
			&i.Graph,
			&i.ValidationSummary,
			&i.CreatedByUserID,
			&i.PublishedByUserID,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelines = `-- name: ListDataPipelines :many
WITH base AS (
    SELECT
        p.id, p.public_id, p.tenant_id, p.created_by_user_id, p.updated_by_user_id, p.name, p.description, p.status, p.published_version_id, p.created_at, p.updated_at, p.archived_at,
        latest_run.public_id AS latest_run_public_id,
        latest_run.status AS latest_run_status,
        latest_run.created_at AS latest_run_at,
        COALESCE(schedule_summary.enabled_schedule_count, 0)::bigint AS enabled_schedule_count,
        COALESCE(schedule_summary.disabled_schedule_count, 0)::bigint AS disabled_schedule_count,
        schedule_summary.next_run_at,
        CASE
            WHEN COALESCE(schedule_summary.enabled_schedule_count, 0) > 0 THEN 'enabled'
            WHEN COALESCE(schedule_summary.disabled_schedule_count, 0) > 0 THEN 'disabled'
            ELSE 'none'
        END AS schedule_state
    FROM data_pipelines p
    LEFT JOIN LATERAL (
        SELECT public_id, status, created_at
        FROM data_pipeline_runs r
        WHERE r.tenant_id = p.tenant_id
          AND r.pipeline_id = p.id
        ORDER BY r.created_at DESC, r.id DESC
        LIMIT 1
    ) latest_run ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            COUNT(*) FILTER (WHERE enabled)::bigint AS enabled_schedule_count,
            COUNT(*) FILTER (WHERE NOT enabled)::bigint AS disabled_schedule_count,
            MIN(next_run_at) FILTER (WHERE enabled) AS next_run_at
        FROM data_pipeline_schedules s
        WHERE s.tenant_id = p.tenant_id
          AND s.pipeline_id = p.id
    ) schedule_summary ON TRUE
    WHERE p.tenant_id = $11
      AND p.archived_at IS NULL
)
SELECT
    id,
    public_id,
    tenant_id,
    created_by_user_id,
    updated_by_user_id,
    name,
    description,
    status,
    published_version_id,
    created_at,
    updated_at,
    archived_at,
    COALESCE(latest_run_public_id::text, '') AS latest_run_public_id,
    COALESCE(latest_run_status, '') AS latest_run_status,
    latest_run_at,
    schedule_state,
    enabled_schedule_count,
    disabled_schedule_count,
    next_run_at::timestamptz AS next_run_at
FROM base
WHERE (
    $1::text IS NULL
    OR btrim($1::text) = ''
    OR name ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%'
    OR public_id::text ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR status = $2::text
)
AND (
    $3::text = 'all'
    OR ($3::text = 'published' AND published_version_id IS NOT NULL)
    OR ($3::text = 'unpublished' AND published_version_id IS NULL)
)
AND (
    $4::text IS NULL
    OR latest_run_status = $4::text
)
AND (
    $5::text = 'all'
    OR schedule_state = $5::text
)
AND (
    $6::bigint IS NULL
    OR (
        $7::text = 'updated_desc'
        AND (updated_at, id) < ($8::timestamptz, $6::bigint)
    )
    OR (
        $7::text = 'updated_asc'
        AND (updated_at, id) > ($8::timestamptz, $6::bigint)
    )
    OR (
        $7::text = 'created_desc'
        AND (created_at, id) < ($8::timestamptz, $6::bigint)
    )
    OR (
        $7::text = 'created_asc'
        AND (created_at, id) > ($8::timestamptz, $6::bigint)
    )
    OR (
        $7::text = 'name_asc'
        AND (lower(name), id) > ($9::text, $6::bigint)
    )
    OR (
        $7::text = 'name_desc'
        AND (lower(name), id) < ($9::text, $6::bigint)
    )
    OR (
        $7::text = 'latest_run_desc'
        AND (COALESCE(latest_run_at, '0001-01-02'::timestamptz), id) < ($8::timestamptz, $6::bigint)
    )
)
ORDER BY
    CASE WHEN $7::text = 'updated_desc' THEN updated_at END DESC,
    CASE WHEN $7::text = 'updated_asc' THEN updated_at END ASC,
    CASE WHEN $7::text = 'created_desc' THEN created_at END DESC,
    CASE WHEN $7::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $7::text = 'name_asc' THEN lower(name) END ASC,
    CASE WHEN $7::text = 'name_desc' THEN lower(name) END DESC,
    CASE WHEN $7::text = 'latest_run_desc' THEN COALESCE(latest_run_at, '0001-01-02'::timestamptz) END DESC,
    CASE WHEN $7::text IN ('updated_desc', 'created_desc', 'name_desc', 'latest_run_desc') THEN id END DESC,
    CASE WHEN $7::text IN ('updated_asc', 'created_asc', 'name_asc') THEN id END ASC
LIMIT $10
`

type ListDataPipelinesParams struct {
	Q                   pgtype.Text        `json:"q"`
	Status              pgtype.Text        `json:"status"`
	Publication         string             `json:"publication"`
	RunStatus           pgtype.Text        `json:"run_status"`
	ScheduleStateFilter string             `json:"schedule_state_filter"`
	CursorID            pgtype.Int8        `json:"cursor_id"`
	SortKey             string             `json:"sort_key"`
	CursorTime          pgtype.Timestamptz `json:"cursor_time"`
	CursorText          pgtype.Text        `json:"cursor_text"`
	ResultLimit         int32              `json:"result_limit"`
	TenantID            int64              `json:"tenant_id"`
}

type ListDataPipelinesRow struct {
	ID                    int64              `json:"id"`
	PublicID              uuid.UUID          `json:"public_id"`
	TenantID              int64              `json:"tenant_id"`
	CreatedByUserID       pgtype.Int8        `json:"created_by_user_id"`
	UpdatedByUserID       pgtype.Int8        `json:"updated_by_user_id"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	Status                string             `json:"status"`
	PublishedVersionID    pgtype.Int8        `json:"published_version_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	LatestRunPublicID     interface{}        `json:"latest_run_public_id"`
	LatestRunStatus       string             `json:"latest_run_status"`
	LatestRunAt           pgtype.Timestamptz `json:"latest_run_at"`
	ScheduleState         string             `json:"schedule_state"`
	EnabledScheduleCount  int64              `json:"enabled_schedule_count"`
	DisabledScheduleCount int64              `json:"disabled_schedule_count"`
	NextRunAt             pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) ListDataPipelines(ctx context.Context, arg ListDataPipelinesParams) ([]ListDataPipelinesRow, error) {
	rows, err := q.db.Query(ctx, listDataPipelines,
		arg.Q,
		arg.Status,
		arg.Publication,
		arg.RunStatus,
		arg.ScheduleStateFilter,
		arg.CursorID,
		arg.SortKey,
		arg.CursorTime,
		arg.CursorText,
		arg.ResultLimit,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDataPipelinesRow
	for rows.Next() {
		var i ListDataPipelinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.PublishedVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.LatestRunPublicID,
			&i.LatestRunStatus,
			&i.LatestRunAt,
			&i.ScheduleState,
			&i.EnabledScheduleCount,
			&i.DisabledScheduleCount,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAdminDataPipelineMappingExamples = `-- name: ListTenantAdminDataPipelineMappingExamples :many
SELECT
    e.public_id,
    e.source_column,
    e.sheet_name,
    e.sample_values,
    e.neighbor_columns,
    e.decision,
    e.shared_scope,
    e.decided_at,
    e.shared_at,
    e.created_at,
    e.updated_at,
    p.public_id AS pipeline_public_id,
    p.name AS pipeline_name,
    c.public_id AS schema_column_public_id,
    c.domain,
    c.schema_type,
    c.target_column,
    EXISTS (
        SELECT 1
        FROM local_search_documents d
        WHERE d.tenant_id = e.tenant_id
          AND d.resource_kind = 'mapping_example'
          AND d.resource_id = e.id
    ) AS search_document_materialized
FROM data_pipeline_mapping_examples e
JOIN data_pipelines p
  ON p.tenant_id = e.tenant_id
 AND p.id = e.pipeline_id
JOIN data_pipeline_schema_columns c
  ON c.tenant_id = e.tenant_id
 AND c.id = e.schema_column_id
WHERE e.tenant_id = $1
  AND (
      $2::text IS NULL
      OR e.shared_scope = $2::text
  )
  AND (
      $3::text IS NULL
      OR e.decision = $3::text
  )
  AND (
      $4::text IS NULL
      OR e.source_column ILIKE '%' || $4::text || '%'
      OR c.target_column ILIKE '%' || $4::text || '%'
      OR p.name ILIKE '%' || $4::text || '%'
      OR c.domain ILIKE '%' || $4::text || '%'
      OR c.schema_type ILIKE '%' || $4::text || '%'
  )
ORDER BY e.updated_at DESC, e.id DESC
LIMIT $5
`

type ListTenantAdminDataPipelineMappingExamplesParams struct {
	TenantID    int64       `json:"tenant_id"`
	SharedScope pgtype.Text `json:"shared_scope"`
	Decision    pgtype.Text `json:"decision"`
	Query       pgtype.Text `json:"query"`
	LimitCount  int32       `json:"limit_count"`
}

type ListTenantAdminDataPipelineMappingExamplesRow struct {
	PublicID                   uuid.UUID          `json:"public_id"`
	SourceColumn               string             `json:"source_column"`
	SheetName                  string             `json:"sheet_name"`
	SampleValues               []byte             `json:"sample_values"`
	NeighborColumns            []byte             `json:"neighbor_columns"`
	Decision                   string             `json:"decision"`
	SharedScope                string             `json:"shared_scope"`
	DecidedAt                  pgtype.Timestamptz `json:"decided_at"`
	SharedAt                   pgtype.Timestamptz `json:"shared_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	PipelinePublicID           uuid.UUID          `json:"pipeline_public_id"`
	PipelineName               string             `json:"pipeline_name"`
	SchemaColumnPublicID       uuid.UUID          `json:"schema_column_public_id"`
	Domain                     string             `json:"domain"`
	SchemaType                 string             `json:"schema_type"`
	TargetColumn               string             `json:"target_column"`
	SearchDocumentMaterialized bool               `json:"search_document_materialized"`
}

func (q *Queries) ListTenantAdminDataPipelineMappingExamples(ctx context.Context, arg ListTenantAdminDataPipelineMappingExamplesParams) ([]ListTenantAdminDataPipelineMappingExamplesRow, error) {
	rows, err := q.db.Query(ctx, listTenantAdminDataPipelineMappingExamples,
		arg.TenantID,
		arg.SharedScope,
		arg.Decision,
		arg.Query,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantAdminDataPipelineMappingExamplesRow
	for rows.Next() {
		var i ListTenantAdminDataPipelineMappingExamplesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.SourceColumn,
			&i.SheetName,
			&i.SampleValues,
			&i.NeighborColumns,
			&i.Decision,
			&i.SharedScope,
			&i.DecidedAt,
			&i.SharedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PipelinePublicID,
			&i.PipelineName,
			&i.SchemaColumnPublicID,
			&i.Domain,
			&i.SchemaType,
			&i.TargetColumn,
			&i.SearchDocumentMaterialized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDataPipelineRunOutputProcessing = `-- name: MarkDataPipelineRunOutputProcessing :one
UPDATE data_pipeline_run_outputs
SET
    status = 'processing',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE tenant_id = $1
  AND run_id = $2
  AND node_id = $3
RETURNING id, tenant_id, run_id, node_id, status, output_work_table_id, row_count, error_summary, metadata, started_at, completed_at, created_at, updated_at
`

type MarkDataPipelineRunOutputProcessingParams struct {
	TenantID int64  `json:"tenant_id"`
	RunID    int64  `json:"run_id"`
	NodeID   string `json:"node_id"`
}

func (q *Queries) MarkDataPipelineRunOutputProcessing(ctx context.Context, arg MarkDataPipelineRunOutputProcessingParams) (DataPipelineRunOutput, error) {
	row := q.db.QueryRow(ctx, markDataPipelineRunOutputProcessing, arg.TenantID, arg.RunID, arg.NodeID)
	var i DataPipelineRunOutput
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.Status,
		&i.OutputWorkTableID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDataPipelineRunProcessing = `-- name: MarkDataPipelineRunProcessing :one
UPDATE data_pipeline_runs
SET
    status = 'processing',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status IN ('pending', 'processing')
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
`

type MarkDataPipelineRunProcessingParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) MarkDataPipelineRunProcessing(ctx context.Context, arg MarkDataPipelineRunProcessingParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, markDataPipelineRunProcessing, arg.TenantID, arg.ID)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDataPipelineRunStepProcessing = `-- name: MarkDataPipelineRunStepProcessing :one
UPDATE data_pipeline_run_steps
SET
    status = 'processing',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE tenant_id = $1
  AND run_id = $2
  AND node_id = $3
RETURNING id, tenant_id, run_id, node_id, step_type, status, row_count, error_summary, error_sample, metadata, started_at, completed_at, created_at, updated_at
`

type MarkDataPipelineRunStepProcessingParams struct {
	TenantID int64  `json:"tenant_id"`
	RunID    int64  `json:"run_id"`
	NodeID   string `json:"node_id"`
}

func (q *Queries) MarkDataPipelineRunStepProcessing(ctx context.Context, arg MarkDataPipelineRunStepProcessingParams) (DataPipelineRunStep, error) {
	row := q.db.QueryRow(ctx, markDataPipelineRunStepProcessing, arg.TenantID, arg.RunID, arg.NodeID)
	var i DataPipelineRunStep
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RunID,
		&i.NodeID,
		&i.StepType,
		&i.Status,
		&i.RowCount,
		&i.ErrorSummary,
		&i.ErrorSample,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDataPipelineScheduleCreated = `-- name: MarkDataPipelineScheduleCreated :one
UPDATE data_pipeline_schedules
SET
    last_run_at = $1,
    last_status = 'created',
    last_error_summary = NULL,
    last_run_id = $2,
    next_run_at = $3,
    updated_at = now()
WHERE tenant_id = $4
  AND id = $5
RETURNING id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
`

type MarkDataPipelineScheduleCreatedParams struct {
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	LastRunID pgtype.Int8        `json:"last_run_id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	TenantID  int64              `json:"tenant_id"`
	ID        int64              `json:"id"`
}

func (q *Queries) MarkDataPipelineScheduleCreated(ctx context.Context, arg MarkDataPipelineScheduleCreatedParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, markDataPipelineScheduleCreated,
		arg.LastRunAt,
		arg.LastRunID,
		arg.NextRunAt,
		arg.TenantID,
		arg.ID,
	)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDataPipelineScheduleFailed = `-- name: MarkDataPipelineScheduleFailed :one
UPDATE data_pipeline_schedules
SET
    enabled = $1,
    last_run_at = $2,
    last_status = $3,
    last_error_summary = left($4, 1000),
    next_run_at = $5,
    updated_at = now()
WHERE tenant_id = $6
  AND id = $7
RETURNING id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
`

type MarkDataPipelineScheduleFailedParams struct {
	Enabled      bool               `json:"enabled"`
	LastRunAt    pgtype.Timestamptz `json:"last_run_at"`
	LastStatus   pgtype.Text        `json:"last_status"`
	ErrorSummary string             `json:"error_summary"`
	NextRunAt    pgtype.Timestamptz `json:"next_run_at"`
	TenantID     int64              `json:"tenant_id"`
	ID           int64              `json:"id"`
}

func (q *Queries) MarkDataPipelineScheduleFailed(ctx context.Context, arg MarkDataPipelineScheduleFailedParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, markDataPipelineScheduleFailed,
		arg.Enabled,
		arg.LastRunAt,
		arg.LastStatus,
		arg.ErrorSummary,
		arg.NextRunAt,
		arg.TenantID,
		arg.ID,
	)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDataPipelineScheduleSkipped = `-- name: MarkDataPipelineScheduleSkipped :one
UPDATE data_pipeline_schedules
SET
    last_run_at = $1,
    last_status = 'skipped',
    last_error_summary = left($2, 1000),
    next_run_at = $3,
    updated_at = now()
WHERE tenant_id = $4
  AND id = $5
RETURNING id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
`

type MarkDataPipelineScheduleSkippedParams struct {
	LastRunAt    pgtype.Timestamptz `json:"last_run_at"`
	ErrorSummary string             `json:"error_summary"`
	NextRunAt    pgtype.Timestamptz `json:"next_run_at"`
	TenantID     int64              `json:"tenant_id"`
	ID           int64              `json:"id"`
}

func (q *Queries) MarkDataPipelineScheduleSkipped(ctx context.Context, arg MarkDataPipelineScheduleSkippedParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, markDataPipelineScheduleSkipped,
		arg.LastRunAt,
		arg.ErrorSummary,
		arg.NextRunAt,
		arg.TenantID,
		arg.ID,
	)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishDataPipelineVersion = `-- name: PublishDataPipelineVersion :one
UPDATE data_pipeline_versions
SET
    status = 'published',
    validation_summary = $1,
    published_by_user_id = $2,
    published_at = now()
WHERE tenant_id = $3
  AND public_id = $4
  AND status <> 'archived'
RETURNING id, public_id, tenant_id, pipeline_id, version_number, status, graph, validation_summary, created_by_user_id, published_by_user_id, created_at, published_at
`

type PublishDataPipelineVersionParams struct {
	ValidationSummary []byte      `json:"validation_summary"`
	PublishedByUserID pgtype.Int8 `json:"published_by_user_id"`
	TenantID          int64       `json:"tenant_id"`
	PublicID          uuid.UUID   `json:"public_id"`
}

func (q *Queries) PublishDataPipelineVersion(ctx context.Context, arg PublishDataPipelineVersionParams) (DataPipelineVersion, error) {
	row := q.db.QueryRow(ctx, publishDataPipelineVersion,
		arg.ValidationSummary,
		arg.PublishedByUserID,
		arg.TenantID,
		arg.PublicID,
	)
	var i DataPipelineVersion
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionNumber,
		&i.Status,
		&i.Graph,
		&i.ValidationSummary,
		&i.CreatedByUserID,
		&i.PublishedByUserID,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const searchDataPipelineSchemaMappingCandidates = `-- name: SearchDataPipelineSchemaMappingCandidates :many
SELECT
    c.id,
    c.public_id,
    c.target_column,
    c.description,
    c.aliases,
    c.examples,
    d.public_id AS document_public_id,
    d.snippet,
    ts_rank_cd(d.search_vector, websearch_to_tsquery('simple', $1::text))::float8 AS keyword_score
FROM data_pipeline_schema_columns c
JOIN local_search_documents d
  ON d.tenant_id = c.tenant_id
 AND d.resource_kind = 'schema_column'
 AND d.resource_id = c.id
WHERE c.tenant_id = $2
  AND c.archived_at IS NULL
  AND (
      $3::text IS NULL
      OR c.domain = $3::text
  )
  AND (
      $4::text IS NULL
      OR c.schema_type = $4::text
  )
  AND (
      d.search_vector @@ websearch_to_tsquery('simple', $1::text)
      OR d.title ILIKE '%' || $1::text || '%'
      OR d.body_text ILIKE '%' || $1::text || '%'
  )
ORDER BY keyword_score DESC, c.updated_at DESC, c.id DESC
LIMIT $5
`

type SearchDataPipelineSchemaMappingCandidatesParams struct {
	Query      string      `json:"query"`
	TenantID   int64       `json:"tenant_id"`
	Domain     pgtype.Text `json:"domain"`
	SchemaType pgtype.Text `json:"schema_type"`
	LimitCount int32       `json:"limit_count"`
}

type SearchDataPipelineSchemaMappingCandidatesRow struct {
	ID               int64     `json:"id"`
	PublicID         uuid.UUID `json:"public_id"`
	TargetColumn     string    `json:"target_column"`
	Description      string    `json:"description"`
	Aliases          []byte    `json:"aliases"`
	Examples         []byte    `json:"examples"`
	DocumentPublicID uuid.UUID `json:"document_public_id"`
	Snippet          string    `json:"snippet"`
	KeywordScore     float64   `json:"keyword_score"`
}

func (q *Queries) SearchDataPipelineSchemaMappingCandidates(ctx context.Context, arg SearchDataPipelineSchemaMappingCandidatesParams) ([]SearchDataPipelineSchemaMappingCandidatesRow, error) {
	rows, err := q.db.Query(ctx, searchDataPipelineSchemaMappingCandidates,
		arg.Query,
		arg.TenantID,
		arg.Domain,
		arg.SchemaType,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDataPipelineSchemaMappingCandidatesRow
	for rows.Next() {
		var i SearchDataPipelineSchemaMappingCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TargetColumn,
			&i.Description,
			&i.Aliases,
			&i.Examples,
			&i.DocumentPublicID,
			&i.Snippet,
			&i.KeywordScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDataPipelinePublishedVersion = `-- name: SetDataPipelinePublishedVersion :one
UPDATE data_pipelines
SET
    status = 'published',
    published_version_id = $1,
    updated_by_user_id = $2,
    updated_at = now()
WHERE tenant_id = $3
  AND id = $4
  AND archived_at IS NULL
RETURNING id, public_id, tenant_id, created_by_user_id, updated_by_user_id, name, description, status, published_version_id, created_at, updated_at, archived_at
`

type SetDataPipelinePublishedVersionParams struct {
	VersionID       pgtype.Int8 `json:"version_id"`
	UpdatedByUserID pgtype.Int8 `json:"updated_by_user_id"`
	TenantID        int64       `json:"tenant_id"`
	PipelineID      int64       `json:"pipeline_id"`
}

func (q *Queries) SetDataPipelinePublishedVersion(ctx context.Context, arg SetDataPipelinePublishedVersionParams) (DataPipeline, error) {
	row := q.db.QueryRow(ctx, setDataPipelinePublishedVersion,
		arg.VersionID,
		arg.UpdatedByUserID,
		arg.TenantID,
		arg.PipelineID,
	)
	var i DataPipeline
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const setDataPipelineRunOutboxEvent = `-- name: SetDataPipelineRunOutboxEvent :one
UPDATE data_pipeline_runs
SET
    outbox_event_id = $1,
    updated_at = now()
WHERE tenant_id = $2
  AND id = $3
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schedule_id, requested_by_user_id, trigger_kind, status, output_work_table_id, outbox_event_id, row_count, error_summary, started_at, completed_at, created_at, updated_at
`

type SetDataPipelineRunOutboxEventParams struct {
	OutboxEventID pgtype.Int8 `json:"outbox_event_id"`
	TenantID      int64       `json:"tenant_id"`
	ID            int64       `json:"id"`
}

func (q *Queries) SetDataPipelineRunOutboxEvent(ctx context.Context, arg SetDataPipelineRunOutboxEventParams) (DataPipelineRun, error) {
	row := q.db.QueryRow(ctx, setDataPipelineRunOutboxEvent, arg.OutboxEventID, arg.TenantID, arg.ID)
	var i DataPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.ScheduleID,
		&i.RequestedByUserID,
		&i.TriggerKind,
		&i.Status,
		&i.OutputWorkTableID,
		&i.OutboxEventID,
		&i.RowCount,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDataPipeline = `-- name: UpdateDataPipeline :one
UPDATE data_pipelines
SET
    name = $1,
    description = $2,
    updated_by_user_id = $3,
    updated_at = now()
WHERE tenant_id = $4
  AND public_id = $5
  AND archived_at IS NULL
RETURNING id, public_id, tenant_id, created_by_user_id, updated_by_user_id, name, description, status, published_version_id, created_at, updated_at, archived_at
`

type UpdateDataPipelineParams struct {
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	UpdatedByUserID pgtype.Int8 `json:"updated_by_user_id"`
	TenantID        int64       `json:"tenant_id"`
	PublicID        uuid.UUID   `json:"public_id"`
}

func (q *Queries) UpdateDataPipeline(ctx context.Context, arg UpdateDataPipelineParams) (DataPipeline, error) {
	row := q.db.QueryRow(ctx, updateDataPipeline,
		arg.Name,
		arg.Description,
		arg.UpdatedByUserID,
		arg.TenantID,
		arg.PublicID,
	)
	var i DataPipeline
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateDataPipelineMappingExampleSharing = `-- name: UpdateDataPipelineMappingExampleSharing :one
UPDATE data_pipeline_mapping_examples
SET
    shared_scope = $1,
    shared_by_user_id = CASE
        WHEN $1::text = 'tenant' THEN $2::bigint
        ELSE NULL
    END,
    shared_at = CASE
        WHEN $1::text = 'tenant' THEN now()
        ELSE NULL
    END,
    updated_at = now()
WHERE tenant_id = $3
  AND public_id = $4
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schema_column_id, source_column, sheet_name, sample_values, neighbor_columns, decision, decided_by_user_id, decided_at, shared_scope, shared_by_user_id, shared_at, created_at, updated_at
`

type UpdateDataPipelineMappingExampleSharingParams struct {
	SharedScope    string      `json:"shared_scope"`
	SharedByUserID pgtype.Int8 `json:"shared_by_user_id"`
	TenantID       int64       `json:"tenant_id"`
	PublicID       uuid.UUID   `json:"public_id"`
}

func (q *Queries) UpdateDataPipelineMappingExampleSharing(ctx context.Context, arg UpdateDataPipelineMappingExampleSharingParams) (DataPipelineMappingExample, error) {
	row := q.db.QueryRow(ctx, updateDataPipelineMappingExampleSharing,
		arg.SharedScope,
		arg.SharedByUserID,
		arg.TenantID,
		arg.PublicID,
	)
	var i DataPipelineMappingExample
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.SchemaColumnID,
		&i.SourceColumn,
		&i.SheetName,
		&i.SampleValues,
		&i.NeighborColumns,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.SharedScope,
		&i.SharedByUserID,
		&i.SharedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDataPipelineSchedule = `-- name: UpdateDataPipelineSchedule :one
UPDATE data_pipeline_schedules
SET
    frequency = $1,
    timezone = $2,
    run_time = $3,
    weekday = $4,
    month_day = $5,
    enabled = $6,
    next_run_at = $7,
    updated_at = now()
WHERE tenant_id = $8
  AND public_id = $9
RETURNING id, public_id, tenant_id, pipeline_id, version_id, created_by_user_id, frequency, timezone, run_time, weekday, month_day, enabled, next_run_at, last_run_at, last_status, last_error_summary, last_run_id, created_at, updated_at
`

type UpdateDataPipelineScheduleParams struct {
	Frequency string             `json:"frequency"`
	Timezone  string             `json:"timezone"`
	RunTime   string             `json:"run_time"`
	Weekday   pgtype.Int2        `json:"weekday"`
	MonthDay  pgtype.Int2        `json:"month_day"`
	Enabled   bool               `json:"enabled"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
	TenantID  int64              `json:"tenant_id"`
	PublicID  uuid.UUID          `json:"public_id"`
}

func (q *Queries) UpdateDataPipelineSchedule(ctx context.Context, arg UpdateDataPipelineScheduleParams) (DataPipelineSchedule, error) {
	row := q.db.QueryRow(ctx, updateDataPipelineSchedule,
		arg.Frequency,
		arg.Timezone,
		arg.RunTime,
		arg.Weekday,
		arg.MonthDay,
		arg.Enabled,
		arg.NextRunAt,
		arg.TenantID,
		arg.PublicID,
	)
	var i DataPipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.CreatedByUserID,
		&i.Frequency,
		&i.Timezone,
		&i.RunTime,
		&i.Weekday,
		&i.MonthDay,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastErrorSummary,
		&i.LastRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDataPipelineMappingExample = `-- name: UpsertDataPipelineMappingExample :one
INSERT INTO data_pipeline_mapping_examples (
    tenant_id,
    pipeline_id,
    version_id,
    schema_column_id,
    source_column,
    sheet_name,
    sample_values,
    neighbor_columns,
    decision,
    decided_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE($7::jsonb, '[]'::jsonb),
    COALESCE($8::jsonb, '[]'::jsonb),
    $9,
    $10
)
ON CONFLICT (tenant_id, pipeline_id, version_id, source_column, schema_column_id, decision)
WHERE version_id IS NOT NULL
DO UPDATE
SET
    sheet_name = EXCLUDED.sheet_name,
    sample_values = EXCLUDED.sample_values,
    neighbor_columns = EXCLUDED.neighbor_columns,
    decided_by_user_id = EXCLUDED.decided_by_user_id,
    decided_at = now(),
    updated_at = now()
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schema_column_id, source_column, sheet_name, sample_values, neighbor_columns, decision, decided_by_user_id, decided_at, shared_scope, shared_by_user_id, shared_at, created_at, updated_at
`

type UpsertDataPipelineMappingExampleParams struct {
	TenantID        int64       `json:"tenant_id"`
	PipelineID      int64       `json:"pipeline_id"`
	VersionID       pgtype.Int8 `json:"version_id"`
	SchemaColumnID  int64       `json:"schema_column_id"`
	SourceColumn    string      `json:"source_column"`
	SheetName       string      `json:"sheet_name"`
	SampleValues    []byte      `json:"sample_values"`
	NeighborColumns []byte      `json:"neighbor_columns"`
	Decision        string      `json:"decision"`
	DecidedByUserID pgtype.Int8 `json:"decided_by_user_id"`
}

func (q *Queries) UpsertDataPipelineMappingExample(ctx context.Context, arg UpsertDataPipelineMappingExampleParams) (DataPipelineMappingExample, error) {
	row := q.db.QueryRow(ctx, upsertDataPipelineMappingExample,
		arg.TenantID,
		arg.PipelineID,
		arg.VersionID,
		arg.SchemaColumnID,
		arg.SourceColumn,
		arg.SheetName,
		arg.SampleValues,
		arg.NeighborColumns,
		arg.Decision,
		arg.DecidedByUserID,
	)
	var i DataPipelineMappingExample
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.SchemaColumnID,
		&i.SourceColumn,
		&i.SheetName,
		&i.SampleValues,
		&i.NeighborColumns,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.SharedScope,
		&i.SharedByUserID,
		&i.SharedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDataPipelineMappingExampleWithoutVersion = `-- name: UpsertDataPipelineMappingExampleWithoutVersion :one
INSERT INTO data_pipeline_mapping_examples (
    tenant_id,
    pipeline_id,
    schema_column_id,
    source_column,
    sheet_name,
    sample_values,
    neighbor_columns,
    decision,
    decided_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6::jsonb, '[]'::jsonb),
    COALESCE($7::jsonb, '[]'::jsonb),
    $8,
    $9
)
ON CONFLICT (tenant_id, pipeline_id, source_column, schema_column_id, decision)
WHERE version_id IS NULL
DO UPDATE
SET
    sheet_name = EXCLUDED.sheet_name,
    sample_values = EXCLUDED.sample_values,
    neighbor_columns = EXCLUDED.neighbor_columns,
    decided_by_user_id = EXCLUDED.decided_by_user_id,
    decided_at = now(),
    updated_at = now()
RETURNING id, public_id, tenant_id, pipeline_id, version_id, schema_column_id, source_column, sheet_name, sample_values, neighbor_columns, decision, decided_by_user_id, decided_at, shared_scope, shared_by_user_id, shared_at, created_at, updated_at
`

type UpsertDataPipelineMappingExampleWithoutVersionParams struct {
	TenantID        int64       `json:"tenant_id"`
	PipelineID      int64       `json:"pipeline_id"`
	SchemaColumnID  int64       `json:"schema_column_id"`
	SourceColumn    string      `json:"source_column"`
	SheetName       string      `json:"sheet_name"`
	SampleValues    []byte      `json:"sample_values"`
	NeighborColumns []byte      `json:"neighbor_columns"`
	Decision        string      `json:"decision"`
	DecidedByUserID pgtype.Int8 `json:"decided_by_user_id"`
}

func (q *Queries) UpsertDataPipelineMappingExampleWithoutVersion(ctx context.Context, arg UpsertDataPipelineMappingExampleWithoutVersionParams) (DataPipelineMappingExample, error) {
	row := q.db.QueryRow(ctx, upsertDataPipelineMappingExampleWithoutVersion,
		arg.TenantID,
		arg.PipelineID,
		arg.SchemaColumnID,
		arg.SourceColumn,
		arg.SheetName,
		arg.SampleValues,
		arg.NeighborColumns,
		arg.Decision,
		arg.DecidedByUserID,
	)
	var i DataPipelineMappingExample
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.SchemaColumnID,
		&i.SourceColumn,
		&i.SheetName,
		&i.SampleValues,
		&i.NeighborColumns,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.SharedScope,
		&i.SharedByUserID,
		&i.SharedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDataPipelineSchemaColumn = `-- name: UpsertDataPipelineSchemaColumn :one
INSERT INTO data_pipeline_schema_columns (
    tenant_id,
    domain,
    schema_type,
    target_column,
    description,
    aliases,
    examples,
    language,
    version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6::jsonb, '[]'::jsonb),
    COALESCE($7::jsonb, '[]'::jsonb),
    $8,
    $9
)
ON CONFLICT (tenant_id, domain, schema_type, target_column, version) DO UPDATE
SET
    description = EXCLUDED.description,
    aliases = EXCLUDED.aliases,
    examples = EXCLUDED.examples,
    language = EXCLUDED.language,
    archived_at = NULL,
    updated_at = now()
RETURNING id, public_id, tenant_id, domain, schema_type, target_column, description, aliases, examples, language, version, archived_at, created_at, updated_at
`

type UpsertDataPipelineSchemaColumnParams struct {
	TenantID     int64  `json:"tenant_id"`
	Domain       string `json:"domain"`
	SchemaType   string `json:"schema_type"`
	TargetColumn string `json:"target_column"`
	Description  string `json:"description"`
	Aliases      []byte `json:"aliases"`
	Examples     []byte `json:"examples"`
	Language     string `json:"language"`
	Version      int32  `json:"version"`
}

func (q *Queries) UpsertDataPipelineSchemaColumn(ctx context.Context, arg UpsertDataPipelineSchemaColumnParams) (DataPipelineSchemaColumn, error) {
	row := q.db.QueryRow(ctx, upsertDataPipelineSchemaColumn,
		arg.TenantID,
		arg.Domain,
		arg.SchemaType,
		arg.TargetColumn,
		arg.Description,
		arg.Aliases,
		arg.Examples,
		arg.Language,
		arg.Version,
	)
	var i DataPipelineSchemaColumn
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Domain,
		&i.SchemaType,
		&i.TargetColumn,
		&i.Description,
		&i.Aliases,
		&i.Examples,
		&i.Language,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
