// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_pipeline_review_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDataPipelineReviewItemComment = `-- name: CreateDataPipelineReviewItemComment :one
INSERT INTO data_pipeline_review_item_comments (
    tenant_id,
    review_item_id,
    author_user_id,
    body
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, public_id, tenant_id, review_item_id, author_user_id, body, created_at
`

type CreateDataPipelineReviewItemCommentParams struct {
	TenantID     int64       `json:"tenant_id"`
	ReviewItemID int64       `json:"review_item_id"`
	AuthorUserID pgtype.Int8 `json:"author_user_id"`
	Body         string      `json:"body"`
}

func (q *Queries) CreateDataPipelineReviewItemComment(ctx context.Context, arg CreateDataPipelineReviewItemCommentParams) (DataPipelineReviewItemComment, error) {
	row := q.db.QueryRow(ctx, createDataPipelineReviewItemComment,
		arg.TenantID,
		arg.ReviewItemID,
		arg.AuthorUserID,
		arg.Body,
	)
	var i DataPipelineReviewItemComment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ReviewItemID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getDataPipelineReviewItemForTenant = `-- name: GetDataPipelineReviewItemForTenant :one
SELECT id, public_id, tenant_id, pipeline_id, version_id, run_id, node_id, queue, status, reason, source_snapshot, source_fingerprint, created_by_user_id, updated_by_user_id, assigned_to_user_id, decision_comment, decided_at, created_at, updated_at
FROM data_pipeline_review_items
WHERE tenant_id = $1
  AND public_id = $2
LIMIT 1
`

type GetDataPipelineReviewItemForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDataPipelineReviewItemForTenant(ctx context.Context, arg GetDataPipelineReviewItemForTenantParams) (DataPipelineReviewItem, error) {
	row := q.db.QueryRow(ctx, getDataPipelineReviewItemForTenant, arg.TenantID, arg.PublicID)
	var i DataPipelineReviewItem
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.RunID,
		&i.NodeID,
		&i.Queue,
		&i.Status,
		&i.Reason,
		&i.SourceSnapshot,
		&i.SourceFingerprint,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.AssignedToUserID,
		&i.DecisionComment,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataPipelineReviewItemComments = `-- name: ListDataPipelineReviewItemComments :many
SELECT id, public_id, tenant_id, review_item_id, author_user_id, body, created_at
FROM data_pipeline_review_item_comments
WHERE tenant_id = $1
  AND review_item_id = $2
ORDER BY created_at ASC, id ASC
`

type ListDataPipelineReviewItemCommentsParams struct {
	TenantID     int64 `json:"tenant_id"`
	ReviewItemID int64 `json:"review_item_id"`
}

func (q *Queries) ListDataPipelineReviewItemComments(ctx context.Context, arg ListDataPipelineReviewItemCommentsParams) ([]DataPipelineReviewItemComment, error) {
	rows, err := q.db.Query(ctx, listDataPipelineReviewItemComments, arg.TenantID, arg.ReviewItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineReviewItemComment
	for rows.Next() {
		var i DataPipelineReviewItemComment
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ReviewItemID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineReviewItems = `-- name: ListDataPipelineReviewItems :many
SELECT ri.id, ri.public_id, ri.tenant_id, ri.pipeline_id, ri.version_id, ri.run_id, ri.node_id, ri.queue, ri.status, ri.reason, ri.source_snapshot, ri.source_fingerprint, ri.created_by_user_id, ri.updated_by_user_id, ri.assigned_to_user_id, ri.decision_comment, ri.decided_at, ri.created_at, ri.updated_at
FROM data_pipeline_review_items ri
JOIN data_pipelines p ON p.id = ri.pipeline_id
WHERE ri.tenant_id = $1
  AND p.public_id = $2
  AND (
      $3::text IS NULL
      OR ri.status = $3::text
  )
ORDER BY ri.created_at DESC, ri.id DESC
LIMIT $4
`

type ListDataPipelineReviewItemsParams struct {
	TenantID         int64       `json:"tenant_id"`
	PipelinePublicID uuid.UUID   `json:"pipeline_public_id"`
	Status           pgtype.Text `json:"status"`
	ResultLimit      int32       `json:"result_limit"`
}

func (q *Queries) ListDataPipelineReviewItems(ctx context.Context, arg ListDataPipelineReviewItemsParams) ([]DataPipelineReviewItem, error) {
	rows, err := q.db.Query(ctx, listDataPipelineReviewItems,
		arg.TenantID,
		arg.PipelinePublicID,
		arg.Status,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataPipelineReviewItem
	for rows.Next() {
		var i DataPipelineReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineID,
			&i.VersionID,
			&i.RunID,
			&i.NodeID,
			&i.Queue,
			&i.Status,
			&i.Reason,
			&i.SourceSnapshot,
			&i.SourceFingerprint,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.AssignedToUserID,
			&i.DecisionComment,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataPipelineReviewItemsByDriveFile = `-- name: ListDataPipelineReviewItemsByDriveFile :many
SELECT
    ri.id, ri.public_id, ri.tenant_id, ri.pipeline_id, ri.version_id, ri.run_id, ri.node_id, ri.queue, ri.status, ri.reason, ri.source_snapshot, ri.source_fingerprint, ri.created_by_user_id, ri.updated_by_user_id, ri.assigned_to_user_id, ri.decision_comment, ri.decided_at, ri.created_at, ri.updated_at,
    p.public_id AS pipeline_public_id,
    p.name AS pipeline_name,
    r.public_id AS run_public_id
FROM data_pipeline_review_items ri
JOIN data_pipelines p ON p.id = ri.pipeline_id
JOIN data_pipeline_runs r ON r.id = ri.run_id
WHERE ri.tenant_id = $1
  AND ri.source_snapshot->>'file_public_id' = $2::text
  AND (
      $3::text IS NULL
      OR ri.status = $3::text
  )
ORDER BY ri.created_at DESC, ri.id DESC
LIMIT $4
`

type ListDataPipelineReviewItemsByDriveFileParams struct {
	TenantID     int64       `json:"tenant_id"`
	FilePublicID string      `json:"file_public_id"`
	Status       pgtype.Text `json:"status"`
	ResultLimit  int32       `json:"result_limit"`
}

type ListDataPipelineReviewItemsByDriveFileRow struct {
	DataPipelineReviewItem DataPipelineReviewItem `json:"data_pipeline_review_item"`
	PipelinePublicID       uuid.UUID              `json:"pipeline_public_id"`
	PipelineName           string                 `json:"pipeline_name"`
	RunPublicID            uuid.UUID              `json:"run_public_id"`
}

func (q *Queries) ListDataPipelineReviewItemsByDriveFile(ctx context.Context, arg ListDataPipelineReviewItemsByDriveFileParams) ([]ListDataPipelineReviewItemsByDriveFileRow, error) {
	rows, err := q.db.Query(ctx, listDataPipelineReviewItemsByDriveFile,
		arg.TenantID,
		arg.FilePublicID,
		arg.Status,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDataPipelineReviewItemsByDriveFileRow
	for rows.Next() {
		var i ListDataPipelineReviewItemsByDriveFileRow
		if err := rows.Scan(
			&i.DataPipelineReviewItem.ID,
			&i.DataPipelineReviewItem.PublicID,
			&i.DataPipelineReviewItem.TenantID,
			&i.DataPipelineReviewItem.PipelineID,
			&i.DataPipelineReviewItem.VersionID,
			&i.DataPipelineReviewItem.RunID,
			&i.DataPipelineReviewItem.NodeID,
			&i.DataPipelineReviewItem.Queue,
			&i.DataPipelineReviewItem.Status,
			&i.DataPipelineReviewItem.Reason,
			&i.DataPipelineReviewItem.SourceSnapshot,
			&i.DataPipelineReviewItem.SourceFingerprint,
			&i.DataPipelineReviewItem.CreatedByUserID,
			&i.DataPipelineReviewItem.UpdatedByUserID,
			&i.DataPipelineReviewItem.AssignedToUserID,
			&i.DataPipelineReviewItem.DecisionComment,
			&i.DataPipelineReviewItem.DecidedAt,
			&i.DataPipelineReviewItem.CreatedAt,
			&i.DataPipelineReviewItem.UpdatedAt,
			&i.PipelinePublicID,
			&i.PipelineName,
			&i.RunPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionDataPipelineReviewItem = `-- name: TransitionDataPipelineReviewItem :one
UPDATE data_pipeline_review_items
SET
    status = $1,
    decision_comment = $2,
    updated_by_user_id = $3,
    decided_at = CASE
        WHEN $1::text IN ('approved', 'rejected', 'needs_changes', 'closed') THEN now()
        ELSE decided_at
    END,
    updated_at = now()
WHERE tenant_id = $4
  AND public_id = $5
RETURNING id, public_id, tenant_id, pipeline_id, version_id, run_id, node_id, queue, status, reason, source_snapshot, source_fingerprint, created_by_user_id, updated_by_user_id, assigned_to_user_id, decision_comment, decided_at, created_at, updated_at
`

type TransitionDataPipelineReviewItemParams struct {
	Status          string      `json:"status"`
	DecisionComment string      `json:"decision_comment"`
	UpdatedByUserID pgtype.Int8 `json:"updated_by_user_id"`
	TenantID        int64       `json:"tenant_id"`
	PublicID        uuid.UUID   `json:"public_id"`
}

func (q *Queries) TransitionDataPipelineReviewItem(ctx context.Context, arg TransitionDataPipelineReviewItemParams) (DataPipelineReviewItem, error) {
	row := q.db.QueryRow(ctx, transitionDataPipelineReviewItem,
		arg.Status,
		arg.DecisionComment,
		arg.UpdatedByUserID,
		arg.TenantID,
		arg.PublicID,
	)
	var i DataPipelineReviewItem
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.RunID,
		&i.NodeID,
		&i.Queue,
		&i.Status,
		&i.Reason,
		&i.SourceSnapshot,
		&i.SourceFingerprint,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.AssignedToUserID,
		&i.DecisionComment,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDataPipelineReviewItem = `-- name: UpsertDataPipelineReviewItem :one
INSERT INTO data_pipeline_review_items (
    tenant_id,
    pipeline_id,
    version_id,
    run_id,
    node_id,
    queue,
    reason,
    source_snapshot,
    source_fingerprint,
    created_by_user_id,
    updated_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE($7::jsonb, '[]'::jsonb),
    COALESCE($8::jsonb, '{}'::jsonb),
    $9,
    $10,
    $11
)
ON CONFLICT (tenant_id, run_id, node_id, source_fingerprint)
DO UPDATE
SET
    queue = EXCLUDED.queue,
    reason = EXCLUDED.reason,
    source_snapshot = EXCLUDED.source_snapshot,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = now()
RETURNING id, public_id, tenant_id, pipeline_id, version_id, run_id, node_id, queue, status, reason, source_snapshot, source_fingerprint, created_by_user_id, updated_by_user_id, assigned_to_user_id, decision_comment, decided_at, created_at, updated_at
`

type UpsertDataPipelineReviewItemParams struct {
	TenantID          int64       `json:"tenant_id"`
	PipelineID        int64       `json:"pipeline_id"`
	VersionID         int64       `json:"version_id"`
	RunID             int64       `json:"run_id"`
	NodeID            string      `json:"node_id"`
	Queue             string      `json:"queue"`
	Reason            []byte      `json:"reason"`
	SourceSnapshot    []byte      `json:"source_snapshot"`
	SourceFingerprint string      `json:"source_fingerprint"`
	CreatedByUserID   pgtype.Int8 `json:"created_by_user_id"`
	UpdatedByUserID   pgtype.Int8 `json:"updated_by_user_id"`
}

func (q *Queries) UpsertDataPipelineReviewItem(ctx context.Context, arg UpsertDataPipelineReviewItemParams) (DataPipelineReviewItem, error) {
	row := q.db.QueryRow(ctx, upsertDataPipelineReviewItem,
		arg.TenantID,
		arg.PipelineID,
		arg.VersionID,
		arg.RunID,
		arg.NodeID,
		arg.Queue,
		arg.Reason,
		arg.SourceSnapshot,
		arg.SourceFingerprint,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i DataPipelineReviewItem
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineID,
		&i.VersionID,
		&i.RunID,
		&i.NodeID,
		&i.Queue,
		&i.Status,
		&i.Reason,
		&i.SourceSnapshot,
		&i.SourceFingerprint,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.AssignedToUserID,
		&i.DecisionComment,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
