// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: downstream_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOAuthUserGrant = `-- name: DeleteOAuthUserGrant :exec
DELETE FROM oauth_user_grants
WHERE user_id = $1
  AND provider = $2
  AND resource_server = $3
`

type DeleteOAuthUserGrantParams struct {
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	ResourceServer string `json:"resource_server"`
}

func (q *Queries) DeleteOAuthUserGrant(ctx context.Context, arg DeleteOAuthUserGrantParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthUserGrant, arg.UserID, arg.Provider, arg.ResourceServer)
	return err
}

const getActiveOAuthUserGrant = `-- name: GetActiveOAuthUserGrant :one
SELECT
    id,
    user_id,
    provider,
    resource_server,
    provider_subject,
    refresh_token_ciphertext,
    refresh_token_key_version,
    scope_text,
    granted_by_session_id,
    granted_at,
    last_refreshed_at,
    revoked_at,
    last_error_code,
    created_at,
    updated_at
FROM oauth_user_grants
WHERE user_id = $1
  AND provider = $2
  AND resource_server = $3
  AND revoked_at IS NULL
LIMIT 1
`

type GetActiveOAuthUserGrantParams struct {
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	ResourceServer string `json:"resource_server"`
}

func (q *Queries) GetActiveOAuthUserGrant(ctx context.Context, arg GetActiveOAuthUserGrantParams) (OauthUserGrant, error) {
	row := q.db.QueryRow(ctx, getActiveOAuthUserGrant, arg.UserID, arg.Provider, arg.ResourceServer)
	var i OauthUserGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ResourceServer,
		&i.ProviderSubject,
		&i.RefreshTokenCiphertext,
		&i.RefreshTokenKeyVersion,
		&i.ScopeText,
		&i.GrantedBySessionID,
		&i.GrantedAt,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthUserGrant = `-- name: GetOAuthUserGrant :one
SELECT
    id,
    user_id,
    provider,
    resource_server,
    provider_subject,
    refresh_token_ciphertext,
    refresh_token_key_version,
    scope_text,
    granted_by_session_id,
    granted_at,
    last_refreshed_at,
    revoked_at,
    last_error_code,
    created_at,
    updated_at
FROM oauth_user_grants
WHERE user_id = $1
  AND provider = $2
  AND resource_server = $3
LIMIT 1
`

type GetOAuthUserGrantParams struct {
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	ResourceServer string `json:"resource_server"`
}

func (q *Queries) GetOAuthUserGrant(ctx context.Context, arg GetOAuthUserGrantParams) (OauthUserGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthUserGrant, arg.UserID, arg.Provider, arg.ResourceServer)
	var i OauthUserGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ResourceServer,
		&i.ProviderSubject,
		&i.RefreshTokenCiphertext,
		&i.RefreshTokenKeyVersion,
		&i.ScopeText,
		&i.GrantedBySessionID,
		&i.GrantedAt,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthUserGrantsByUserID = `-- name: ListOAuthUserGrantsByUserID :many
SELECT
    id,
    user_id,
    provider,
    resource_server,
    provider_subject,
    refresh_token_key_version,
    scope_text,
    granted_by_session_id,
    granted_at,
    last_refreshed_at,
    revoked_at,
    last_error_code,
    created_at,
    updated_at
FROM oauth_user_grants
WHERE user_id = $1
ORDER BY resource_server, provider
`

type ListOAuthUserGrantsByUserIDRow struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	Provider               string             `json:"provider"`
	ResourceServer         string             `json:"resource_server"`
	ProviderSubject        string             `json:"provider_subject"`
	RefreshTokenKeyVersion int32              `json:"refresh_token_key_version"`
	ScopeText              string             `json:"scope_text"`
	GrantedBySessionID     string             `json:"granted_by_session_id"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	LastRefreshedAt        pgtype.Timestamptz `json:"last_refreshed_at"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	LastErrorCode          pgtype.Text        `json:"last_error_code"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOAuthUserGrantsByUserID(ctx context.Context, userID int64) ([]ListOAuthUserGrantsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOAuthUserGrantsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOAuthUserGrantsByUserIDRow
	for rows.Next() {
		var i ListOAuthUserGrantsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ResourceServer,
			&i.ProviderSubject,
			&i.RefreshTokenKeyVersion,
			&i.ScopeText,
			&i.GrantedBySessionID,
			&i.GrantedAt,
			&i.LastRefreshedAt,
			&i.RevokedAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOAuthUserGrantRevoked = `-- name: MarkOAuthUserGrantRevoked :exec
UPDATE oauth_user_grants
SET revoked_at = now(),
    last_error_code = $4,
    updated_at = now()
WHERE user_id = $1
  AND provider = $2
  AND resource_server = $3
`

type MarkOAuthUserGrantRevokedParams struct {
	UserID         int64       `json:"user_id"`
	Provider       string      `json:"provider"`
	ResourceServer string      `json:"resource_server"`
	LastErrorCode  pgtype.Text `json:"last_error_code"`
}

func (q *Queries) MarkOAuthUserGrantRevoked(ctx context.Context, arg MarkOAuthUserGrantRevokedParams) error {
	_, err := q.db.Exec(ctx, markOAuthUserGrantRevoked,
		arg.UserID,
		arg.Provider,
		arg.ResourceServer,
		arg.LastErrorCode,
	)
	return err
}

const updateOAuthUserGrantAfterRefresh = `-- name: UpdateOAuthUserGrantAfterRefresh :one
UPDATE oauth_user_grants
SET refresh_token_ciphertext = $4,
    refresh_token_key_version = $5,
    scope_text = $6,
    last_refreshed_at = now(),
    last_error_code = NULL,
    updated_at = now()
WHERE user_id = $1
  AND provider = $2
  AND resource_server = $3
  AND revoked_at IS NULL
RETURNING
    id,
    user_id,
    provider,
    resource_server,
    provider_subject,
    refresh_token_ciphertext,
    refresh_token_key_version,
    scope_text,
    granted_by_session_id,
    granted_at,
    last_refreshed_at,
    revoked_at,
    last_error_code,
    created_at,
    updated_at
`

type UpdateOAuthUserGrantAfterRefreshParams struct {
	UserID                 int64  `json:"user_id"`
	Provider               string `json:"provider"`
	ResourceServer         string `json:"resource_server"`
	RefreshTokenCiphertext []byte `json:"refresh_token_ciphertext"`
	RefreshTokenKeyVersion int32  `json:"refresh_token_key_version"`
	ScopeText              string `json:"scope_text"`
}

func (q *Queries) UpdateOAuthUserGrantAfterRefresh(ctx context.Context, arg UpdateOAuthUserGrantAfterRefreshParams) (OauthUserGrant, error) {
	row := q.db.QueryRow(ctx, updateOAuthUserGrantAfterRefresh,
		arg.UserID,
		arg.Provider,
		arg.ResourceServer,
		arg.RefreshTokenCiphertext,
		arg.RefreshTokenKeyVersion,
		arg.ScopeText,
	)
	var i OauthUserGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ResourceServer,
		&i.ProviderSubject,
		&i.RefreshTokenCiphertext,
		&i.RefreshTokenKeyVersion,
		&i.ScopeText,
		&i.GrantedBySessionID,
		&i.GrantedAt,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthUserGrant = `-- name: UpsertOAuthUserGrant :one
INSERT INTO oauth_user_grants (
    user_id,
    provider,
    resource_server,
    provider_subject,
    refresh_token_ciphertext,
    refresh_token_key_version,
    scope_text,
    granted_by_session_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (user_id, provider, resource_server) DO UPDATE
SET provider_subject = EXCLUDED.provider_subject,
    refresh_token_ciphertext = EXCLUDED.refresh_token_ciphertext,
    refresh_token_key_version = EXCLUDED.refresh_token_key_version,
    scope_text = EXCLUDED.scope_text,
    granted_by_session_id = EXCLUDED.granted_by_session_id,
    granted_at = now(),
    last_refreshed_at = NULL,
    revoked_at = NULL,
    last_error_code = NULL,
    updated_at = now()
RETURNING
    id,
    user_id,
    provider,
    resource_server,
    provider_subject,
    refresh_token_ciphertext,
    refresh_token_key_version,
    scope_text,
    granted_by_session_id,
    granted_at,
    last_refreshed_at,
    revoked_at,
    last_error_code,
    created_at,
    updated_at
`

type UpsertOAuthUserGrantParams struct {
	UserID                 int64  `json:"user_id"`
	Provider               string `json:"provider"`
	ResourceServer         string `json:"resource_server"`
	ProviderSubject        string `json:"provider_subject"`
	RefreshTokenCiphertext []byte `json:"refresh_token_ciphertext"`
	RefreshTokenKeyVersion int32  `json:"refresh_token_key_version"`
	ScopeText              string `json:"scope_text"`
	GrantedBySessionID     string `json:"granted_by_session_id"`
}

func (q *Queries) UpsertOAuthUserGrant(ctx context.Context, arg UpsertOAuthUserGrantParams) (OauthUserGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUserGrant,
		arg.UserID,
		arg.Provider,
		arg.ResourceServer,
		arg.ProviderSubject,
		arg.RefreshTokenCiphertext,
		arg.RefreshTokenKeyVersion,
		arg.ScopeText,
		arg.GrantedBySessionID,
	)
	var i OauthUserGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ResourceServer,
		&i.ProviderSubject,
		&i.RefreshTokenCiphertext,
		&i.RefreshTokenKeyVersion,
		&i.ScopeText,
		&i.GrantedBySessionID,
		&i.GrantedAt,
		&i.LastRefreshedAt,
		&i.RevokedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
