// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addDriveGroupMember = `-- name: AddDriveGroupMember :one
INSERT INTO drive_group_members (
    group_id,
    user_id,
    added_by_user_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, group_id, user_id, added_by_user_id, deleted_at, created_at, updated_at
`

type AddDriveGroupMemberParams struct {
	GroupID       int64 `json:"group_id"`
	UserID        int64 `json:"user_id"`
	AddedByUserID int64 `json:"added_by_user_id"`
}

func (q *Queries) AddDriveGroupMember(ctx context.Context, arg AddDriveGroupMemberParams) (DriveGroupMember, error) {
	row := q.db.QueryRow(ctx, addDriveGroupMember, arg.GroupID, arg.UserID, arg.AddedByUserID)
	var i DriveGroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.AddedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDriveGroup = `-- name: CreateDriveGroup :one
INSERT INTO drive_groups (
    tenant_id,
    name,
    description,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, public_id, tenant_id, name, description, created_by_user_id, deleted_at, created_at, updated_at
`

type CreateDriveGroupParams struct {
	TenantID        int64  `json:"tenant_id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	CreatedByUserID int64  `json:"created_by_user_id"`
}

func (q *Queries) CreateDriveGroup(ctx context.Context, arg CreateDriveGroupParams) (DriveGroup, error) {
	row := q.db.QueryRow(ctx, createDriveGroup,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.CreatedByUserID,
	)
	var i DriveGroup
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveGroupByIDForTenant = `-- name: GetDriveGroupByIDForTenant :one
SELECT id, public_id, tenant_id, name, description, created_by_user_id, deleted_at, created_at, updated_at
FROM drive_groups
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetDriveGroupByIDForTenantParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetDriveGroupByIDForTenant(ctx context.Context, arg GetDriveGroupByIDForTenantParams) (DriveGroup, error) {
	row := q.db.QueryRow(ctx, getDriveGroupByIDForTenant, arg.ID, arg.TenantID)
	var i DriveGroup
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveGroupByPublicIDForTenant = `-- name: GetDriveGroupByPublicIDForTenant :one
SELECT id, public_id, tenant_id, name, description, created_by_user_id, deleted_at, created_at, updated_at
FROM drive_groups
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetDriveGroupByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetDriveGroupByPublicIDForTenant(ctx context.Context, arg GetDriveGroupByPublicIDForTenantParams) (DriveGroup, error) {
	row := q.db.QueryRow(ctx, getDriveGroupByPublicIDForTenant, arg.PublicID, arg.TenantID)
	var i DriveGroup
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDriveGroupMembers = `-- name: ListDriveGroupMembers :many
SELECT id, group_id, user_id, added_by_user_id, deleted_at, created_at, updated_at
FROM drive_group_members
WHERE group_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDriveGroupMembers(ctx context.Context, groupID int64) ([]DriveGroupMember, error) {
	rows, err := q.db.Query(ctx, listDriveGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveGroupMember
	for rows.Next() {
		var i DriveGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.AddedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriveGroups = `-- name: ListDriveGroups :many
SELECT id, public_id, tenant_id, name, description, created_by_user_id, deleted_at, created_at, updated_at
FROM drive_groups
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC, id ASC
LIMIT $2
`

type ListDriveGroupsParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListDriveGroups(ctx context.Context, arg ListDriveGroupsParams) ([]DriveGroup, error) {
	rows, err := q.db.Query(ctx, listDriveGroups, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveGroup
	for rows.Next() {
		var i DriveGroup
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriveGroupsForUser = `-- name: ListDriveGroupsForUser :many
SELECT g.id, g.public_id, g.tenant_id, g.name, g.description, g.created_by_user_id, g.deleted_at, g.created_at, g.updated_at
FROM drive_groups g
JOIN drive_group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
  AND gm.deleted_at IS NULL
  AND g.tenant_id = $2
  AND g.deleted_at IS NULL
ORDER BY g.name ASC, g.id ASC
`

type ListDriveGroupsForUserParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) ListDriveGroupsForUser(ctx context.Context, arg ListDriveGroupsForUserParams) ([]DriveGroup, error) {
	rows, err := q.db.Query(ctx, listDriveGroupsForUser, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveGroup
	for rows.Next() {
		var i DriveGroup
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDriveGroupMember = `-- name: RemoveDriveGroupMember :one
UPDATE drive_group_members
SET
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE group_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, group_id, user_id, added_by_user_id, deleted_at, created_at, updated_at
`

type RemoveDriveGroupMemberParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RemoveDriveGroupMember(ctx context.Context, arg RemoveDriveGroupMemberParams) (DriveGroupMember, error) {
	row := q.db.QueryRow(ctx, removeDriveGroupMember, arg.GroupID, arg.UserID)
	var i DriveGroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.AddedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteDriveGroup = `-- name: SoftDeleteDriveGroup :one
UPDATE drive_groups
SET
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, name, description, created_by_user_id, deleted_at, created_at, updated_at
`

type SoftDeleteDriveGroupParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) SoftDeleteDriveGroup(ctx context.Context, arg SoftDeleteDriveGroupParams) (DriveGroup, error) {
	row := q.db.QueryRow(ctx, softDeleteDriveGroup, arg.ID, arg.TenantID)
	var i DriveGroup
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDriveGroup = `-- name: UpdateDriveGroup :one
UPDATE drive_groups
SET
    name = $1,
    description = $2,
    updated_at = now()
WHERE id = $3
  AND tenant_id = $4
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, name, description, created_by_user_id, deleted_at, created_at, updated_at
`

type UpdateDriveGroupParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
	TenantID    int64  `json:"tenant_id"`
}

func (q *Queries) UpdateDriveGroup(ctx context.Context, arg UpdateDriveGroupParams) (DriveGroup, error) {
	row := q.db.QueryRow(ctx, updateDriveGroup,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.TenantID,
	)
	var i DriveGroup
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
