// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: drive_workspaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDriveWorkspaces = `-- name: CountDriveWorkspaces :one
SELECT count(*)::bigint
FROM drive_workspaces
WHERE tenant_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountDriveWorkspaces(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDriveWorkspaces, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDriveWorkspace = `-- name: CreateDriveWorkspace :one
INSERT INTO drive_workspaces (
    tenant_id,
    name,
    created_by_user_id,
    storage_quota_bytes,
    policy_override
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, '{}'::jsonb)
)
RETURNING id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
`

type CreateDriveWorkspaceParams struct {
	TenantID          int64       `json:"tenant_id"`
	Name              string      `json:"name"`
	CreatedByUserID   pgtype.Int8 `json:"created_by_user_id"`
	StorageQuotaBytes pgtype.Int8 `json:"storage_quota_bytes"`
	PolicyOverride    interface{} `json:"policy_override"`
}

func (q *Queries) CreateDriveWorkspace(ctx context.Context, arg CreateDriveWorkspaceParams) (DriveWorkspace, error) {
	row := q.db.QueryRow(ctx, createDriveWorkspace,
		arg.TenantID,
		arg.Name,
		arg.CreatedByUserID,
		arg.StorageQuotaBytes,
		arg.PolicyOverride,
	)
	var i DriveWorkspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.RootFolderID,
		&i.CreatedByUserID,
		&i.StorageQuotaBytes,
		&i.PolicyOverride,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultDriveWorkspace = `-- name: GetDefaultDriveWorkspace :one
SELECT id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
FROM drive_workspaces
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetDefaultDriveWorkspace(ctx context.Context, tenantID int64) (DriveWorkspace, error) {
	row := q.db.QueryRow(ctx, getDefaultDriveWorkspace, tenantID)
	var i DriveWorkspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.RootFolderID,
		&i.CreatedByUserID,
		&i.StorageQuotaBytes,
		&i.PolicyOverride,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveWorkspaceByIDForTenant = `-- name: GetDriveWorkspaceByIDForTenant :one
SELECT id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
FROM drive_workspaces
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetDriveWorkspaceByIDForTenantParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetDriveWorkspaceByIDForTenant(ctx context.Context, arg GetDriveWorkspaceByIDForTenantParams) (DriveWorkspace, error) {
	row := q.db.QueryRow(ctx, getDriveWorkspaceByIDForTenant, arg.ID, arg.TenantID)
	var i DriveWorkspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.RootFolderID,
		&i.CreatedByUserID,
		&i.StorageQuotaBytes,
		&i.PolicyOverride,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveWorkspaceByPublicIDForTenant = `-- name: GetDriveWorkspaceByPublicIDForTenant :one
SELECT id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
FROM drive_workspaces
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetDriveWorkspaceByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetDriveWorkspaceByPublicIDForTenant(ctx context.Context, arg GetDriveWorkspaceByPublicIDForTenantParams) (DriveWorkspace, error) {
	row := q.db.QueryRow(ctx, getDriveWorkspaceByPublicIDForTenant, arg.PublicID, arg.TenantID)
	var i DriveWorkspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.RootFolderID,
		&i.CreatedByUserID,
		&i.StorageQuotaBytes,
		&i.PolicyOverride,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDriveWorkspaces = `-- name: ListDriveWorkspaces :many
SELECT id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
FROM drive_workspaces
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC, id ASC
LIMIT $2
`

type ListDriveWorkspacesParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListDriveWorkspaces(ctx context.Context, arg ListDriveWorkspacesParams) ([]DriveWorkspace, error) {
	rows, err := q.db.Query(ctx, listDriveWorkspaces, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveWorkspace
	for rows.Next() {
		var i DriveWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Name,
			&i.RootFolderID,
			&i.CreatedByUserID,
			&i.StorageQuotaBytes,
			&i.PolicyOverride,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDriveWorkspace = `-- name: SoftDeleteDriveWorkspace :one
UPDATE drive_workspaces
SET
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
`

type SoftDeleteDriveWorkspaceParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) SoftDeleteDriveWorkspace(ctx context.Context, arg SoftDeleteDriveWorkspaceParams) (DriveWorkspace, error) {
	row := q.db.QueryRow(ctx, softDeleteDriveWorkspace, arg.PublicID, arg.TenantID)
	var i DriveWorkspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.RootFolderID,
		&i.CreatedByUserID,
		&i.StorageQuotaBytes,
		&i.PolicyOverride,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDriveWorkspace = `-- name: UpdateDriveWorkspace :one
UPDATE drive_workspaces
SET
    name = $1,
    storage_quota_bytes = $2,
    policy_override = COALESCE($3, policy_override),
    updated_at = now()
WHERE public_id = $4
  AND tenant_id = $5
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, name, root_folder_id, created_by_user_id, storage_quota_bytes, policy_override, deleted_at, created_at, updated_at
`

type UpdateDriveWorkspaceParams struct {
	Name              string      `json:"name"`
	StorageQuotaBytes pgtype.Int8 `json:"storage_quota_bytes"`
	PolicyOverride    []byte      `json:"policy_override"`
	PublicID          uuid.UUID   `json:"public_id"`
	TenantID          int64       `json:"tenant_id"`
}

func (q *Queries) UpdateDriveWorkspace(ctx context.Context, arg UpdateDriveWorkspaceParams) (DriveWorkspace, error) {
	row := q.db.QueryRow(ctx, updateDriveWorkspace,
		arg.Name,
		arg.StorageQuotaBytes,
		arg.PolicyOverride,
		arg.PublicID,
		arg.TenantID,
	)
	var i DriveWorkspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Name,
		&i.RootFolderID,
		&i.CreatedByUserID,
		&i.StorageQuotaBytes,
		&i.PolicyOverride,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
