// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: drive_search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriveIndexJob = `-- name: CreateDriveIndexJob :one
INSERT INTO drive_index_jobs (
    tenant_id,
    file_object_id,
    reason,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, public_id, tenant_id, file_object_id, reason, status, attempts, last_error, created_at, updated_at
`

type CreateDriveIndexJobParams struct {
	TenantID     int64  `json:"tenant_id"`
	FileObjectID int64  `json:"file_object_id"`
	Reason       string `json:"reason"`
	Status       string `json:"status"`
}

func (q *Queries) CreateDriveIndexJob(ctx context.Context, arg CreateDriveIndexJobParams) (DriveIndexJob, error) {
	row := q.db.QueryRow(ctx, createDriveIndexJob,
		arg.TenantID,
		arg.FileObjectID,
		arg.Reason,
		arg.Status,
	)
	var i DriveIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.FileObjectID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDriveSearchDocument = `-- name: DeleteDriveSearchDocument :exec
DELETE FROM drive_search_documents
WHERE tenant_id = $1
  AND file_object_id = $2
`

type DeleteDriveSearchDocumentParams struct {
	TenantID     int64 `json:"tenant_id"`
	FileObjectID int64 `json:"file_object_id"`
}

func (q *Queries) DeleteDriveSearchDocument(ctx context.Context, arg DeleteDriveSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDriveSearchDocument, arg.TenantID, arg.FileObjectID)
	return err
}

const listDriveSearchResults = `-- name: ListDriveSearchResults :many
SELECT
    f.id, f.public_id, f.tenant_id, f.uploaded_by_user_id, f.purpose, f.attached_to_type, f.attached_to_id, f.original_filename, f.content_type, f.byte_size, f.sha256_hex, f.storage_driver, f.storage_key, f.status, f.created_at, f.updated_at, f.deleted_at, f.purged_at, f.purge_attempts, f.purge_locked_at, f.purge_locked_by, f.last_purge_error, f.drive_folder_id, f.locked_at, f.locked_by_user_id, f.lock_reason, f.inheritance_enabled, f.deleted_by_user_id, f.deleted_parent_folder_id, f.retention_until, f.legal_hold_at, f.legal_hold_by_user_id, f.legal_hold_reason, f.purge_block_reason, f.workspace_id, f.storage_bucket, f.storage_version, f.content_sha256, f.etag, f.scan_status, f.scan_reason, f.scan_engine, f.scanned_at, f.dlp_blocked, f.upload_state, f.office_mime_family, f.office_coauthoring_enabled, f.office_last_revision, f.encryption_mode, f.e2ee_file_key_public_id, f.storage_gateway_id,
    COALESCE(d.snippet, '') AS search_snippet,
    d.indexed_at AS search_indexed_at
FROM file_objects f
LEFT JOIN drive_search_documents d ON d.file_object_id = f.id
WHERE f.tenant_id = $1
  AND f.purpose = 'drive'
  AND f.deleted_at IS NULL
  AND f.scan_status IN ('clean', 'skipped')
  AND f.dlp_blocked = false
  AND (
      $2::text IS NULL
      OR f.content_type = $2::text
  )
  AND (
      $3::text IS NULL
      OR f.original_filename ILIKE '%' || $3::text || '%'
      OR d.search_vector @@ plainto_tsquery('simple', $3::text)
  )
ORDER BY f.updated_at DESC, f.id DESC
LIMIT $4
`

type ListDriveSearchResultsParams struct {
	TenantID    int64       `json:"tenant_id"`
	ContentType pgtype.Text `json:"content_type"`
	Query       pgtype.Text `json:"query"`
	LimitCount  int32       `json:"limit_count"`
}

type ListDriveSearchResultsRow struct {
	ID                       int64              `json:"id"`
	PublicID                 uuid.UUID          `json:"public_id"`
	TenantID                 int64              `json:"tenant_id"`
	UploadedByUserID         pgtype.Int8        `json:"uploaded_by_user_id"`
	Purpose                  string             `json:"purpose"`
	AttachedToType           pgtype.Text        `json:"attached_to_type"`
	AttachedToID             pgtype.Text        `json:"attached_to_id"`
	OriginalFilename         string             `json:"original_filename"`
	ContentType              string             `json:"content_type"`
	ByteSize                 int64              `json:"byte_size"`
	Sha256Hex                string             `json:"sha256_hex"`
	StorageDriver            string             `json:"storage_driver"`
	StorageKey               string             `json:"storage_key"`
	Status                   string             `json:"status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	PurgedAt                 pgtype.Timestamptz `json:"purged_at"`
	PurgeAttempts            int32              `json:"purge_attempts"`
	PurgeLockedAt            pgtype.Timestamptz `json:"purge_locked_at"`
	PurgeLockedBy            pgtype.Text        `json:"purge_locked_by"`
	LastPurgeError           pgtype.Text        `json:"last_purge_error"`
	DriveFolderID            pgtype.Int8        `json:"drive_folder_id"`
	LockedAt                 pgtype.Timestamptz `json:"locked_at"`
	LockedByUserID           pgtype.Int8        `json:"locked_by_user_id"`
	LockReason               pgtype.Text        `json:"lock_reason"`
	InheritanceEnabled       bool               `json:"inheritance_enabled"`
	DeletedByUserID          pgtype.Int8        `json:"deleted_by_user_id"`
	DeletedParentFolderID    pgtype.Int8        `json:"deleted_parent_folder_id"`
	RetentionUntil           pgtype.Timestamptz `json:"retention_until"`
	LegalHoldAt              pgtype.Timestamptz `json:"legal_hold_at"`
	LegalHoldByUserID        pgtype.Int8        `json:"legal_hold_by_user_id"`
	LegalHoldReason          pgtype.Text        `json:"legal_hold_reason"`
	PurgeBlockReason         pgtype.Text        `json:"purge_block_reason"`
	WorkspaceID              pgtype.Int8        `json:"workspace_id"`
	StorageBucket            pgtype.Text        `json:"storage_bucket"`
	StorageVersion           pgtype.Text        `json:"storage_version"`
	ContentSha256            pgtype.Text        `json:"content_sha256"`
	Etag                     pgtype.Text        `json:"etag"`
	ScanStatus               string             `json:"scan_status"`
	ScanReason               pgtype.Text        `json:"scan_reason"`
	ScanEngine               pgtype.Text        `json:"scan_engine"`
	ScannedAt                pgtype.Timestamptz `json:"scanned_at"`
	DlpBlocked               bool               `json:"dlp_blocked"`
	UploadState              string             `json:"upload_state"`
	OfficeMimeFamily         pgtype.Text        `json:"office_mime_family"`
	OfficeCoauthoringEnabled bool               `json:"office_coauthoring_enabled"`
	OfficeLastRevision       pgtype.Text        `json:"office_last_revision"`
	EncryptionMode           string             `json:"encryption_mode"`
	E2eeFileKeyPublicID      pgtype.UUID        `json:"e2ee_file_key_public_id"`
	StorageGatewayID         pgtype.Int8        `json:"storage_gateway_id"`
	SearchSnippet            string             `json:"search_snippet"`
	SearchIndexedAt          pgtype.Timestamptz `json:"search_indexed_at"`
}

func (q *Queries) ListDriveSearchResults(ctx context.Context, arg ListDriveSearchResultsParams) ([]ListDriveSearchResultsRow, error) {
	rows, err := q.db.Query(ctx, listDriveSearchResults,
		arg.TenantID,
		arg.ContentType,
		arg.Query,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriveSearchResultsRow
	for rows.Next() {
		var i ListDriveSearchResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
			&i.DriveFolderID,
			&i.LockedAt,
			&i.LockedByUserID,
			&i.LockReason,
			&i.InheritanceEnabled,
			&i.DeletedByUserID,
			&i.DeletedParentFolderID,
			&i.RetentionUntil,
			&i.LegalHoldAt,
			&i.LegalHoldByUserID,
			&i.LegalHoldReason,
			&i.PurgeBlockReason,
			&i.WorkspaceID,
			&i.StorageBucket,
			&i.StorageVersion,
			&i.ContentSha256,
			&i.Etag,
			&i.ScanStatus,
			&i.ScanReason,
			&i.ScanEngine,
			&i.ScannedAt,
			&i.DlpBlocked,
			&i.UploadState,
			&i.OfficeMimeFamily,
			&i.OfficeCoauthoringEnabled,
			&i.OfficeLastRevision,
			&i.EncryptionMode,
			&i.E2eeFileKeyPublicID,
			&i.StorageGatewayID,
			&i.SearchSnippet,
			&i.SearchIndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDriveIndexedFileCandidates = `-- name: SearchDriveIndexedFileCandidates :many
SELECT f.id, f.public_id, f.tenant_id, f.uploaded_by_user_id, f.purpose, f.attached_to_type, f.attached_to_id, f.original_filename, f.content_type, f.byte_size, f.sha256_hex, f.storage_driver, f.storage_key, f.status, f.created_at, f.updated_at, f.deleted_at, f.purged_at, f.purge_attempts, f.purge_locked_at, f.purge_locked_by, f.last_purge_error, f.drive_folder_id, f.locked_at, f.locked_by_user_id, f.lock_reason, f.inheritance_enabled, f.deleted_by_user_id, f.deleted_parent_folder_id, f.retention_until, f.legal_hold_at, f.legal_hold_by_user_id, f.legal_hold_reason, f.purge_block_reason, f.workspace_id, f.storage_bucket, f.storage_version, f.content_sha256, f.etag, f.scan_status, f.scan_reason, f.scan_engine, f.scanned_at, f.dlp_blocked, f.upload_state, f.office_mime_family, f.office_coauthoring_enabled, f.office_last_revision, f.encryption_mode, f.e2ee_file_key_public_id, f.storage_gateway_id
FROM file_objects f
LEFT JOIN drive_search_documents d ON d.file_object_id = f.id
WHERE f.tenant_id = $1
  AND f.purpose = 'drive'
  AND f.deleted_at IS NULL
  AND f.scan_status IN ('clean', 'skipped')
  AND f.dlp_blocked = false
  AND (
      $2::text IS NULL
      OR f.content_type = $2::text
  )
  AND (
      $3::timestamptz IS NULL
      OR f.updated_at >= $3::timestamptz
  )
  AND (
      $4::timestamptz IS NULL
      OR f.updated_at <= $4::timestamptz
  )
  AND (
      $5::text IS NULL
      OR f.original_filename ILIKE '%' || $5::text || '%'
      OR d.search_vector @@ plainto_tsquery('simple', $5::text)
  )
ORDER BY
    CASE
        WHEN $5::text IS NULL THEN 0
        WHEN f.original_filename ILIKE '%' || $5::text || '%' THEN 0
        ELSE 1
    END ASC,
    f.updated_at DESC,
    f.id DESC
LIMIT $6
`

type SearchDriveIndexedFileCandidatesParams struct {
	TenantID      int64              `json:"tenant_id"`
	ContentType   pgtype.Text        `json:"content_type"`
	UpdatedAfter  pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
	Query         pgtype.Text        `json:"query"`
	LimitCount    int32              `json:"limit_count"`
}

func (q *Queries) SearchDriveIndexedFileCandidates(ctx context.Context, arg SearchDriveIndexedFileCandidatesParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, searchDriveIndexedFileCandidates,
		arg.TenantID,
		arg.ContentType,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.Query,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
			&i.DriveFolderID,
			&i.LockedAt,
			&i.LockedByUserID,
			&i.LockReason,
			&i.InheritanceEnabled,
			&i.DeletedByUserID,
			&i.DeletedParentFolderID,
			&i.RetentionUntil,
			&i.LegalHoldAt,
			&i.LegalHoldByUserID,
			&i.LegalHoldReason,
			&i.PurgeBlockReason,
			&i.WorkspaceID,
			&i.StorageBucket,
			&i.StorageVersion,
			&i.ContentSha256,
			&i.Etag,
			&i.ScanStatus,
			&i.ScanReason,
			&i.ScanEngine,
			&i.ScannedAt,
			&i.DlpBlocked,
			&i.UploadState,
			&i.OfficeMimeFamily,
			&i.OfficeCoauthoringEnabled,
			&i.OfficeLastRevision,
			&i.EncryptionMode,
			&i.E2eeFileKeyPublicID,
			&i.StorageGatewayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDriveSearchDocument = `-- name: UpsertDriveSearchDocument :one
INSERT INTO drive_search_documents (
    tenant_id,
    workspace_id,
    file_object_id,
    title,
    content_type,
    extracted_text,
    snippet,
    content_sha256,
    object_updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (file_object_id) DO UPDATE
SET
    workspace_id = EXCLUDED.workspace_id,
    title = EXCLUDED.title,
    content_type = EXCLUDED.content_type,
    extracted_text = EXCLUDED.extracted_text,
    snippet = EXCLUDED.snippet,
    content_sha256 = EXCLUDED.content_sha256,
    object_updated_at = EXCLUDED.object_updated_at,
    indexed_at = now(),
    updated_at = now()
RETURNING id, public_id, tenant_id, workspace_id, file_object_id, title, content_type, extracted_text, snippet, content_sha256, object_updated_at, indexed_at, search_vector, created_at, updated_at
`

type UpsertDriveSearchDocumentParams struct {
	TenantID        int64              `json:"tenant_id"`
	WorkspaceID     pgtype.Int8        `json:"workspace_id"`
	FileObjectID    int64              `json:"file_object_id"`
	Title           string             `json:"title"`
	ContentType     string             `json:"content_type"`
	ExtractedText   string             `json:"extracted_text"`
	Snippet         string             `json:"snippet"`
	ContentSha256   pgtype.Text        `json:"content_sha256"`
	ObjectUpdatedAt pgtype.Timestamptz `json:"object_updated_at"`
}

func (q *Queries) UpsertDriveSearchDocument(ctx context.Context, arg UpsertDriveSearchDocumentParams) (DriveSearchDocument, error) {
	row := q.db.QueryRow(ctx, upsertDriveSearchDocument,
		arg.TenantID,
		arg.WorkspaceID,
		arg.FileObjectID,
		arg.Title,
		arg.ContentType,
		arg.ExtractedText,
		arg.Snippet,
		arg.ContentSha256,
		arg.ObjectUpdatedAt,
	)
	var i DriveSearchDocument
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.FileObjectID,
		&i.Title,
		&i.ContentType,
		&i.ExtractedText,
		&i.Snippet,
		&i.ContentSha256,
		&i.ObjectUpdatedAt,
		&i.IndexedAt,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
