// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: drive_files.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriveFileObject = `-- name: CreateDriveFileObject :one
INSERT INTO file_objects (
    tenant_id,
    uploaded_by_user_id,
    purpose,
    attached_to_type,
    attached_to_id,
    workspace_id,
    drive_folder_id,
    original_filename,
    content_type,
    byte_size,
    sha256_hex,
    content_sha256,
    storage_driver,
    storage_key,
    scan_status,
    inheritance_enabled
) VALUES (
    $1,
    $2,
    'drive',
    NULL,
    NULL,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NULLIF($8, ''),
    $9,
    $10,
    $11,
    $12
)
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type CreateDriveFileObjectParams struct {
	TenantID           int64       `json:"tenant_id"`
	UploadedByUserID   pgtype.Int8 `json:"uploaded_by_user_id"`
	WorkspaceID        pgtype.Int8 `json:"workspace_id"`
	DriveFolderID      pgtype.Int8 `json:"drive_folder_id"`
	OriginalFilename   string      `json:"original_filename"`
	ContentType        string      `json:"content_type"`
	ByteSize           int64       `json:"byte_size"`
	Sha256Hex          string      `json:"sha256_hex"`
	StorageDriver      string      `json:"storage_driver"`
	StorageKey         string      `json:"storage_key"`
	ScanStatus         string      `json:"scan_status"`
	InheritanceEnabled bool        `json:"inheritance_enabled"`
}

func (q *Queries) CreateDriveFileObject(ctx context.Context, arg CreateDriveFileObjectParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, createDriveFileObject,
		arg.TenantID,
		arg.UploadedByUserID,
		arg.WorkspaceID,
		arg.DriveFolderID,
		arg.OriginalFilename,
		arg.ContentType,
		arg.ByteSize,
		arg.Sha256Hex,
		arg.StorageDriver,
		arg.StorageKey,
		arg.ScanStatus,
		arg.InheritanceEnabled,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const getDriveFileByIDForTenant = `-- name: GetDriveFileByIDForTenant :one
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
FROM file_objects
WHERE id = $1
  AND tenant_id = $2
  AND purpose = 'drive'
  AND deleted_at IS NULL
`

type GetDriveFileByIDForTenantParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetDriveFileByIDForTenant(ctx context.Context, arg GetDriveFileByIDForTenantParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, getDriveFileByIDForTenant, arg.ID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const getDriveFileByPublicIDForTenant = `-- name: GetDriveFileByPublicIDForTenant :one
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
FROM file_objects
WHERE public_id = $1
  AND tenant_id = $2
  AND purpose = 'drive'
  AND deleted_at IS NULL
`

type GetDriveFileByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetDriveFileByPublicIDForTenant(ctx context.Context, arg GetDriveFileByPublicIDForTenantParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, getDriveFileByPublicIDForTenant, arg.PublicID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const listDriveChildFiles = `-- name: ListDriveChildFiles :many
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
FROM file_objects
WHERE tenant_id = $1
  AND drive_folder_id IS NOT DISTINCT FROM $2::bigint
  AND (
      $3::bigint IS NULL
      OR workspace_id = $3::bigint
  )
  AND purpose = 'drive'
  AND deleted_at IS NULL
ORDER BY original_filename ASC, id ASC
LIMIT $4
`

type ListDriveChildFilesParams struct {
	TenantID      int64       `json:"tenant_id"`
	DriveFolderID pgtype.Int8 `json:"drive_folder_id"`
	WorkspaceID   pgtype.Int8 `json:"workspace_id"`
	LimitCount    int32       `json:"limit_count"`
}

func (q *Queries) ListDriveChildFiles(ctx context.Context, arg ListDriveChildFilesParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, listDriveChildFiles,
		arg.TenantID,
		arg.DriveFolderID,
		arg.WorkspaceID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
			&i.DriveFolderID,
			&i.LockedAt,
			&i.LockedByUserID,
			&i.LockReason,
			&i.InheritanceEnabled,
			&i.DeletedByUserID,
			&i.DeletedParentFolderID,
			&i.RetentionUntil,
			&i.LegalHoldAt,
			&i.LegalHoldByUserID,
			&i.LegalHoldReason,
			&i.PurgeBlockReason,
			&i.WorkspaceID,
			&i.StorageBucket,
			&i.StorageVersion,
			&i.ContentSha256,
			&i.Etag,
			&i.ScanStatus,
			&i.ScanReason,
			&i.ScanEngine,
			&i.ScannedAt,
			&i.DlpBlocked,
			&i.UploadState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDriveFile = `-- name: LockDriveFile :one
UPDATE file_objects
SET
    locked_at = now(),
    locked_by_user_id = $1,
    lock_reason = $2,
    updated_at = now()
WHERE id = $3
  AND tenant_id = $4
  AND purpose = 'drive'
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type LockDriveFileParams struct {
	LockedByUserID pgtype.Int8 `json:"locked_by_user_id"`
	LockReason     pgtype.Text `json:"lock_reason"`
	ID             int64       `json:"id"`
	TenantID       int64       `json:"tenant_id"`
}

func (q *Queries) LockDriveFile(ctx context.Context, arg LockDriveFileParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, lockDriveFile,
		arg.LockedByUserID,
		arg.LockReason,
		arg.ID,
		arg.TenantID,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const moveDriveFile = `-- name: MoveDriveFile :one
UPDATE file_objects
SET
    drive_folder_id = $1,
    workspace_id = $2,
    inheritance_enabled = $3,
    updated_at = now()
WHERE id = $4
  AND tenant_id = $5
  AND purpose = 'drive'
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type MoveDriveFileParams struct {
	DriveFolderID      pgtype.Int8 `json:"drive_folder_id"`
	WorkspaceID        pgtype.Int8 `json:"workspace_id"`
	InheritanceEnabled bool        `json:"inheritance_enabled"`
	ID                 int64       `json:"id"`
	TenantID           int64       `json:"tenant_id"`
}

func (q *Queries) MoveDriveFile(ctx context.Context, arg MoveDriveFileParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, moveDriveFile,
		arg.DriveFolderID,
		arg.WorkspaceID,
		arg.InheritanceEnabled,
		arg.ID,
		arg.TenantID,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const renameDriveFile = `-- name: RenameDriveFile :one
UPDATE file_objects
SET
    original_filename = $1,
    updated_at = now()
WHERE id = $2
  AND tenant_id = $3
  AND purpose = 'drive'
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type RenameDriveFileParams struct {
	OriginalFilename string `json:"original_filename"`
	ID               int64  `json:"id"`
	TenantID         int64  `json:"tenant_id"`
}

func (q *Queries) RenameDriveFile(ctx context.Context, arg RenameDriveFileParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, renameDriveFile, arg.OriginalFilename, arg.ID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const searchDriveFileCandidates = `-- name: SearchDriveFileCandidates :many
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
FROM file_objects
WHERE tenant_id = $1
  AND purpose = 'drive'
  AND deleted_at IS NULL
  AND (
      $2::text IS NULL
      OR original_filename ILIKE '%' || $2::text || '%'
  )
  AND (
      $3::text IS NULL
      OR content_type = $3::text
  )
  AND (
      $4::timestamptz IS NULL
      OR updated_at >= $4::timestamptz
  )
  AND (
      $5::timestamptz IS NULL
      OR updated_at <= $5::timestamptz
  )
ORDER BY updated_at DESC, id DESC
LIMIT $6
`

type SearchDriveFileCandidatesParams struct {
	TenantID      int64              `json:"tenant_id"`
	Query         pgtype.Text        `json:"query"`
	ContentType   pgtype.Text        `json:"content_type"`
	UpdatedAfter  pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
	LimitCount    int32              `json:"limit_count"`
}

func (q *Queries) SearchDriveFileCandidates(ctx context.Context, arg SearchDriveFileCandidatesParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, searchDriveFileCandidates,
		arg.TenantID,
		arg.Query,
		arg.ContentType,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
			&i.DriveFolderID,
			&i.LockedAt,
			&i.LockedByUserID,
			&i.LockReason,
			&i.InheritanceEnabled,
			&i.DeletedByUserID,
			&i.DeletedParentFolderID,
			&i.RetentionUntil,
			&i.LegalHoldAt,
			&i.LegalHoldByUserID,
			&i.LegalHoldReason,
			&i.PurgeBlockReason,
			&i.WorkspaceID,
			&i.StorageBucket,
			&i.StorageVersion,
			&i.ContentSha256,
			&i.Etag,
			&i.ScanStatus,
			&i.ScanReason,
			&i.ScanEngine,
			&i.ScannedAt,
			&i.DlpBlocked,
			&i.UploadState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDriveFile = `-- name: SoftDeleteDriveFile :one
UPDATE file_objects
SET
    status = 'deleted',
    deleted_at = COALESCE(deleted_at, now()),
    deleted_by_user_id = $1,
    updated_at = now()
WHERE id = $2
  AND tenant_id = $3
  AND purpose = 'drive'
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type SoftDeleteDriveFileParams struct {
	DeletedByUserID pgtype.Int8 `json:"deleted_by_user_id"`
	ID              int64       `json:"id"`
	TenantID        int64       `json:"tenant_id"`
}

func (q *Queries) SoftDeleteDriveFile(ctx context.Context, arg SoftDeleteDriveFileParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, softDeleteDriveFile, arg.DeletedByUserID, arg.ID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const unlockDriveFile = `-- name: UnlockDriveFile :one
UPDATE file_objects
SET
    locked_at = NULL,
    locked_by_user_id = NULL,
    lock_reason = NULL,
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND purpose = 'drive'
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type UnlockDriveFileParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) UnlockDriveFile(ctx context.Context, arg UnlockDriveFileParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, unlockDriveFile, arg.ID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}

const updateDriveFileObjectMetadata = `-- name: UpdateDriveFileObjectMetadata :one
UPDATE file_objects
SET
    content_type = $1,
    byte_size = $2,
    sha256_hex = $3,
    storage_driver = $4,
    storage_key = $5,
    content_sha256 = NULLIF($3, ''),
    scan_status = $6,
    scan_reason = NULL,
    scan_engine = NULL,
    scanned_at = NULL,
    dlp_blocked = false,
    updated_at = now()
WHERE id = $7
  AND tenant_id = $8
  AND purpose = 'drive'
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state
`

type UpdateDriveFileObjectMetadataParams struct {
	ContentType   string `json:"content_type"`
	ByteSize      int64  `json:"byte_size"`
	Sha256Hex     string `json:"sha256_hex"`
	StorageDriver string `json:"storage_driver"`
	StorageKey    string `json:"storage_key"`
	ScanStatus    string `json:"scan_status"`
	ID            int64  `json:"id"`
	TenantID      int64  `json:"tenant_id"`
}

func (q *Queries) UpdateDriveFileObjectMetadata(ctx context.Context, arg UpdateDriveFileObjectMetadataParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, updateDriveFileObjectMetadata,
		arg.ContentType,
		arg.ByteSize,
		arg.Sha256Hex,
		arg.StorageDriver,
		arg.StorageKey,
		arg.ScanStatus,
		arg.ID,
		arg.TenantID,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
		&i.DriveFolderID,
		&i.LockedAt,
		&i.LockedByUserID,
		&i.LockReason,
		&i.InheritanceEnabled,
		&i.DeletedByUserID,
		&i.DeletedParentFolderID,
		&i.RetentionUntil,
		&i.LegalHoldAt,
		&i.LegalHoldByUserID,
		&i.LegalHoldReason,
		&i.PurgeBlockReason,
		&i.WorkspaceID,
		&i.StorageBucket,
		&i.StorageVersion,
		&i.ContentSha256,
		&i.Etag,
		&i.ScanStatus,
		&i.ScanReason,
		&i.ScanEngine,
		&i.ScannedAt,
		&i.DlpBlocked,
		&i.UploadState,
	)
	return i, err
}
