// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive_shares.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriveResourceShare = `-- name: CreateDriveResourceShare :one
INSERT INTO drive_resource_shares (
    tenant_id,
    resource_type,
    resource_id,
    subject_type,
    subject_id,
    role,
    status,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, public_id, tenant_id, resource_type, resource_id, subject_type, subject_id, role, status, created_by_user_id, revoked_by_user_id, revoked_at, created_at, updated_at
`

type CreateDriveResourceShareParams struct {
	TenantID        int64  `json:"tenant_id"`
	ResourceType    string `json:"resource_type"`
	ResourceID      int64  `json:"resource_id"`
	SubjectType     string `json:"subject_type"`
	SubjectID       int64  `json:"subject_id"`
	Role            string `json:"role"`
	Status          string `json:"status"`
	CreatedByUserID int64  `json:"created_by_user_id"`
}

func (q *Queries) CreateDriveResourceShare(ctx context.Context, arg CreateDriveResourceShareParams) (DriveResourceShare, error) {
	row := q.db.QueryRow(ctx, createDriveResourceShare,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Role,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i DriveResourceShare
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveResourceShareByPublicIDForTenant = `-- name: GetDriveResourceShareByPublicIDForTenant :one
SELECT id, public_id, tenant_id, resource_type, resource_id, subject_type, subject_id, role, status, created_by_user_id, revoked_by_user_id, revoked_at, created_at, updated_at
FROM drive_resource_shares
WHERE public_id = $1
  AND tenant_id = $2
  AND status <> 'revoked'
`

type GetDriveResourceShareByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetDriveResourceShareByPublicIDForTenant(ctx context.Context, arg GetDriveResourceShareByPublicIDForTenantParams) (DriveResourceShare, error) {
	row := q.db.QueryRow(ctx, getDriveResourceShareByPublicIDForTenant, arg.PublicID, arg.TenantID)
	var i DriveResourceShare
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDriveResourceSharesBySubject = `-- name: ListActiveDriveResourceSharesBySubject :many
SELECT id, public_id, tenant_id, resource_type, resource_id, subject_type, subject_id, role, status, created_by_user_id, revoked_by_user_id, revoked_at, created_at, updated_at
FROM drive_resource_shares
WHERE tenant_id = $1
  AND subject_type = $2
  AND subject_id = $3
  AND status = 'active'
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListActiveDriveResourceSharesBySubjectParams struct {
	TenantID    int64  `json:"tenant_id"`
	SubjectType string `json:"subject_type"`
	SubjectID   int64  `json:"subject_id"`
	LimitCount  int32  `json:"limit_count"`
}

func (q *Queries) ListActiveDriveResourceSharesBySubject(ctx context.Context, arg ListActiveDriveResourceSharesBySubjectParams) ([]DriveResourceShare, error) {
	rows, err := q.db.Query(ctx, listActiveDriveResourceSharesBySubject,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveResourceShare
	for rows.Next() {
		var i DriveResourceShare
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ResourceType,
			&i.ResourceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Role,
			&i.Status,
			&i.CreatedByUserID,
			&i.RevokedByUserID,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriveResourceSharesByResource = `-- name: ListDriveResourceSharesByResource :many
SELECT id, public_id, tenant_id, resource_type, resource_id, subject_type, subject_id, role, status, created_by_user_id, revoked_by_user_id, revoked_at, created_at, updated_at
FROM drive_resource_shares
WHERE tenant_id = $1
  AND resource_type = $2
  AND resource_id = $3
  AND status IN ('active', 'pending_sync')
ORDER BY created_at ASC, id ASC
`

type ListDriveResourceSharesByResourceParams struct {
	TenantID     int64  `json:"tenant_id"`
	ResourceType string `json:"resource_type"`
	ResourceID   int64  `json:"resource_id"`
}

func (q *Queries) ListDriveResourceSharesByResource(ctx context.Context, arg ListDriveResourceSharesByResourceParams) ([]DriveResourceShare, error) {
	rows, err := q.db.Query(ctx, listDriveResourceSharesByResource, arg.TenantID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveResourceShare
	for rows.Next() {
		var i DriveResourceShare
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ResourceType,
			&i.ResourceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Role,
			&i.Status,
			&i.CreatedByUserID,
			&i.RevokedByUserID,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDriveResourceSharePendingSync = `-- name: MarkDriveResourceSharePendingSync :one
UPDATE drive_resource_shares
SET
    status = 'pending_sync',
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND status <> 'revoked'
RETURNING id, public_id, tenant_id, resource_type, resource_id, subject_type, subject_id, role, status, created_by_user_id, revoked_by_user_id, revoked_at, created_at, updated_at
`

type MarkDriveResourceSharePendingSyncParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) MarkDriveResourceSharePendingSync(ctx context.Context, arg MarkDriveResourceSharePendingSyncParams) (DriveResourceShare, error) {
	row := q.db.QueryRow(ctx, markDriveResourceSharePendingSync, arg.ID, arg.TenantID)
	var i DriveResourceShare
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeDriveResourceShare = `-- name: RevokeDriveResourceShare :one
UPDATE drive_resource_shares
SET
    status = 'revoked',
    revoked_by_user_id = $1,
    revoked_at = now(),
    updated_at = now()
WHERE public_id = $2
  AND tenant_id = $3
  AND status <> 'revoked'
RETURNING id, public_id, tenant_id, resource_type, resource_id, subject_type, subject_id, role, status, created_by_user_id, revoked_by_user_id, revoked_at, created_at, updated_at
`

type RevokeDriveResourceShareParams struct {
	RevokedByUserID pgtype.Int8 `json:"revoked_by_user_id"`
	PublicID        uuid.UUID   `json:"public_id"`
	TenantID        int64       `json:"tenant_id"`
}

func (q *Queries) RevokeDriveResourceShare(ctx context.Context, arg RevokeDriveResourceShareParams) (DriveResourceShare, error) {
	row := q.db.QueryRow(ctx, revokeDriveResourceShare, arg.RevokedByUserID, arg.PublicID, arg.TenantID)
	var i DriveResourceShare
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
