// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive_share_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriveShareLink = `-- name: CreateDriveShareLink :one
INSERT INTO drive_share_links (
    tenant_id,
    resource_type,
    resource_id,
    token_hash,
    role,
    can_download,
    expires_at,
    status,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
`

type CreateDriveShareLinkParams struct {
	TenantID        int64              `json:"tenant_id"`
	ResourceType    string             `json:"resource_type"`
	ResourceID      int64              `json:"resource_id"`
	TokenHash       string             `json:"token_hash"`
	Role            string             `json:"role"`
	CanDownload     bool               `json:"can_download"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Status          string             `json:"status"`
	CreatedByUserID int64              `json:"created_by_user_id"`
}

func (q *Queries) CreateDriveShareLink(ctx context.Context, arg CreateDriveShareLinkParams) (DriveShareLink, error) {
	row := q.db.QueryRow(ctx, createDriveShareLink,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.TokenHash,
		arg.Role,
		arg.CanDownload,
		arg.ExpiresAt,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i DriveShareLink
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.TokenHash,
		&i.Role,
		&i.CanDownload,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedByUserID,
		&i.DisabledByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordRequired,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const disableDriveShareLink = `-- name: DisableDriveShareLink :one
UPDATE drive_share_links
SET
    status = 'disabled',
    disabled_by_user_id = $1,
    disabled_at = now(),
    updated_at = now()
WHERE public_id = $2
  AND tenant_id = $3
  AND status <> 'disabled'
RETURNING id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
`

type DisableDriveShareLinkParams struct {
	DisabledByUserID pgtype.Int8 `json:"disabled_by_user_id"`
	PublicID         uuid.UUID   `json:"public_id"`
	TenantID         int64       `json:"tenant_id"`
}

func (q *Queries) DisableDriveShareLink(ctx context.Context, arg DisableDriveShareLinkParams) (DriveShareLink, error) {
	row := q.db.QueryRow(ctx, disableDriveShareLink, arg.DisabledByUserID, arg.PublicID, arg.TenantID)
	var i DriveShareLink
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.TokenHash,
		&i.Role,
		&i.CanDownload,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedByUserID,
		&i.DisabledByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordRequired,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const getDriveShareLinkByPublicIDForTenant = `-- name: GetDriveShareLinkByPublicIDForTenant :one
SELECT id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
FROM drive_share_links
WHERE public_id = $1
  AND tenant_id = $2
`

type GetDriveShareLinkByPublicIDForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetDriveShareLinkByPublicIDForTenant(ctx context.Context, arg GetDriveShareLinkByPublicIDForTenantParams) (DriveShareLink, error) {
	row := q.db.QueryRow(ctx, getDriveShareLinkByPublicIDForTenant, arg.PublicID, arg.TenantID)
	var i DriveShareLink
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.TokenHash,
		&i.Role,
		&i.CanDownload,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedByUserID,
		&i.DisabledByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordRequired,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const listDriveShareLinksByResource = `-- name: ListDriveShareLinksByResource :many
SELECT id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
FROM drive_share_links
WHERE tenant_id = $1
  AND resource_type = $2
  AND resource_id = $3
  AND status IN ('active', 'pending_sync')
ORDER BY created_at DESC, id DESC
`

type ListDriveShareLinksByResourceParams struct {
	TenantID     int64  `json:"tenant_id"`
	ResourceType string `json:"resource_type"`
	ResourceID   int64  `json:"resource_id"`
}

func (q *Queries) ListDriveShareLinksByResource(ctx context.Context, arg ListDriveShareLinksByResourceParams) ([]DriveShareLink, error) {
	rows, err := q.db.Query(ctx, listDriveShareLinksByResource, arg.TenantID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveShareLink
	for rows.Next() {
		var i DriveShareLink
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ResourceType,
			&i.ResourceID,
			&i.TokenHash,
			&i.Role,
			&i.CanDownload,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedByUserID,
			&i.DisabledByUserID,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.PasswordRequired,
			&i.PasswordUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupActiveDriveShareLinkByTokenHash = `-- name: LookupActiveDriveShareLinkByTokenHash :one
SELECT id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
FROM drive_share_links
WHERE token_hash = $1
  AND status = 'active'
  AND expires_at > now()
`

func (q *Queries) LookupActiveDriveShareLinkByTokenHash(ctx context.Context, tokenHash string) (DriveShareLink, error) {
	row := q.db.QueryRow(ctx, lookupActiveDriveShareLinkByTokenHash, tokenHash)
	var i DriveShareLink
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.TokenHash,
		&i.Role,
		&i.CanDownload,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedByUserID,
		&i.DisabledByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordRequired,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const markDriveShareLinkPendingSync = `-- name: MarkDriveShareLinkPendingSync :one
UPDATE drive_share_links
SET
    status = 'pending_sync',
    updated_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND status <> 'disabled'
RETURNING id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
`

type MarkDriveShareLinkPendingSyncParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) MarkDriveShareLinkPendingSync(ctx context.Context, arg MarkDriveShareLinkPendingSyncParams) (DriveShareLink, error) {
	row := q.db.QueryRow(ctx, markDriveShareLinkPendingSync, arg.ID, arg.TenantID)
	var i DriveShareLink
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.TokenHash,
		&i.Role,
		&i.CanDownload,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedByUserID,
		&i.DisabledByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordRequired,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const updateDriveShareLink = `-- name: UpdateDriveShareLink :one
UPDATE drive_share_links
SET
    can_download = $1,
    expires_at = $2,
    updated_at = now()
WHERE public_id = $3
  AND tenant_id = $4
  AND status <> 'disabled'
RETURNING id, public_id, tenant_id, resource_type, resource_id, token_hash, role, can_download, expires_at, status, created_by_user_id, disabled_by_user_id, disabled_at, created_at, updated_at, password_hash, password_required, password_updated_at
`

type UpdateDriveShareLinkParams struct {
	CanDownload bool               `json:"can_download"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	PublicID    uuid.UUID          `json:"public_id"`
	TenantID    int64              `json:"tenant_id"`
}

func (q *Queries) UpdateDriveShareLink(ctx context.Context, arg UpdateDriveShareLinkParams) (DriveShareLink, error) {
	row := q.db.QueryRow(ctx, updateDriveShareLink,
		arg.CanDownload,
		arg.ExpiresAt,
		arg.PublicID,
		arg.TenantID,
	)
	var i DriveShareLink
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.TokenHash,
		&i.Role,
		&i.CanDownload,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedByUserID,
		&i.DisabledByUserID,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordRequired,
		&i.PasswordUpdatedAt,
	)
	return i, err
}
