// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: file_objects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDeletedLocalFileObjectsForPurge = `-- name: ClaimDeletedLocalFileObjectsForPurge :many
UPDATE file_objects
SET
    purge_locked_at = now(),
    purge_locked_by = $1::text,
    purge_attempts = purge_attempts + 1,
    updated_at = now()
WHERE id IN (
    SELECT id
    FROM file_objects
    WHERE storage_driver = 'local'
      AND status = 'deleted'
      AND deleted_at IS NOT NULL
      AND deleted_at < $2::timestamptz
      AND purged_at IS NULL
      AND (
          purge_locked_at IS NULL
          OR purge_locked_at < now() - $3::interval
      )
    ORDER BY deleted_at, id
    LIMIT $4::int
    FOR UPDATE SKIP LOCKED
)
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
`

type ClaimDeletedLocalFileObjectsForPurgeParams struct {
	WorkerID    string             `json:"worker_id"`
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
	LockTimeout pgtype.Interval    `json:"lock_timeout"`
	BatchSize   int32              `json:"batch_size"`
}

func (q *Queries) ClaimDeletedLocalFileObjectsForPurge(ctx context.Context, arg ClaimDeletedLocalFileObjectsForPurgeParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, claimDeletedLocalFileObjectsForPurge,
		arg.WorkerID,
		arg.Cutoff,
		arg.LockTimeout,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFileObject = `-- name: CreateFileObject :one
INSERT INTO file_objects (
    tenant_id,
    uploaded_by_user_id,
    purpose,
    attached_to_type,
    attached_to_id,
    original_filename,
    content_type,
    byte_size,
    sha256_hex,
    storage_driver,
    storage_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
`

type CreateFileObjectParams struct {
	TenantID         int64       `json:"tenant_id"`
	UploadedByUserID pgtype.Int8 `json:"uploaded_by_user_id"`
	Purpose          string      `json:"purpose"`
	AttachedToType   pgtype.Text `json:"attached_to_type"`
	AttachedToID     pgtype.Text `json:"attached_to_id"`
	OriginalFilename string      `json:"original_filename"`
	ContentType      string      `json:"content_type"`
	ByteSize         int64       `json:"byte_size"`
	Sha256Hex        string      `json:"sha256_hex"`
	StorageDriver    string      `json:"storage_driver"`
	StorageKey       string      `json:"storage_key"`
}

func (q *Queries) CreateFileObject(ctx context.Context, arg CreateFileObjectParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, createFileObject,
		arg.TenantID,
		arg.UploadedByUserID,
		arg.Purpose,
		arg.AttachedToType,
		arg.AttachedToID,
		arg.OriginalFilename,
		arg.ContentType,
		arg.ByteSize,
		arg.Sha256Hex,
		arg.StorageDriver,
		arg.StorageKey,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
	)
	return i, err
}

const getFileObjectByIDForTenant = `-- name: GetFileObjectByIDForTenant :one
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
FROM file_objects
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetFileObjectByIDForTenantParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetFileObjectByIDForTenant(ctx context.Context, arg GetFileObjectByIDForTenantParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, getFileObjectByIDForTenant, arg.ID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
	)
	return i, err
}

const getFileObjectForTenant = `-- name: GetFileObjectForTenant :one
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
FROM file_objects
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetFileObjectForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetFileObjectForTenant(ctx context.Context, arg GetFileObjectForTenantParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, getFileObjectForTenant, arg.PublicID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
	)
	return i, err
}

const listActiveFileObjectsForTenant = `-- name: ListActiveFileObjectsForTenant :many
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
FROM file_objects
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListActiveFileObjectsForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListActiveFileObjectsForTenant(ctx context.Context, arg ListActiveFileObjectsForTenantParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, listActiveFileObjectsForTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileObjectsForAttachment = `-- name: ListFileObjectsForAttachment :many
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
FROM file_objects
WHERE tenant_id = $1
  AND attached_to_type = $2
  AND attached_to_id = $3
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListFileObjectsForAttachmentParams struct {
	TenantID       int64       `json:"tenant_id"`
	AttachedToType pgtype.Text `json:"attached_to_type"`
	AttachedToID   pgtype.Text `json:"attached_to_id"`
}

func (q *Queries) ListFileObjectsForAttachment(ctx context.Context, arg ListFileObjectsForAttachmentParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, listFileObjectsForAttachment, arg.TenantID, arg.AttachedToType, arg.AttachedToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFileObjectBodyPurged = `-- name: MarkFileObjectBodyPurged :one
UPDATE file_objects
SET
    purged_at = now(),
    purge_locked_at = NULL,
    purge_locked_by = NULL,
    last_purge_error = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'deleted'
  AND deleted_at IS NOT NULL
  AND purged_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
`

func (q *Queries) MarkFileObjectBodyPurged(ctx context.Context, id int64) (FileObject, error) {
	row := q.db.QueryRow(ctx, markFileObjectBodyPurged, id)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
	)
	return i, err
}

const markFileObjectPurgeFailed = `-- name: MarkFileObjectPurgeFailed :one
UPDATE file_objects
SET
    purge_locked_at = NULL,
    purge_locked_by = NULL,
    last_purge_error = left($1::text, 1000),
    updated_at = now()
WHERE id = $2
  AND purged_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
`

type MarkFileObjectPurgeFailedParams struct {
	LastError string `json:"last_error"`
	ID        int64  `json:"id"`
}

func (q *Queries) MarkFileObjectPurgeFailed(ctx context.Context, arg MarkFileObjectPurgeFailedParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, markFileObjectPurgeFailed, arg.LastError, arg.ID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
	)
	return i, err
}

const softDeleteFileObjectForTenant = `-- name: SoftDeleteFileObjectForTenant :one
UPDATE file_objects
SET
    status = 'deleted',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
RETURNING id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error
`

type SoftDeleteFileObjectForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) SoftDeleteFileObjectForTenant(ctx context.Context, arg SoftDeleteFileObjectForTenantParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, softDeleteFileObjectForTenant, arg.PublicID, arg.TenantID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.UploadedByUserID,
		&i.Purpose,
		&i.AttachedToType,
		&i.AttachedToID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.ByteSize,
		&i.Sha256Hex,
		&i.StorageDriver,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PurgedAt,
		&i.PurgeAttempts,
		&i.PurgeLockedAt,
		&i.PurgeLockedBy,
		&i.LastPurgeError,
	)
	return i, err
}
