// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET
    status = 'completed',
    response_status = $2,
    response_summary = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, actor_user_id, scope, idempotency_key_hash, method, path, request_hash, status, response_status, response_summary, expires_at, created_at, updated_at, completed_at
`

type CompleteIdempotencyKeyParams struct {
	ID              int64       `json:"id"`
	ResponseStatus  pgtype.Int4 `json:"response_status"`
	ResponseSummary []byte      `json:"response_summary"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey, arg.ID, arg.ResponseStatus, arg.ResponseSummary)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ActorUserID,
		&i.Scope,
		&i.IdempotencyKeyHash,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    tenant_id,
    actor_user_id,
    scope,
    idempotency_key_hash,
    method,
    path,
    request_hash,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, public_id, tenant_id, actor_user_id, scope, idempotency_key_hash, method, path, request_hash, status, response_status, response_summary, expires_at, created_at, updated_at, completed_at
`

type CreateIdempotencyKeyParams struct {
	TenantID           pgtype.Int8        `json:"tenant_id"`
	ActorUserID        pgtype.Int8        `json:"actor_user_id"`
	Scope              string             `json:"scope"`
	IdempotencyKeyHash string             `json:"idempotency_key_hash"`
	Method             string             `json:"method"`
	Path               string             `json:"path"`
	RequestHash        string             `json:"request_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.TenantID,
		arg.ActorUserID,
		arg.Scope,
		arg.IdempotencyKeyHash,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ActorUserID,
		&i.Scope,
		&i.IdempotencyKeyHash,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failIdempotencyKey = `-- name: FailIdempotencyKey :one
UPDATE idempotency_keys
SET
    status = 'failed',
    response_status = $2,
    response_summary = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, actor_user_id, scope, idempotency_key_hash, method, path, request_hash, status, response_status, response_summary, expires_at, created_at, updated_at, completed_at
`

type FailIdempotencyKeyParams struct {
	ID              int64       `json:"id"`
	ResponseStatus  pgtype.Int4 `json:"response_status"`
	ResponseSummary []byte      `json:"response_summary"`
}

func (q *Queries) FailIdempotencyKey(ctx context.Context, arg FailIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, failIdempotencyKey, arg.ID, arg.ResponseStatus, arg.ResponseSummary)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ActorUserID,
		&i.Scope,
		&i.IdempotencyKeyHash,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIdempotencyKeyForScope = `-- name: GetIdempotencyKeyForScope :one
SELECT id, public_id, tenant_id, actor_user_id, scope, idempotency_key_hash, method, path, request_hash, status, response_status, response_summary, expires_at, created_at, updated_at, completed_at
FROM idempotency_keys
WHERE scope = $1
  AND idempotency_key_hash = $2
  AND expires_at > now()
`

type GetIdempotencyKeyForScopeParams struct {
	Scope              string `json:"scope"`
	IdempotencyKeyHash string `json:"idempotency_key_hash"`
}

func (q *Queries) GetIdempotencyKeyForScope(ctx context.Context, arg GetIdempotencyKeyForScopeParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyForScope, arg.Scope, arg.IdempotencyKeyHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ActorUserID,
		&i.Scope,
		&i.IdempotencyKeyHash,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
