// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserIdentity = `-- name: CreateUserIdentity :exec
INSERT INTO user_identities (
    user_id,
    provider,
    subject,
    email,
    email_verified
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateUserIdentityParams struct {
	UserID        int64  `json:"user_id"`
	Provider      string `json:"provider"`
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error {
	_, err := q.db.Exec(ctx, createUserIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
	)
	return err
}

const getUserByProviderSubject = `-- name: GetUserByProviderSubject :one
SELECT
    u.id,
    u.public_id,
    u.email,
    u.display_name
FROM user_identities ui
JOIN users u ON u.id = ui.user_id
WHERE ui.provider = $1
  AND ui.subject = $2
LIMIT 1
`

type GetUserByProviderSubjectParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

type GetUserByProviderSubjectRow struct {
	ID          int64     `json:"id"`
	PublicID    uuid.UUID `json:"public_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) GetUserByProviderSubject(ctx context.Context, arg GetUserByProviderSubjectParams) (GetUserByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, getUserByProviderSubject, arg.Provider, arg.Subject)
	var i GetUserByProviderSubjectRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const getUserIdentityByUserIDProvider = `-- name: GetUserIdentityByUserIDProvider :one
SELECT
    id,
    user_id,
    provider,
    subject,
    email,
    email_verified,
    created_at,
    updated_at
FROM user_identities
WHERE user_id = $1
  AND provider = $2
LIMIT 1
`

type GetUserIdentityByUserIDProviderParams struct {
	UserID   int64  `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetUserIdentityByUserIDProvider(ctx context.Context, arg GetUserIdentityByUserIDProviderParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByUserIDProvider, arg.UserID, arg.Provider)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserIdentityProfile = `-- name: UpdateUserIdentityProfile :exec
UPDATE user_identities
SET email = $3,
    email_verified = $4,
    updated_at = now()
WHERE provider = $1
  AND subject = $2
`

type UpdateUserIdentityProfileParams struct {
	Provider      string `json:"provider"`
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
}

func (q *Queries) UpdateUserIdentityProfile(ctx context.Context, arg UpdateUserIdentityProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserIdentityProfile,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
	)
	return err
}
