// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: local_search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeLocalSearchIndexJob = `-- name: CompleteLocalSearchIndexJob :one
UPDATE local_search_index_jobs
SET
    status = $1,
    indexed_count = $2,
    skipped_count = $3,
    failed_count = $4,
    last_error = NULL,
    completed_at = now(),
    updated_at = now()
WHERE id = $5
  AND tenant_id = $6
RETURNING id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
`

type CompleteLocalSearchIndexJobParams struct {
	Status       string `json:"status"`
	IndexedCount int32  `json:"indexed_count"`
	SkippedCount int32  `json:"skipped_count"`
	FailedCount  int32  `json:"failed_count"`
	ID           int64  `json:"id"`
	TenantID     int64  `json:"tenant_id"`
}

func (q *Queries) CompleteLocalSearchIndexJob(ctx context.Context, arg CompleteLocalSearchIndexJobParams) (LocalSearchIndexJob, error) {
	row := q.db.QueryRow(ctx, completeLocalSearchIndexJob,
		arg.Status,
		arg.IndexedCount,
		arg.SkippedCount,
		arg.FailedCount,
		arg.ID,
		arg.TenantID,
	)
	var i LocalSearchIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.OutboxEventID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.IndexedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.LastError,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalSearchIndexJob = `-- name: CreateLocalSearchIndexJob :one
INSERT INTO local_search_index_jobs (
    tenant_id,
    resource_kind,
    resource_id,
    resource_public_id,
    reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
`

type CreateLocalSearchIndexJobParams struct {
	TenantID         int64       `json:"tenant_id"`
	ResourceKind     pgtype.Text `json:"resource_kind"`
	ResourceID       pgtype.Int8 `json:"resource_id"`
	ResourcePublicID pgtype.UUID `json:"resource_public_id"`
	Reason           string      `json:"reason"`
}

func (q *Queries) CreateLocalSearchIndexJob(ctx context.Context, arg CreateLocalSearchIndexJobParams) (LocalSearchIndexJob, error) {
	row := q.db.QueryRow(ctx, createLocalSearchIndexJob,
		arg.TenantID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ResourcePublicID,
		arg.Reason,
	)
	var i LocalSearchIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.OutboxEventID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.IndexedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.LastError,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocalSearchDocumentForResource = `-- name: DeleteLocalSearchDocumentForResource :exec
DELETE FROM local_search_documents
WHERE tenant_id = $1
  AND resource_kind = $2
  AND resource_id = $3
`

type DeleteLocalSearchDocumentForResourceParams struct {
	TenantID     int64  `json:"tenant_id"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   int64  `json:"resource_id"`
}

func (q *Queries) DeleteLocalSearchDocumentForResource(ctx context.Context, arg DeleteLocalSearchDocumentForResourceParams) error {
	_, err := q.db.Exec(ctx, deleteLocalSearchDocumentForResource, arg.TenantID, arg.ResourceKind, arg.ResourceID)
	return err
}

const deleteLocalSearchDocumentsForFile = `-- name: DeleteLocalSearchDocumentsForFile :exec
DELETE FROM local_search_documents
WHERE tenant_id = $1
  AND file_object_id = $2
`

type DeleteLocalSearchDocumentsForFileParams struct {
	TenantID     int64       `json:"tenant_id"`
	FileObjectID pgtype.Int8 `json:"file_object_id"`
}

func (q *Queries) DeleteLocalSearchDocumentsForFile(ctx context.Context, arg DeleteLocalSearchDocumentsForFileParams) error {
	_, err := q.db.Exec(ctx, deleteLocalSearchDocumentsForFile, arg.TenantID, arg.FileObjectID)
	return err
}

const failLocalSearchIndexJob = `-- name: FailLocalSearchIndexJob :one
UPDATE local_search_index_jobs
SET
    status = 'failed',
    failed_count = GREATEST(failed_count, 1),
    last_error = left($1, 1000),
    completed_at = now(),
    updated_at = now()
WHERE id = $2
  AND tenant_id = $3
RETURNING id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
`

type FailLocalSearchIndexJobParams struct {
	LastError string `json:"last_error"`
	ID        int64  `json:"id"`
	TenantID  int64  `json:"tenant_id"`
}

func (q *Queries) FailLocalSearchIndexJob(ctx context.Context, arg FailLocalSearchIndexJobParams) (LocalSearchIndexJob, error) {
	row := q.db.QueryRow(ctx, failLocalSearchIndexJob, arg.LastError, arg.ID, arg.TenantID)
	var i LocalSearchIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.OutboxEventID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.IndexedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.LastError,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriveProductExtractionItemByIDForTenant = `-- name: GetDriveProductExtractionItemByIDForTenant :one
SELECT id, public_id, tenant_id, ocr_run_id, file_object_id, item_type, name, brand, manufacturer, model, sku, jan_code, category, description, price, promotion, availability, source_text, evidence, attributes, confidence, created_at
FROM drive_product_extraction_items
WHERE tenant_id = $1
  AND id = $2
LIMIT 1
`

type GetDriveProductExtractionItemByIDForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetDriveProductExtractionItemByIDForTenant(ctx context.Context, arg GetDriveProductExtractionItemByIDForTenantParams) (DriveProductExtractionItem, error) {
	row := q.db.QueryRow(ctx, getDriveProductExtractionItemByIDForTenant, arg.TenantID, arg.ID)
	var i DriveProductExtractionItem
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.OcrRunID,
		&i.FileObjectID,
		&i.ItemType,
		&i.Name,
		&i.Brand,
		&i.Manufacturer,
		&i.Model,
		&i.Sku,
		&i.JanCode,
		&i.Category,
		&i.Description,
		&i.Price,
		&i.Promotion,
		&i.Availability,
		&i.SourceText,
		&i.Evidence,
		&i.Attributes,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalSearchIndexJobByIDForTenant = `-- name: GetLocalSearchIndexJobByIDForTenant :one
SELECT id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
FROM local_search_index_jobs
WHERE tenant_id = $1
  AND id = $2
LIMIT 1
`

type GetLocalSearchIndexJobByIDForTenantParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetLocalSearchIndexJobByIDForTenant(ctx context.Context, arg GetLocalSearchIndexJobByIDForTenantParams) (LocalSearchIndexJob, error) {
	row := q.db.QueryRow(ctx, getLocalSearchIndexJobByIDForTenant, arg.TenantID, arg.ID)
	var i LocalSearchIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.OutboxEventID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.IndexedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.LastError,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkLocalSearchIndexJobOutboxEvent = `-- name: LinkLocalSearchIndexJobOutboxEvent :one
UPDATE local_search_index_jobs
SET
    outbox_event_id = $1,
    updated_at = now()
WHERE id = $2
  AND tenant_id = $3
RETURNING id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
`

type LinkLocalSearchIndexJobOutboxEventParams struct {
	OutboxEventID pgtype.Int8 `json:"outbox_event_id"`
	ID            int64       `json:"id"`
	TenantID      int64       `json:"tenant_id"`
}

func (q *Queries) LinkLocalSearchIndexJobOutboxEvent(ctx context.Context, arg LinkLocalSearchIndexJobOutboxEventParams) (LocalSearchIndexJob, error) {
	row := q.db.QueryRow(ctx, linkLocalSearchIndexJobOutboxEvent, arg.OutboxEventID, arg.ID, arg.TenantID)
	var i LocalSearchIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.OutboxEventID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.IndexedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.LastError,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocalSearchIndexJobs = `-- name: ListLocalSearchIndexJobs :many
SELECT id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
FROM local_search_index_jobs
WHERE tenant_id = $1
  AND (
      $2::text IS NULL
      OR status = $2::text
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListLocalSearchIndexJobsParams struct {
	TenantID   int64       `json:"tenant_id"`
	Status     pgtype.Text `json:"status"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListLocalSearchIndexJobs(ctx context.Context, arg ListLocalSearchIndexJobsParams) ([]LocalSearchIndexJob, error) {
	rows, err := q.db.Query(ctx, listLocalSearchIndexJobs, arg.TenantID, arg.Status, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalSearchIndexJob
	for rows.Next() {
		var i LocalSearchIndexJob
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourcePublicID,
			&i.OutboxEventID,
			&i.Reason,
			&i.Status,
			&i.Attempts,
			&i.IndexedCount,
			&i.SkippedCount,
			&i.FailedCount,
			&i.LastError,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSearchMatchesForFile = `-- name: ListLocalSearchMatchesForFile :many
SELECT
    d.resource_kind,
    d.resource_public_id::text AS resource_public_id,
    COALESCE(m.public_id::text, '') AS medallion_asset_public_id,
    COALESCE(m.layer, '') AS layer,
    d.snippet,
    d.indexed_at
FROM local_search_documents d
LEFT JOIN medallion_assets m ON m.id = d.medallion_asset_id
WHERE d.tenant_id = $1
  AND d.file_object_id = $2
  AND (
      $3::text IS NULL
      OR d.title ILIKE '%' || $3::text || '%'
      OR d.body_text ILIKE '%' || $3::text || '%'
      OR d.search_vector @@ websearch_to_tsquery('simple', $3::text)
  )
ORDER BY
    CASE
        WHEN $3::text IS NULL THEN 0
        ELSE ts_rank_cd(d.search_vector, websearch_to_tsquery('simple', $3::text))
    END DESC,
    d.indexed_at DESC,
    d.id DESC
LIMIT $4
`

type ListLocalSearchMatchesForFileParams struct {
	TenantID     int64       `json:"tenant_id"`
	FileObjectID pgtype.Int8 `json:"file_object_id"`
	Query        pgtype.Text `json:"query"`
	LimitCount   int32       `json:"limit_count"`
}

type ListLocalSearchMatchesForFileRow struct {
	ResourceKind           string             `json:"resource_kind"`
	ResourcePublicID       string             `json:"resource_public_id"`
	MedallionAssetPublicID interface{}        `json:"medallion_asset_public_id"`
	Layer                  string             `json:"layer"`
	Snippet                string             `json:"snippet"`
	IndexedAt              pgtype.Timestamptz `json:"indexed_at"`
}

func (q *Queries) ListLocalSearchMatchesForFile(ctx context.Context, arg ListLocalSearchMatchesForFileParams) ([]ListLocalSearchMatchesForFileRow, error) {
	rows, err := q.db.Query(ctx, listLocalSearchMatchesForFile,
		arg.TenantID,
		arg.FileObjectID,
		arg.Query,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocalSearchMatchesForFileRow
	for rows.Next() {
		var i ListLocalSearchMatchesForFileRow
		if err := rows.Scan(
			&i.ResourceKind,
			&i.ResourcePublicID,
			&i.MedallionAssetPublicID,
			&i.Layer,
			&i.Snippet,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSearchRebuildDriveFiles = `-- name: ListLocalSearchRebuildDriveFiles :many
SELECT id, public_id, tenant_id, uploaded_by_user_id, purpose, attached_to_type, attached_to_id, original_filename, content_type, byte_size, sha256_hex, storage_driver, storage_key, status, created_at, updated_at, deleted_at, purged_at, purge_attempts, purge_locked_at, purge_locked_by, last_purge_error, drive_folder_id, locked_at, locked_by_user_id, lock_reason, inheritance_enabled, deleted_by_user_id, deleted_parent_folder_id, retention_until, legal_hold_at, legal_hold_by_user_id, legal_hold_reason, purge_block_reason, workspace_id, storage_bucket, storage_version, content_sha256, etag, scan_status, scan_reason, scan_engine, scanned_at, dlp_blocked, upload_state, office_mime_family, office_coauthoring_enabled, office_last_revision, encryption_mode, e2ee_file_key_public_id, storage_gateway_id, description
FROM file_objects
WHERE tenant_id = $1
  AND purpose = 'drive'
ORDER BY id
LIMIT $2
`

type ListLocalSearchRebuildDriveFilesParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListLocalSearchRebuildDriveFiles(ctx context.Context, arg ListLocalSearchRebuildDriveFilesParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, listLocalSearchRebuildDriveFiles, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
			&i.DriveFolderID,
			&i.LockedAt,
			&i.LockedByUserID,
			&i.LockReason,
			&i.InheritanceEnabled,
			&i.DeletedByUserID,
			&i.DeletedParentFolderID,
			&i.RetentionUntil,
			&i.LegalHoldAt,
			&i.LegalHoldByUserID,
			&i.LegalHoldReason,
			&i.PurgeBlockReason,
			&i.WorkspaceID,
			&i.StorageBucket,
			&i.StorageVersion,
			&i.ContentSha256,
			&i.Etag,
			&i.ScanStatus,
			&i.ScanReason,
			&i.ScanEngine,
			&i.ScannedAt,
			&i.DlpBlocked,
			&i.UploadState,
			&i.OfficeMimeFamily,
			&i.OfficeCoauthoringEnabled,
			&i.OfficeLastRevision,
			&i.EncryptionMode,
			&i.E2eeFileKeyPublicID,
			&i.StorageGatewayID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSearchRebuildGoldPublications = `-- name: ListLocalSearchRebuildGoldPublications :many
SELECT id, public_id, tenant_id, source_work_table_id, created_by_user_id, updated_by_user_id, published_by_user_id, unpublished_by_user_id, archived_by_user_id, last_publish_run_id, display_name, description, gold_database, gold_table, status, row_count, total_bytes, schema_summary, refresh_policy, created_at, updated_at, published_at, unpublished_at, archived_at
FROM dataset_gold_publications
WHERE tenant_id = $1
ORDER BY id
LIMIT $2
`

type ListLocalSearchRebuildGoldPublicationsParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListLocalSearchRebuildGoldPublications(ctx context.Context, arg ListLocalSearchRebuildGoldPublicationsParams) ([]DatasetGoldPublication, error) {
	rows, err := q.db.Query(ctx, listLocalSearchRebuildGoldPublications, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatasetGoldPublication
	for rows.Next() {
		var i DatasetGoldPublication
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.SourceWorkTableID,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.PublishedByUserID,
			&i.UnpublishedByUserID,
			&i.ArchivedByUserID,
			&i.LastPublishRunID,
			&i.DisplayName,
			&i.Description,
			&i.GoldDatabase,
			&i.GoldTable,
			&i.Status,
			&i.RowCount,
			&i.TotalBytes,
			&i.SchemaSummary,
			&i.RefreshPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.UnpublishedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSearchRebuildOCRRuns = `-- name: ListLocalSearchRebuildOCRRuns :many
SELECT id, public_id, tenant_id, file_object_id, file_revision, content_sha256, engine, languages, structured_extractor, status, reason, page_count, processed_page_count, average_confidence, extracted_text, error_code, error_message, requested_by_user_id, outbox_event_id, started_at, completed_at, created_at, updated_at, artifact_schema_version, pipeline_config_hash
FROM drive_ocr_runs
WHERE tenant_id = $1
  AND status = 'completed'
ORDER BY id
LIMIT $2
`

type ListLocalSearchRebuildOCRRunsParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListLocalSearchRebuildOCRRuns(ctx context.Context, arg ListLocalSearchRebuildOCRRunsParams) ([]DriveOcrRun, error) {
	rows, err := q.db.Query(ctx, listLocalSearchRebuildOCRRuns, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveOcrRun
	for rows.Next() {
		var i DriveOcrRun
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.FileObjectID,
			&i.FileRevision,
			&i.ContentSha256,
			&i.Engine,
			&i.Languages,
			&i.StructuredExtractor,
			&i.Status,
			&i.Reason,
			&i.PageCount,
			&i.ProcessedPageCount,
			&i.AverageConfidence,
			&i.ExtractedText,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.RequestedByUserID,
			&i.OutboxEventID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArtifactSchemaVersion,
			&i.PipelineConfigHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSearchRebuildProductExtractionItems = `-- name: ListLocalSearchRebuildProductExtractionItems :many
SELECT id, public_id, tenant_id, ocr_run_id, file_object_id, item_type, name, brand, manufacturer, model, sku, jan_code, category, description, price, promotion, availability, source_text, evidence, attributes, confidence, created_at
FROM drive_product_extraction_items
WHERE tenant_id = $1
ORDER BY id
LIMIT $2
`

type ListLocalSearchRebuildProductExtractionItemsParams struct {
	TenantID   int64 `json:"tenant_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListLocalSearchRebuildProductExtractionItems(ctx context.Context, arg ListLocalSearchRebuildProductExtractionItemsParams) ([]DriveProductExtractionItem, error) {
	rows, err := q.db.Query(ctx, listLocalSearchRebuildProductExtractionItems, arg.TenantID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriveProductExtractionItem
	for rows.Next() {
		var i DriveProductExtractionItem
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.OcrRunID,
			&i.FileObjectID,
			&i.ItemType,
			&i.Name,
			&i.Brand,
			&i.Manufacturer,
			&i.Model,
			&i.Sku,
			&i.JanCode,
			&i.Category,
			&i.Description,
			&i.Price,
			&i.Promotion,
			&i.Availability,
			&i.SourceText,
			&i.Evidence,
			&i.Attributes,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLocalSearchIndexJobProcessing = `-- name: MarkLocalSearchIndexJobProcessing :one
UPDATE local_search_index_jobs
SET
    status = 'processing',
    outbox_event_id = $1,
    attempts = attempts + 1,
    started_at = COALESCE(started_at, now()),
    last_error = NULL,
    updated_at = now()
WHERE id = $2
  AND tenant_id = $3
  AND status IN ('queued', 'processing', 'failed')
RETURNING id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, outbox_event_id, reason, status, attempts, indexed_count, skipped_count, failed_count, last_error, started_at, completed_at, created_at, updated_at
`

type MarkLocalSearchIndexJobProcessingParams struct {
	OutboxEventID pgtype.Int8 `json:"outbox_event_id"`
	ID            int64       `json:"id"`
	TenantID      int64       `json:"tenant_id"`
}

func (q *Queries) MarkLocalSearchIndexJobProcessing(ctx context.Context, arg MarkLocalSearchIndexJobProcessingParams) (LocalSearchIndexJob, error) {
	row := q.db.QueryRow(ctx, markLocalSearchIndexJobProcessing, arg.OutboxEventID, arg.ID, arg.TenantID)
	var i LocalSearchIndexJob
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.OutboxEventID,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.IndexedCount,
		&i.SkippedCount,
		&i.FailedCount,
		&i.LastError,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchLocalSearchDriveFileCandidates = `-- name: SearchLocalSearchDriveFileCandidates :many
WITH candidate_files AS (
    SELECT
        d.file_object_id,
        max(
            CASE
                WHEN $2::text IS NULL THEN 0
                ELSE ts_rank_cd(d.search_vector, websearch_to_tsquery('simple', $2::text))
            END
        ) AS rank,
        max(d.indexed_at) AS latest_indexed_at
    FROM local_search_documents d
    JOIN file_objects f ON f.id = d.file_object_id
    WHERE d.tenant_id = $3
      AND d.file_object_id IS NOT NULL
      AND f.tenant_id = $3
      AND f.purpose = 'drive'
      AND f.deleted_at IS NULL
      AND f.scan_status IN ('clean', 'skipped')
      AND f.dlp_blocked = false
      AND (
          $4::text IS NULL
          OR f.content_type = $4::text
      )
      AND (
          $5::timestamptz IS NULL
          OR f.updated_at >= $5::timestamptz
      )
      AND (
          $6::timestamptz IS NULL
          OR f.updated_at <= $6::timestamptz
      )
      AND (
          $2::text IS NULL
          OR f.original_filename ILIKE '%' || $2::text || '%'
          OR d.title ILIKE '%' || $2::text || '%'
          OR d.body_text ILIKE '%' || $2::text || '%'
          OR d.search_vector @@ websearch_to_tsquery('simple', $2::text)
      )
    GROUP BY d.file_object_id
)
SELECT f.id, f.public_id, f.tenant_id, f.uploaded_by_user_id, f.purpose, f.attached_to_type, f.attached_to_id, f.original_filename, f.content_type, f.byte_size, f.sha256_hex, f.storage_driver, f.storage_key, f.status, f.created_at, f.updated_at, f.deleted_at, f.purged_at, f.purge_attempts, f.purge_locked_at, f.purge_locked_by, f.last_purge_error, f.drive_folder_id, f.locked_at, f.locked_by_user_id, f.lock_reason, f.inheritance_enabled, f.deleted_by_user_id, f.deleted_parent_folder_id, f.retention_until, f.legal_hold_at, f.legal_hold_by_user_id, f.legal_hold_reason, f.purge_block_reason, f.workspace_id, f.storage_bucket, f.storage_version, f.content_sha256, f.etag, f.scan_status, f.scan_reason, f.scan_engine, f.scanned_at, f.dlp_blocked, f.upload_state, f.office_mime_family, f.office_coauthoring_enabled, f.office_last_revision, f.encryption_mode, f.e2ee_file_key_public_id, f.storage_gateway_id, f.description
FROM candidate_files c
JOIN file_objects f ON f.id = c.file_object_id
ORDER BY c.rank DESC, c.latest_indexed_at DESC, f.updated_at DESC, f.id DESC
LIMIT $1
`

type SearchLocalSearchDriveFileCandidatesParams struct {
	LimitCount    int32              `json:"limit_count"`
	Query         pgtype.Text        `json:"query"`
	TenantID      int64              `json:"tenant_id"`
	ContentType   pgtype.Text        `json:"content_type"`
	UpdatedAfter  pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore pgtype.Timestamptz `json:"updated_before"`
}

func (q *Queries) SearchLocalSearchDriveFileCandidates(ctx context.Context, arg SearchLocalSearchDriveFileCandidatesParams) ([]FileObject, error) {
	rows, err := q.db.Query(ctx, searchLocalSearchDriveFileCandidates,
		arg.LimitCount,
		arg.Query,
		arg.TenantID,
		arg.ContentType,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileObject
	for rows.Next() {
		var i FileObject
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.UploadedByUserID,
			&i.Purpose,
			&i.AttachedToType,
			&i.AttachedToID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.ByteSize,
			&i.Sha256Hex,
			&i.StorageDriver,
			&i.StorageKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PurgedAt,
			&i.PurgeAttempts,
			&i.PurgeLockedAt,
			&i.PurgeLockedBy,
			&i.LastPurgeError,
			&i.DriveFolderID,
			&i.LockedAt,
			&i.LockedByUserID,
			&i.LockReason,
			&i.InheritanceEnabled,
			&i.DeletedByUserID,
			&i.DeletedParentFolderID,
			&i.RetentionUntil,
			&i.LegalHoldAt,
			&i.LegalHoldByUserID,
			&i.LegalHoldReason,
			&i.PurgeBlockReason,
			&i.WorkspaceID,
			&i.StorageBucket,
			&i.StorageVersion,
			&i.ContentSha256,
			&i.Etag,
			&i.ScanStatus,
			&i.ScanReason,
			&i.ScanEngine,
			&i.ScannedAt,
			&i.DlpBlocked,
			&i.UploadState,
			&i.OfficeMimeFamily,
			&i.OfficeCoauthoringEnabled,
			&i.OfficeLastRevision,
			&i.EncryptionMode,
			&i.E2eeFileKeyPublicID,
			&i.StorageGatewayID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocalSearchDocument = `-- name: UpsertLocalSearchDocument :one
INSERT INTO local_search_documents (
    tenant_id,
    resource_kind,
    resource_id,
    resource_public_id,
    file_object_id,
    medallion_asset_id,
    gold_publication_id,
    title,
    body_text,
    snippet,
    content_hash,
    source_updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (tenant_id, resource_kind, resource_id) DO UPDATE
SET
    resource_public_id = EXCLUDED.resource_public_id,
    file_object_id = EXCLUDED.file_object_id,
    medallion_asset_id = EXCLUDED.medallion_asset_id,
    gold_publication_id = EXCLUDED.gold_publication_id,
    title = EXCLUDED.title,
    body_text = EXCLUDED.body_text,
    snippet = EXCLUDED.snippet,
    content_hash = EXCLUDED.content_hash,
    source_updated_at = EXCLUDED.source_updated_at,
    indexed_at = now(),
    updated_at = now()
RETURNING id, public_id, tenant_id, resource_kind, resource_id, resource_public_id, file_object_id, medallion_asset_id, gold_publication_id, title, body_text, snippet, content_hash, source_updated_at, indexed_at, search_vector, created_at, updated_at
`

type UpsertLocalSearchDocumentParams struct {
	TenantID          int64              `json:"tenant_id"`
	ResourceKind      string             `json:"resource_kind"`
	ResourceID        int64              `json:"resource_id"`
	ResourcePublicID  uuid.UUID          `json:"resource_public_id"`
	FileObjectID      pgtype.Int8        `json:"file_object_id"`
	MedallionAssetID  pgtype.Int8        `json:"medallion_asset_id"`
	GoldPublicationID pgtype.Int8        `json:"gold_publication_id"`
	Title             string             `json:"title"`
	BodyText          string             `json:"body_text"`
	Snippet           string             `json:"snippet"`
	ContentHash       string             `json:"content_hash"`
	SourceUpdatedAt   pgtype.Timestamptz `json:"source_updated_at"`
}

func (q *Queries) UpsertLocalSearchDocument(ctx context.Context, arg UpsertLocalSearchDocumentParams) (LocalSearchDocument, error) {
	row := q.db.QueryRow(ctx, upsertLocalSearchDocument,
		arg.TenantID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ResourcePublicID,
		arg.FileObjectID,
		arg.MedallionAssetID,
		arg.GoldPublicationID,
		arg.Title,
		arg.BodyText,
		arg.Snippet,
		arg.ContentHash,
		arg.SourceUpdatedAt,
	)
	var i LocalSearchDocument
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.FileObjectID,
		&i.MedallionAssetID,
		&i.GoldPublicationID,
		&i.Title,
		&i.BodyText,
		&i.Snippet,
		&i.ContentHash,
		&i.SourceUpdatedAt,
		&i.IndexedAt,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
