// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medallion_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDriveProductExtractionItemByPublicIDForTenant = `-- name: GetDriveProductExtractionItemByPublicIDForTenant :one
SELECT id, public_id, tenant_id, ocr_run_id, file_object_id, item_type, name, brand, manufacturer, model, sku, jan_code, category, description, price, promotion, availability, source_text, evidence, attributes, confidence, created_at
FROM drive_product_extraction_items
WHERE tenant_id = $1
  AND public_id = $2
LIMIT 1
`

type GetDriveProductExtractionItemByPublicIDForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDriveProductExtractionItemByPublicIDForTenant(ctx context.Context, arg GetDriveProductExtractionItemByPublicIDForTenantParams) (DriveProductExtractionItem, error) {
	row := q.db.QueryRow(ctx, getDriveProductExtractionItemByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i DriveProductExtractionItem
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.OcrRunID,
		&i.FileObjectID,
		&i.ItemType,
		&i.Name,
		&i.Brand,
		&i.Manufacturer,
		&i.Model,
		&i.Sku,
		&i.JanCode,
		&i.Category,
		&i.Description,
		&i.Price,
		&i.Promotion,
		&i.Availability,
		&i.SourceText,
		&i.Evidence,
		&i.Attributes,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const getMedallionAssetByPublicIDForTenant = `-- name: GetMedallionAssetByPublicIDForTenant :one
SELECT id, public_id, tenant_id, layer, resource_kind, resource_id, resource_public_id, display_name, status, row_count, byte_size, schema_summary, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, archived_at
FROM medallion_assets
WHERE tenant_id = $1
  AND public_id = $2
LIMIT 1
`

type GetMedallionAssetByPublicIDForTenantParams struct {
	TenantID int64     `json:"tenant_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetMedallionAssetByPublicIDForTenant(ctx context.Context, arg GetMedallionAssetByPublicIDForTenantParams) (MedallionAsset, error) {
	row := q.db.QueryRow(ctx, getMedallionAssetByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i MedallionAsset
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Layer,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.DisplayName,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.SchemaSummary,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getMedallionAssetByResourceForTenant = `-- name: GetMedallionAssetByResourceForTenant :one
SELECT id, public_id, tenant_id, layer, resource_kind, resource_id, resource_public_id, display_name, status, row_count, byte_size, schema_summary, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, archived_at
FROM medallion_assets
WHERE tenant_id = $1
  AND resource_kind = $2
  AND resource_id = $3
LIMIT 1
`

type GetMedallionAssetByResourceForTenantParams struct {
	TenantID     int64  `json:"tenant_id"`
	ResourceKind string `json:"resource_kind"`
	ResourceID   int64  `json:"resource_id"`
}

func (q *Queries) GetMedallionAssetByResourceForTenant(ctx context.Context, arg GetMedallionAssetByResourceForTenantParams) (MedallionAsset, error) {
	row := q.db.QueryRow(ctx, getMedallionAssetByResourceForTenant, arg.TenantID, arg.ResourceKind, arg.ResourceID)
	var i MedallionAsset
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Layer,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.DisplayName,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.SchemaSummary,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const linkMedallionPipelineRunAsset = `-- name: LinkMedallionPipelineRunAsset :one
INSERT INTO medallion_pipeline_run_assets (
    tenant_id,
    pipeline_run_id,
    asset_id,
    role
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (pipeline_run_id, asset_id, role) DO UPDATE
SET tenant_id = EXCLUDED.tenant_id
RETURNING id, tenant_id, pipeline_run_id, asset_id, role, created_at
`

type LinkMedallionPipelineRunAssetParams struct {
	TenantID      int64  `json:"tenant_id"`
	PipelineRunID int64  `json:"pipeline_run_id"`
	AssetID       int64  `json:"asset_id"`
	Role          string `json:"role"`
}

func (q *Queries) LinkMedallionPipelineRunAsset(ctx context.Context, arg LinkMedallionPipelineRunAssetParams) (MedallionPipelineRunAsset, error) {
	row := q.db.QueryRow(ctx, linkMedallionPipelineRunAsset,
		arg.TenantID,
		arg.PipelineRunID,
		arg.AssetID,
		arg.Role,
	)
	var i MedallionPipelineRunAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PipelineRunID,
		&i.AssetID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMedallionAssets = `-- name: ListMedallionAssets :many
SELECT id, public_id, tenant_id, layer, resource_kind, resource_id, resource_public_id, display_name, status, row_count, byte_size, schema_summary, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, archived_at
FROM medallion_assets
WHERE tenant_id = $1
  AND (
      $2::text IS NULL
      OR layer = $2::text
  )
  AND (
      $3::text IS NULL
      OR resource_kind = $3::text
  )
  AND (
      $4::text IS NULL
      OR display_name ILIKE '%' || $4::text || '%'
      OR metadata::text ILIKE '%' || $4::text || '%'
      OR schema_summary::text ILIKE '%' || $4::text || '%'
      OR to_tsvector('simple', display_name || ' ' || metadata::text || ' ' || schema_summary::text)
         @@ websearch_to_tsquery('simple', $4::text)
  )
ORDER BY
  CASE
      WHEN $4::text IS NULL THEN 0
      ELSE ts_rank_cd(
          to_tsvector('simple', display_name || ' ' || metadata::text || ' ' || schema_summary::text),
          websearch_to_tsquery('simple', $4::text)
      )
  END DESC,
  updated_at DESC,
  id DESC
LIMIT $5
`

type ListMedallionAssetsParams struct {
	TenantID     int64       `json:"tenant_id"`
	Layer        pgtype.Text `json:"layer"`
	ResourceKind pgtype.Text `json:"resource_kind"`
	Q            pgtype.Text `json:"q"`
	LimitCount   int32       `json:"limit_count"`
}

func (q *Queries) ListMedallionAssets(ctx context.Context, arg ListMedallionAssetsParams) ([]MedallionAsset, error) {
	rows, err := q.db.Query(ctx, listMedallionAssets,
		arg.TenantID,
		arg.Layer,
		arg.ResourceKind,
		arg.Q,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedallionAsset
	for rows.Next() {
		var i MedallionAsset
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Layer,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourcePublicID,
			&i.DisplayName,
			&i.Status,
			&i.RowCount,
			&i.ByteSize,
			&i.SchemaSummary,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedallionDownstreamAssets = `-- name: ListMedallionDownstreamAssets :many
SELECT target.id, target.public_id, target.tenant_id, target.layer, target.resource_kind, target.resource_id, target.resource_public_id, target.display_name, target.status, target.row_count, target.byte_size, target.schema_summary, target.metadata, target.created_by_user_id, target.updated_by_user_id, target.created_at, target.updated_at, target.archived_at
FROM medallion_asset_edges edge
JOIN medallion_assets target ON target.id = edge.target_asset_id
WHERE edge.tenant_id = $1
  AND edge.source_asset_id = $2
ORDER BY edge.created_at DESC, edge.id DESC
LIMIT $3
`

type ListMedallionDownstreamAssetsParams struct {
	TenantID   int64 `json:"tenant_id"`
	AssetID    int64 `json:"asset_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListMedallionDownstreamAssets(ctx context.Context, arg ListMedallionDownstreamAssetsParams) ([]MedallionAsset, error) {
	rows, err := q.db.Query(ctx, listMedallionDownstreamAssets, arg.TenantID, arg.AssetID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedallionAsset
	for rows.Next() {
		var i MedallionAsset
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Layer,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourcePublicID,
			&i.DisplayName,
			&i.Status,
			&i.RowCount,
			&i.ByteSize,
			&i.SchemaSummary,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedallionPipelineRunAssetLinks = `-- name: ListMedallionPipelineRunAssetLinks :many
SELECT
    link.role,
    asset.id, asset.public_id, asset.tenant_id, asset.layer, asset.resource_kind, asset.resource_id, asset.resource_public_id, asset.display_name, asset.status, asset.row_count, asset.byte_size, asset.schema_summary, asset.metadata, asset.created_by_user_id, asset.updated_by_user_id, asset.created_at, asset.updated_at, asset.archived_at
FROM medallion_pipeline_run_assets link
JOIN medallion_assets asset ON asset.id = link.asset_id
WHERE link.tenant_id = $1
  AND link.pipeline_run_id = $2
ORDER BY link.role ASC, asset.updated_at DESC, asset.id DESC
`

type ListMedallionPipelineRunAssetLinksParams struct {
	TenantID      int64 `json:"tenant_id"`
	PipelineRunID int64 `json:"pipeline_run_id"`
}

type ListMedallionPipelineRunAssetLinksRow struct {
	Role             string             `json:"role"`
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	TenantID         int64              `json:"tenant_id"`
	Layer            string             `json:"layer"`
	ResourceKind     string             `json:"resource_kind"`
	ResourceID       int64              `json:"resource_id"`
	ResourcePublicID uuid.UUID          `json:"resource_public_id"`
	DisplayName      string             `json:"display_name"`
	Status           string             `json:"status"`
	RowCount         pgtype.Int8        `json:"row_count"`
	ByteSize         pgtype.Int8        `json:"byte_size"`
	SchemaSummary    []byte             `json:"schema_summary"`
	Metadata         []byte             `json:"metadata"`
	CreatedByUserID  pgtype.Int8        `json:"created_by_user_id"`
	UpdatedByUserID  pgtype.Int8        `json:"updated_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ListMedallionPipelineRunAssetLinks(ctx context.Context, arg ListMedallionPipelineRunAssetLinksParams) ([]ListMedallionPipelineRunAssetLinksRow, error) {
	rows, err := q.db.Query(ctx, listMedallionPipelineRunAssetLinks, arg.TenantID, arg.PipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMedallionPipelineRunAssetLinksRow
	for rows.Next() {
		var i ListMedallionPipelineRunAssetLinksRow
		if err := rows.Scan(
			&i.Role,
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Layer,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourcePublicID,
			&i.DisplayName,
			&i.Status,
			&i.RowCount,
			&i.ByteSize,
			&i.SchemaSummary,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedallionPipelineRunsByAsset = `-- name: ListMedallionPipelineRunsByAsset :many
SELECT run.id, run.public_id, run.tenant_id, run.pipeline_type, run.run_key, run.source_resource_kind, run.source_resource_id, run.source_resource_public_id, run.target_resource_kind, run.target_resource_id, run.target_resource_public_id, run.status, run.runtime, run.trigger_kind, run.retryable, run.error_summary, run.metadata, run.requested_by_user_id, run.started_at, run.completed_at, run.created_at, run.updated_at
FROM medallion_pipeline_run_assets link
JOIN medallion_pipeline_runs run ON run.id = link.pipeline_run_id
WHERE link.tenant_id = $1
  AND link.asset_id = $2
ORDER BY run.created_at DESC, run.id DESC
LIMIT $3
`

type ListMedallionPipelineRunsByAssetParams struct {
	TenantID   int64 `json:"tenant_id"`
	AssetID    int64 `json:"asset_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListMedallionPipelineRunsByAsset(ctx context.Context, arg ListMedallionPipelineRunsByAssetParams) ([]MedallionPipelineRun, error) {
	rows, err := q.db.Query(ctx, listMedallionPipelineRunsByAsset, arg.TenantID, arg.AssetID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedallionPipelineRun
	for rows.Next() {
		var i MedallionPipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineType,
			&i.RunKey,
			&i.SourceResourceKind,
			&i.SourceResourceID,
			&i.SourceResourcePublicID,
			&i.TargetResourceKind,
			&i.TargetResourceID,
			&i.TargetResourcePublicID,
			&i.Status,
			&i.Runtime,
			&i.TriggerKind,
			&i.Retryable,
			&i.ErrorSummary,
			&i.Metadata,
			&i.RequestedByUserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedallionPipelineRunsByResource = `-- name: ListMedallionPipelineRunsByResource :many
SELECT id, public_id, tenant_id, pipeline_type, run_key, source_resource_kind, source_resource_id, source_resource_public_id, target_resource_kind, target_resource_id, target_resource_public_id, status, runtime, trigger_kind, retryable, error_summary, metadata, requested_by_user_id, started_at, completed_at, created_at, updated_at
FROM medallion_pipeline_runs
WHERE tenant_id = $1
  AND (
      (source_resource_kind = $2 AND source_resource_id = $3)
      OR (target_resource_kind = $2 AND target_resource_id = $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMedallionPipelineRunsByResourceParams struct {
	TenantID     int64       `json:"tenant_id"`
	ResourceKind pgtype.Text `json:"resource_kind"`
	ResourceID   pgtype.Int8 `json:"resource_id"`
	LimitCount   int32       `json:"limit_count"`
}

func (q *Queries) ListMedallionPipelineRunsByResource(ctx context.Context, arg ListMedallionPipelineRunsByResourceParams) ([]MedallionPipelineRun, error) {
	rows, err := q.db.Query(ctx, listMedallionPipelineRunsByResource,
		arg.TenantID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedallionPipelineRun
	for rows.Next() {
		var i MedallionPipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.PipelineType,
			&i.RunKey,
			&i.SourceResourceKind,
			&i.SourceResourceID,
			&i.SourceResourcePublicID,
			&i.TargetResourceKind,
			&i.TargetResourceID,
			&i.TargetResourcePublicID,
			&i.Status,
			&i.Runtime,
			&i.TriggerKind,
			&i.Retryable,
			&i.ErrorSummary,
			&i.Metadata,
			&i.RequestedByUserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedallionUpstreamAssets = `-- name: ListMedallionUpstreamAssets :many
SELECT source.id, source.public_id, source.tenant_id, source.layer, source.resource_kind, source.resource_id, source.resource_public_id, source.display_name, source.status, source.row_count, source.byte_size, source.schema_summary, source.metadata, source.created_by_user_id, source.updated_by_user_id, source.created_at, source.updated_at, source.archived_at
FROM medallion_asset_edges edge
JOIN medallion_assets source ON source.id = edge.source_asset_id
WHERE edge.tenant_id = $1
  AND edge.target_asset_id = $2
ORDER BY edge.created_at DESC, edge.id DESC
LIMIT $3
`

type ListMedallionUpstreamAssetsParams struct {
	TenantID   int64 `json:"tenant_id"`
	AssetID    int64 `json:"asset_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) ListMedallionUpstreamAssets(ctx context.Context, arg ListMedallionUpstreamAssetsParams) ([]MedallionAsset, error) {
	rows, err := q.db.Query(ctx, listMedallionUpstreamAssets, arg.TenantID, arg.AssetID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedallionAsset
	for rows.Next() {
		var i MedallionAsset
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.Layer,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourcePublicID,
			&i.DisplayName,
			&i.Status,
			&i.RowCount,
			&i.ByteSize,
			&i.SchemaSummary,
			&i.Metadata,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMedallionAsset = `-- name: UpsertMedallionAsset :one
INSERT INTO medallion_assets (
    tenant_id,
    layer,
    resource_kind,
    resource_id,
    resource_public_id,
    display_name,
    status,
    row_count,
    byte_size,
    schema_summary,
    metadata,
    created_by_user_id,
    updated_by_user_id,
    archived_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT (tenant_id, resource_kind, resource_id) DO UPDATE
SET
    layer = EXCLUDED.layer,
    resource_public_id = EXCLUDED.resource_public_id,
    display_name = EXCLUDED.display_name,
    status = EXCLUDED.status,
    row_count = EXCLUDED.row_count,
    byte_size = EXCLUDED.byte_size,
    schema_summary = EXCLUDED.schema_summary,
    metadata = EXCLUDED.metadata,
    updated_by_user_id = COALESCE(EXCLUDED.updated_by_user_id, medallion_assets.updated_by_user_id),
    updated_at = now(),
    archived_at = EXCLUDED.archived_at
RETURNING id, public_id, tenant_id, layer, resource_kind, resource_id, resource_public_id, display_name, status, row_count, byte_size, schema_summary, metadata, created_by_user_id, updated_by_user_id, created_at, updated_at, archived_at
`

type UpsertMedallionAssetParams struct {
	TenantID         int64              `json:"tenant_id"`
	Layer            string             `json:"layer"`
	ResourceKind     string             `json:"resource_kind"`
	ResourceID       int64              `json:"resource_id"`
	ResourcePublicID uuid.UUID          `json:"resource_public_id"`
	DisplayName      string             `json:"display_name"`
	Status           string             `json:"status"`
	RowCount         pgtype.Int8        `json:"row_count"`
	ByteSize         pgtype.Int8        `json:"byte_size"`
	SchemaSummary    []byte             `json:"schema_summary"`
	Metadata         []byte             `json:"metadata"`
	CreatedByUserID  pgtype.Int8        `json:"created_by_user_id"`
	UpdatedByUserID  pgtype.Int8        `json:"updated_by_user_id"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) UpsertMedallionAsset(ctx context.Context, arg UpsertMedallionAssetParams) (MedallionAsset, error) {
	row := q.db.QueryRow(ctx, upsertMedallionAsset,
		arg.TenantID,
		arg.Layer,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ResourcePublicID,
		arg.DisplayName,
		arg.Status,
		arg.RowCount,
		arg.ByteSize,
		arg.SchemaSummary,
		arg.Metadata,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
		arg.ArchivedAt,
	)
	var i MedallionAsset
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.Layer,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourcePublicID,
		&i.DisplayName,
		&i.Status,
		&i.RowCount,
		&i.ByteSize,
		&i.SchemaSummary,
		&i.Metadata,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertMedallionAssetEdge = `-- name: UpsertMedallionAssetEdge :one
INSERT INTO medallion_asset_edges (
    tenant_id,
    source_asset_id,
    target_asset_id,
    relation_type,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (tenant_id, source_asset_id, target_asset_id, relation_type) DO UPDATE
SET metadata = EXCLUDED.metadata
RETURNING id, public_id, tenant_id, source_asset_id, target_asset_id, relation_type, metadata, created_at
`

type UpsertMedallionAssetEdgeParams struct {
	TenantID      int64  `json:"tenant_id"`
	SourceAssetID int64  `json:"source_asset_id"`
	TargetAssetID int64  `json:"target_asset_id"`
	RelationType  string `json:"relation_type"`
	Metadata      []byte `json:"metadata"`
}

func (q *Queries) UpsertMedallionAssetEdge(ctx context.Context, arg UpsertMedallionAssetEdgeParams) (MedallionAssetEdge, error) {
	row := q.db.QueryRow(ctx, upsertMedallionAssetEdge,
		arg.TenantID,
		arg.SourceAssetID,
		arg.TargetAssetID,
		arg.RelationType,
		arg.Metadata,
	)
	var i MedallionAssetEdge
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.SourceAssetID,
		&i.TargetAssetID,
		&i.RelationType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMedallionPipelineRun = `-- name: UpsertMedallionPipelineRun :one
INSERT INTO medallion_pipeline_runs (
    tenant_id,
    pipeline_type,
    run_key,
    source_resource_kind,
    source_resource_id,
    source_resource_public_id,
    target_resource_kind,
    target_resource_id,
    target_resource_public_id,
    status,
    runtime,
    trigger_kind,
    retryable,
    error_summary,
    metadata,
    requested_by_user_id,
    started_at,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
ON CONFLICT (tenant_id, pipeline_type, run_key) DO UPDATE
SET
    source_resource_kind = COALESCE(EXCLUDED.source_resource_kind, medallion_pipeline_runs.source_resource_kind),
    source_resource_id = COALESCE(EXCLUDED.source_resource_id, medallion_pipeline_runs.source_resource_id),
    source_resource_public_id = COALESCE(EXCLUDED.source_resource_public_id, medallion_pipeline_runs.source_resource_public_id),
    target_resource_kind = COALESCE(EXCLUDED.target_resource_kind, medallion_pipeline_runs.target_resource_kind),
    target_resource_id = COALESCE(EXCLUDED.target_resource_id, medallion_pipeline_runs.target_resource_id),
    target_resource_public_id = COALESCE(EXCLUDED.target_resource_public_id, medallion_pipeline_runs.target_resource_public_id),
    status = EXCLUDED.status,
    runtime = EXCLUDED.runtime,
    trigger_kind = EXCLUDED.trigger_kind,
    retryable = EXCLUDED.retryable,
    error_summary = EXCLUDED.error_summary,
    metadata = EXCLUDED.metadata,
    requested_by_user_id = COALESCE(EXCLUDED.requested_by_user_id, medallion_pipeline_runs.requested_by_user_id),
    started_at = COALESCE(medallion_pipeline_runs.started_at, EXCLUDED.started_at),
    completed_at = EXCLUDED.completed_at,
    updated_at = now()
RETURNING id, public_id, tenant_id, pipeline_type, run_key, source_resource_kind, source_resource_id, source_resource_public_id, target_resource_kind, target_resource_id, target_resource_public_id, status, runtime, trigger_kind, retryable, error_summary, metadata, requested_by_user_id, started_at, completed_at, created_at, updated_at
`

type UpsertMedallionPipelineRunParams struct {
	TenantID               int64              `json:"tenant_id"`
	PipelineType           string             `json:"pipeline_type"`
	RunKey                 string             `json:"run_key"`
	SourceResourceKind     pgtype.Text        `json:"source_resource_kind"`
	SourceResourceID       pgtype.Int8        `json:"source_resource_id"`
	SourceResourcePublicID pgtype.UUID        `json:"source_resource_public_id"`
	TargetResourceKind     pgtype.Text        `json:"target_resource_kind"`
	TargetResourceID       pgtype.Int8        `json:"target_resource_id"`
	TargetResourcePublicID pgtype.UUID        `json:"target_resource_public_id"`
	Status                 string             `json:"status"`
	Runtime                string             `json:"runtime"`
	TriggerKind            string             `json:"trigger_kind"`
	Retryable              bool               `json:"retryable"`
	ErrorSummary           pgtype.Text        `json:"error_summary"`
	Metadata               []byte             `json:"metadata"`
	RequestedByUserID      pgtype.Int8        `json:"requested_by_user_id"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpsertMedallionPipelineRun(ctx context.Context, arg UpsertMedallionPipelineRunParams) (MedallionPipelineRun, error) {
	row := q.db.QueryRow(ctx, upsertMedallionPipelineRun,
		arg.TenantID,
		arg.PipelineType,
		arg.RunKey,
		arg.SourceResourceKind,
		arg.SourceResourceID,
		arg.SourceResourcePublicID,
		arg.TargetResourceKind,
		arg.TargetResourceID,
		arg.TargetResourcePublicID,
		arg.Status,
		arg.Runtime,
		arg.TriggerKind,
		arg.Retryable,
		arg.ErrorSummary,
		arg.Metadata,
		arg.RequestedByUserID,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i MedallionPipelineRun
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.PipelineType,
		&i.RunKey,
		&i.SourceResourceKind,
		&i.SourceResourceID,
		&i.SourceResourcePublicID,
		&i.TargetResourceKind,
		&i.TargetResourceID,
		&i.TargetResourcePublicID,
		&i.Status,
		&i.Runtime,
		&i.TriggerKind,
		&i.Retryable,
		&i.ErrorSummary,
		&i.Metadata,
		&i.RequestedByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
