// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID                   int64              `json:"id"`
	PublicID             uuid.UUID          `json:"public_id"`
	ActorType            string             `json:"actor_type"`
	ActorUserID          pgtype.Int8        `json:"actor_user_id"`
	ActorMachineClientID pgtype.Int8        `json:"actor_machine_client_id"`
	TenantID             pgtype.Int8        `json:"tenant_id"`
	Action               string             `json:"action"`
	TargetType           string             `json:"target_type"`
	TargetID             string             `json:"target_id"`
	RequestID            string             `json:"request_id"`
	ClientIp             string             `json:"client_ip"`
	UserAgent            string             `json:"user_agent"`
	Metadata             []byte             `json:"metadata"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type CustomerSignal struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	CustomerName    string             `json:"customer_name"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Source          string             `json:"source"`
	Priority        string             `json:"priority"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type MachineClient struct {
	ID               int64              `json:"id"`
	Provider         string             `json:"provider"`
	ProviderClientID string             `json:"provider_client_id"`
	DisplayName      string             `json:"display_name"`
	DefaultTenantID  pgtype.Int8        `json:"default_tenant_id"`
	AllowedScopes    []string           `json:"allowed_scopes"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OauthUserGrant struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	Provider               string             `json:"provider"`
	ResourceServer         string             `json:"resource_server"`
	ProviderSubject        string             `json:"provider_subject"`
	RefreshTokenCiphertext []byte             `json:"refresh_token_ciphertext"`
	RefreshTokenKeyVersion int32              `json:"refresh_token_key_version"`
	ScopeText              string             `json:"scope_text"`
	GrantedBySessionID     string             `json:"granted_by_session_id"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	LastRefreshedAt        pgtype.Timestamptz `json:"last_refreshed_at"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	LastErrorCode          pgtype.Text        `json:"last_error_code"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TenantID               int64              `json:"tenant_id"`
}

type ProvisioningSyncState struct {
	Source           string             `json:"source"`
	CursorText       pgtype.Text        `json:"cursor_text"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	FailedCount      int32              `json:"failed_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type Tenant struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantMembership struct {
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	RoleID    int64              `json:"role_id"`
	Source    string             `json:"source"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantRoleOverride struct {
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	RoleID    int64              `json:"role_id"`
	Effect    string             `json:"effect"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Todo struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	Title           string             `json:"title"`
	Completed       bool               `json:"completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeactivatedAt   pgtype.Timestamptz `json:"deactivated_at"`
	DefaultTenantID pgtype.Int8        `json:"default_tenant_id"`
}

type UserIdentity struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Provider           string             `json:"provider"`
	Subject            string             `json:"subject"`
	Email              string             `json:"email"`
	EmailVerified      bool               `json:"email_verified"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ExternalID         pgtype.Text        `json:"external_id"`
	ProvisioningSource pgtype.Text        `json:"provisioning_source"`
}

type UserRole struct {
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
