// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID                   int64              `json:"id"`
	PublicID             uuid.UUID          `json:"public_id"`
	ActorType            string             `json:"actor_type"`
	ActorUserID          pgtype.Int8        `json:"actor_user_id"`
	ActorMachineClientID pgtype.Int8        `json:"actor_machine_client_id"`
	TenantID             pgtype.Int8        `json:"tenant_id"`
	Action               string             `json:"action"`
	TargetType           string             `json:"target_type"`
	TargetID             string             `json:"target_id"`
	RequestID            string             `json:"request_id"`
	ClientIp             string             `json:"client_ip"`
	UserAgent            string             `json:"user_agent"`
	Metadata             []byte             `json:"metadata"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type CustomerSignal struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	CustomerName    string             `json:"customer_name"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Source          string             `json:"source"`
	Priority        string             `json:"priority"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type CustomerSignalImportJob struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	RequestedByUserID pgtype.Int8        `json:"requested_by_user_id"`
	InputFileObjectID int64              `json:"input_file_object_id"`
	ErrorFileObjectID pgtype.Int8        `json:"error_file_object_id"`
	OutboxEventID     pgtype.Int8        `json:"outbox_event_id"`
	Status            string             `json:"status"`
	ValidateOnly      bool               `json:"validate_only"`
	TotalRows         int32              `json:"total_rows"`
	ValidRows         int32              `json:"valid_rows"`
	InvalidRows       int32              `json:"invalid_rows"`
	InsertedRows      int32              `json:"inserted_rows"`
	ErrorSummary      pgtype.Text        `json:"error_summary"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type CustomerSignalSavedFilter struct {
	ID          int64              `json:"id"`
	PublicID    uuid.UUID          `json:"public_id"`
	TenantID    int64              `json:"tenant_id"`
	OwnerUserID int64              `json:"owner_user_id"`
	Name        string             `json:"name"`
	Query       string             `json:"query"`
	Filters     []byte             `json:"filters"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type DriveAdminContentAccessSession struct {
	ID             int64              `json:"id"`
	PublicID       uuid.UUID          `json:"public_id"`
	TenantID       int64              `json:"tenant_id"`
	ActorUserID    int64              `json:"actor_user_id"`
	Reason         string             `json:"reason"`
	ReasonCategory string             `json:"reason_category"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DriveChainOfCustodyEvent struct {
	ID          int64              `json:"id"`
	PublicID    uuid.UUID          `json:"public_id"`
	TenantID    int64              `json:"tenant_id"`
	CaseID      pgtype.Int8        `json:"case_id"`
	ExportID    pgtype.Int8        `json:"export_id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DriveCleanRoom struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	Policy          []byte             `json:"policy"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveCleanRoomDataset struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	CleanRoomID        int64              `json:"clean_room_id"`
	TenantID           int64              `json:"tenant_id"`
	SourceFileObjectID int64              `json:"source_file_object_id"`
	SubmittedByUserID  int64              `json:"submitted_by_user_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DriveCleanRoomExport struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	CleanRoomID       int64              `json:"clean_room_id"`
	TenantID          int64              `json:"tenant_id"`
	JobID             pgtype.Int8        `json:"job_id"`
	RequestedByUserID int64              `json:"requested_by_user_id"`
	ApprovedByUserID  pgtype.Int8        `json:"approved_by_user_id"`
	Status            string             `json:"status"`
	RawDatasetExport  bool               `json:"raw_dataset_export"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DriveCleanRoomJob struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	CleanRoomID     int64              `json:"clean_room_id"`
	TenantID        int64              `json:"tenant_id"`
	JobType         string             `json:"job_type"`
	Status          string             `json:"status"`
	ResultMetadata  []byte             `json:"result_metadata"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveCleanRoomParticipant struct {
	ID                  int64              `json:"id"`
	PublicID            uuid.UUID          `json:"public_id"`
	CleanRoomID         int64              `json:"clean_room_id"`
	TenantID            int64              `json:"tenant_id"`
	ParticipantTenantID int64              `json:"participant_tenant_id"`
	UserID              pgtype.Int8        `json:"user_id"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type DriveCleanRoomPolicyDecision struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	CleanRoomID      pgtype.Int8        `json:"clean_room_id"`
	TenantID         int64              `json:"tenant_id"`
	ActorTenantID    pgtype.Int8        `json:"actor_tenant_id"`
	ResourceTenantID pgtype.Int8        `json:"resource_tenant_id"`
	Decision         string             `json:"decision"`
	Reason           string             `json:"reason"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DriveEditLock struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	FileObjectID    int64              `json:"file_object_id"`
	ActorUserID     int64              `json:"actor_user_id"`
	SessionID       int64              `json:"session_id"`
	BaseRevision    int64              `json:"base_revision"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveEditSession struct {
	ID           int64              `json:"id"`
	PublicID     uuid.UUID          `json:"public_id"`
	TenantID     int64              `json:"tenant_id"`
	FileObjectID int64              `json:"file_object_id"`
	ActorUserID  int64              `json:"actor_user_id"`
	Provider     string             `json:"provider"`
	Status       string             `json:"status"`
	BaseRevision int64              `json:"base_revision"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DriveEncryptionPolicy struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      int64              `json:"tenant_id"`
	Scope         string             `json:"scope"`
	Mode          string             `json:"mode"`
	KmsKeyID      pgtype.Int8        `json:"kms_key_id"`
	Status        string             `json:"status"`
	KeyLossPolicy string             `json:"key_loss_policy"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DriveFileRevision struct {
	ID                       int64              `json:"id"`
	PublicID                 uuid.UUID          `json:"public_id"`
	TenantID                 int64              `json:"tenant_id"`
	FileObjectID             int64              `json:"file_object_id"`
	CreatedByUserID          pgtype.Int8        `json:"created_by_user_id"`
	ActorType                string             `json:"actor_type"`
	PreviousOriginalFilename string             `json:"previous_original_filename"`
	PreviousContentType      string             `json:"previous_content_type"`
	PreviousByteSize         int64              `json:"previous_byte_size"`
	PreviousSha256Hex        string             `json:"previous_sha256_hex"`
	PreviousStorageDriver    string             `json:"previous_storage_driver"`
	PreviousStorageKey       string             `json:"previous_storage_key"`
	Reason                   string             `json:"reason"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type DriveFolder struct {
	ID                    int64              `json:"id"`
	PublicID              uuid.UUID          `json:"public_id"`
	TenantID              int64              `json:"tenant_id"`
	ParentFolderID        pgtype.Int8        `json:"parent_folder_id"`
	Name                  string             `json:"name"`
	CreatedByUserID       int64              `json:"created_by_user_id"`
	InheritanceEnabled    bool               `json:"inheritance_enabled"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserID       pgtype.Int8        `json:"deleted_by_user_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedParentFolderID pgtype.Int8        `json:"deleted_parent_folder_id"`
	RetentionUntil        pgtype.Timestamptz `json:"retention_until"`
	LegalHoldAt           pgtype.Timestamptz `json:"legal_hold_at"`
	LegalHoldByUserID     pgtype.Int8        `json:"legal_hold_by_user_id"`
	LegalHoldReason       pgtype.Text        `json:"legal_hold_reason"`
	PurgeBlockReason      pgtype.Text        `json:"purge_block_reason"`
	WorkspaceID           pgtype.Int8        `json:"workspace_id"`
}

type DriveGroup struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveGroupExternalMapping struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	DriveGroupID    int64              `json:"drive_group_id"`
	Provider        string             `json:"provider"`
	ExternalGroupID string             `json:"external_group_id"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveGroupMember struct {
	ID            int64              `json:"id"`
	GroupID       int64              `json:"group_id"`
	UserID        int64              `json:"user_id"`
	AddedByUserID int64              `json:"added_by_user_id"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DriveIndexJob struct {
	ID           int64              `json:"id"`
	PublicID     uuid.UUID          `json:"public_id"`
	TenantID     int64              `json:"tenant_id"`
	FileObjectID int64              `json:"file_object_id"`
	Reason       string             `json:"reason"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	LastError    pgtype.Text        `json:"last_error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DriveKeyRotationJob struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      int64              `json:"tenant_id"`
	OldKmsKeyID   pgtype.Int8        `json:"old_kms_key_id"`
	NewKmsKeyID   pgtype.Int8        `json:"new_kms_key_id"`
	Status        string             `json:"status"`
	ProgressCount int64              `json:"progress_count"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DriveKmsKey struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	Provider        string             `json:"provider"`
	KeyRef          string             `json:"key_ref"`
	MaskedKeyRef    string             `json:"masked_key_ref"`
	Status          string             `json:"status"`
	LastVerifiedAt  pgtype.Timestamptz `json:"last_verified_at"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveLegalCase struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	Status          string             `json:"status"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveLegalCaseResource struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      int64              `json:"tenant_id"`
	CaseID        int64              `json:"case_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    int64              `json:"resource_id"`
	HoldEnabled   bool               `json:"hold_enabled"`
	AddedByUserID int64              `json:"added_by_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DriveLegalExport struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	CaseID            int64              `json:"case_id"`
	RequestedByUserID int64              `json:"requested_by_user_id"`
	ApprovedByUserID  pgtype.Int8        `json:"approved_by_user_id"`
	Status            string             `json:"status"`
	PackageStorageKey pgtype.Text        `json:"package_storage_key"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DriveLegalExportItem struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	ExportID     int64              `json:"export_id"`
	FileObjectID int64              `json:"file_object_id"`
	Status       string             `json:"status"`
	DenialReason pgtype.Text        `json:"denial_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DriveLegalHold struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	TenantID         int64              `json:"tenant_id"`
	CaseID           int64              `json:"case_id"`
	ResourceType     string             `json:"resource_type"`
	ResourceID       int64              `json:"resource_id"`
	Reason           string             `json:"reason"`
	CreatedByUserID  int64              `json:"created_by_user_id"`
	ReleasedByUserID pgtype.Int8        `json:"released_by_user_id"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DriveMobileOfflineOperation struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	TenantID         int64              `json:"tenant_id"`
	DeviceID         int64              `json:"device_id"`
	OperationType    string             `json:"operation_type"`
	ResourceType     string             `json:"resource_type"`
	ResourcePublicID uuid.UUID          `json:"resource_public_id"`
	BaseRevision     int64              `json:"base_revision"`
	Status           string             `json:"status"`
	FailureReason    pgtype.Text        `json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
}

type DriveObjectKeyVersion struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	FileObjectID int64              `json:"file_object_id"`
	KmsKeyID     pgtype.Int8        `json:"kms_key_id"`
	KeyVersion   string             `json:"key_version"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DrivePresenceSession struct {
	ID           int64              `json:"id"`
	PublicID     uuid.UUID          `json:"public_id"`
	TenantID     int64              `json:"tenant_id"`
	FileObjectID int64              `json:"file_object_id"`
	ActorUserID  int64              `json:"actor_user_id"`
	SessionID    pgtype.Int8        `json:"session_id"`
	Status       string             `json:"status"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DriveRegionMigrationJob struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	WorkspaceID     pgtype.Int8        `json:"workspace_id"`
	SourceRegion    string             `json:"source_region"`
	TargetRegion    string             `json:"target_region"`
	DryRun          bool               `json:"dry_run"`
	Status          string             `json:"status"`
	RollbackPlan    pgtype.Text        `json:"rollback_plan"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveRegionPlacementEvent struct {
	ID           int64              `json:"id"`
	PublicID     uuid.UUID          `json:"public_id"`
	TenantID     int64              `json:"tenant_id"`
	WorkspaceID  pgtype.Int8        `json:"workspace_id"`
	FileObjectID pgtype.Int8        `json:"file_object_id"`
	Subsystem    string             `json:"subsystem"`
	Region       string             `json:"region"`
	Decision     string             `json:"decision"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DriveRegionPolicy struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	PrimaryRegion   string             `json:"primary_region"`
	AllowedRegions  []string           `json:"allowed_regions"`
	ReplicationMode string             `json:"replication_mode"`
	IndexRegion     string             `json:"index_region"`
	BackupRegion    string             `json:"backup_region"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveRemoteWipeRequest struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	DeviceID          int64              `json:"device_id"`
	RequestedByUserID pgtype.Int8        `json:"requested_by_user_id"`
	Reason            string             `json:"reason"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AcknowledgedAt    pgtype.Timestamptz `json:"acknowledged_at"`
}

type DriveResourceShare struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	ResourceType    string             `json:"resource_type"`
	ResourceID      int64              `json:"resource_id"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       int64              `json:"subject_id"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	RevokedByUserID pgtype.Int8        `json:"revoked_by_user_id"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveSearchDocument struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	WorkspaceID     pgtype.Int8        `json:"workspace_id"`
	FileObjectID    int64              `json:"file_object_id"`
	Title           string             `json:"title"`
	ContentType     string             `json:"content_type"`
	ExtractedText   string             `json:"extracted_text"`
	Snippet         string             `json:"snippet"`
	ContentSha256   pgtype.Text        `json:"content_sha256"`
	ObjectUpdatedAt pgtype.Timestamptz `json:"object_updated_at"`
	IndexedAt       pgtype.Timestamptz `json:"indexed_at"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DriveShareInvitation struct {
	ID                   int64              `json:"id"`
	PublicID             uuid.UUID          `json:"public_id"`
	TenantID             int64              `json:"tenant_id"`
	ResourceType         string             `json:"resource_type"`
	ResourceID           int64              `json:"resource_id"`
	InviteeEmailHash     string             `json:"invitee_email_hash"`
	InviteeEmailDomain   string             `json:"invitee_email_domain"`
	InviteeUserID        pgtype.Int8        `json:"invitee_user_id"`
	Role                 string             `json:"role"`
	Status               string             `json:"status"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ApprovedByUserID     pgtype.Int8        `json:"approved_by_user_id"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	AcceptedAt           pgtype.Timestamptz `json:"accepted_at"`
	RevokedByUserID      pgtype.Int8        `json:"revoked_by_user_id"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	CreatedByUserID      int64              `json:"created_by_user_id"`
	AcceptTokenHash      pgtype.Text        `json:"accept_token_hash"`
	AcceptTokenExpiresAt pgtype.Timestamptz `json:"accept_token_expires_at"`
	MaskedInviteeEmail   pgtype.Text        `json:"masked_invitee_email"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type DriveShareLink struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        int64              `json:"resource_id"`
	TokenHash         string             `json:"token_hash"`
	Role              string             `json:"role"`
	CanDownload       bool               `json:"can_download"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	CreatedByUserID   int64              `json:"created_by_user_id"`
	DisabledByUserID  pgtype.Int8        `json:"disabled_by_user_id"`
	DisabledAt        pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	PasswordRequired  bool               `json:"password_required"`
	PasswordUpdatedAt pgtype.Timestamptz `json:"password_updated_at"`
}

type DriveShareLinkPasswordAttempt struct {
	ID           int64              `json:"id"`
	TokenHash    string             `json:"token_hash"`
	RequesterKey string             `json:"requester_key"`
	FailedCount  int32              `json:"failed_count"`
	BlockedUntil pgtype.Timestamptz `json:"blocked_until"`
	LastFailedAt pgtype.Timestamptz `json:"last_failed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DriveSyncConflict struct {
	ID           int64              `json:"id"`
	PublicID     uuid.UUID          `json:"public_id"`
	TenantID     int64              `json:"tenant_id"`
	DeviceID     pgtype.Int8        `json:"device_id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   int64              `json:"resource_id"`
	Reason       string             `json:"reason"`
	Status       string             `json:"status"`
	Resolution   pgtype.Text        `json:"resolution"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DriveSyncCursor struct {
	ID           int64              `json:"id"`
	PublicID     uuid.UUID          `json:"public_id"`
	TenantID     int64              `json:"tenant_id"`
	DeviceID     int64              `json:"device_id"`
	CursorValue  int64              `json:"cursor_value"`
	LastIssuedAt pgtype.Timestamptz `json:"last_issued_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DriveSyncDevice struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	TenantID           int64              `json:"tenant_id"`
	UserID             int64              `json:"user_id"`
	DeviceName         string             `json:"device_name"`
	Platform           string             `json:"platform"`
	TokenHash          string             `json:"token_hash"`
	Status             string             `json:"status"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	LastIp             pgtype.Text        `json:"last_ip"`
	LastUserAgent      pgtype.Text        `json:"last_user_agent"`
	RemoteWipeRequired bool               `json:"remote_wipe_required"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DriveSyncEvent struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      int64              `json:"tenant_id"`
	WorkspaceID   pgtype.Int8        `json:"workspace_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    int64              `json:"resource_id"`
	Action        string             `json:"action"`
	ObjectVersion pgtype.Text        `json:"object_version"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DriveWorkspace struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	Name              string             `json:"name"`
	RootFolderID      pgtype.Int8        `json:"root_folder_id"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
	StorageQuotaBytes pgtype.Int8        `json:"storage_quota_bytes"`
	PolicyOverride    []byte             `json:"policy_override"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DriveWorkspaceRegionOverride struct {
	ID            int64              `json:"id"`
	TenantID      int64              `json:"tenant_id"`
	WorkspaceID   int64              `json:"workspace_id"`
	PrimaryRegion string             `json:"primary_region"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FeatureDefinition struct {
	Code           string             `json:"code"`
	DisplayName    string             `json:"display_name"`
	Description    string             `json:"description"`
	DefaultEnabled bool               `json:"default_enabled"`
	DefaultLimit   []byte             `json:"default_limit"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FileObject struct {
	ID                    int64              `json:"id"`
	PublicID              uuid.UUID          `json:"public_id"`
	TenantID              int64              `json:"tenant_id"`
	UploadedByUserID      pgtype.Int8        `json:"uploaded_by_user_id"`
	Purpose               string             `json:"purpose"`
	AttachedToType        pgtype.Text        `json:"attached_to_type"`
	AttachedToID          pgtype.Text        `json:"attached_to_id"`
	OriginalFilename      string             `json:"original_filename"`
	ContentType           string             `json:"content_type"`
	ByteSize              int64              `json:"byte_size"`
	Sha256Hex             string             `json:"sha256_hex"`
	StorageDriver         string             `json:"storage_driver"`
	StorageKey            string             `json:"storage_key"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	PurgedAt              pgtype.Timestamptz `json:"purged_at"`
	PurgeAttempts         int32              `json:"purge_attempts"`
	PurgeLockedAt         pgtype.Timestamptz `json:"purge_locked_at"`
	PurgeLockedBy         pgtype.Text        `json:"purge_locked_by"`
	LastPurgeError        pgtype.Text        `json:"last_purge_error"`
	DriveFolderID         pgtype.Int8        `json:"drive_folder_id"`
	LockedAt              pgtype.Timestamptz `json:"locked_at"`
	LockedByUserID        pgtype.Int8        `json:"locked_by_user_id"`
	LockReason            pgtype.Text        `json:"lock_reason"`
	InheritanceEnabled    bool               `json:"inheritance_enabled"`
	DeletedByUserID       pgtype.Int8        `json:"deleted_by_user_id"`
	DeletedParentFolderID pgtype.Int8        `json:"deleted_parent_folder_id"`
	RetentionUntil        pgtype.Timestamptz `json:"retention_until"`
	LegalHoldAt           pgtype.Timestamptz `json:"legal_hold_at"`
	LegalHoldByUserID     pgtype.Int8        `json:"legal_hold_by_user_id"`
	LegalHoldReason       pgtype.Text        `json:"legal_hold_reason"`
	PurgeBlockReason      pgtype.Text        `json:"purge_block_reason"`
	WorkspaceID           pgtype.Int8        `json:"workspace_id"`
	StorageBucket         pgtype.Text        `json:"storage_bucket"`
	StorageVersion        pgtype.Text        `json:"storage_version"`
	ContentSha256         pgtype.Text        `json:"content_sha256"`
	Etag                  pgtype.Text        `json:"etag"`
	ScanStatus            string             `json:"scan_status"`
	ScanReason            pgtype.Text        `json:"scan_reason"`
	ScanEngine            pgtype.Text        `json:"scan_engine"`
	ScannedAt             pgtype.Timestamptz `json:"scanned_at"`
	DlpBlocked            bool               `json:"dlp_blocked"`
	UploadState           string             `json:"upload_state"`
}

type IdempotencyKey struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	TenantID           pgtype.Int8        `json:"tenant_id"`
	ActorUserID        pgtype.Int8        `json:"actor_user_id"`
	Scope              string             `json:"scope"`
	IdempotencyKeyHash string             `json:"idempotency_key_hash"`
	Method             string             `json:"method"`
	Path               string             `json:"path"`
	RequestHash        string             `json:"request_hash"`
	Status             string             `json:"status"`
	ResponseStatus     pgtype.Int4        `json:"response_status"`
	ResponseSummary    []byte             `json:"response_summary"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type MachineClient struct {
	ID               int64              `json:"id"`
	Provider         string             `json:"provider"`
	ProviderClientID string             `json:"provider_client_id"`
	DisplayName      string             `json:"display_name"`
	DefaultTenantID  pgtype.Int8        `json:"default_tenant_id"`
	AllowedScopes    []string           `json:"allowed_scopes"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        pgtype.Int8        `json:"tenant_id"`
	RecipientUserID int64              `json:"recipient_user_id"`
	Channel         string             `json:"channel"`
	Template        string             `json:"template"`
	Subject         string             `json:"subject"`
	Body            string             `json:"body"`
	Metadata        []byte             `json:"metadata"`
	Status          string             `json:"status"`
	OutboxEventID   pgtype.Int8        `json:"outbox_event_id"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OauthUserGrant struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	Provider               string             `json:"provider"`
	ResourceServer         string             `json:"resource_server"`
	ProviderSubject        string             `json:"provider_subject"`
	RefreshTokenCiphertext []byte             `json:"refresh_token_ciphertext"`
	RefreshTokenKeyVersion int32              `json:"refresh_token_key_version"`
	ScopeText              string             `json:"scope_text"`
	GrantedBySessionID     string             `json:"granted_by_session_id"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	LastRefreshedAt        pgtype.Timestamptz `json:"last_refreshed_at"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	LastErrorCode          pgtype.Text        `json:"last_error_code"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TenantID               int64              `json:"tenant_id"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	PublicID      uuid.UUID          `json:"public_id"`
	TenantID      pgtype.Int8        `json:"tenant_id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type ProvisioningSyncState struct {
	Source           string             `json:"source"`
	CursorText       pgtype.Text        `json:"cursor_text"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	LastErrorMessage pgtype.Text        `json:"last_error_message"`
	FailedCount      int32              `json:"failed_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type SupportAccessSession struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	SupportUserID      int64              `json:"support_user_id"`
	ImpersonatedUserID int64              `json:"impersonated_user_id"`
	TenantID           int64              `json:"tenant_id"`
	Reason             string             `json:"reason"`
	Status             string             `json:"status"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantDataExport struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	RequestedByUserID pgtype.Int8        `json:"requested_by_user_id"`
	OutboxEventID     pgtype.Int8        `json:"outbox_event_id"`
	FileObjectID      pgtype.Int8        `json:"file_object_id"`
	Format            string             `json:"format"`
	Status            string             `json:"status"`
	ErrorSummary      pgtype.Text        `json:"error_summary"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type TenantEntitlement struct {
	TenantID    int64              `json:"tenant_id"`
	FeatureCode string             `json:"feature_code"`
	Enabled     bool               `json:"enabled"`
	LimitValue  []byte             `json:"limit_value"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantInvitation struct {
	ID                     int64              `json:"id"`
	PublicID               uuid.UUID          `json:"public_id"`
	TenantID               int64              `json:"tenant_id"`
	InvitedByUserID        pgtype.Int8        `json:"invited_by_user_id"`
	AcceptedByUserID       pgtype.Int8        `json:"accepted_by_user_id"`
	InviteeEmailNormalized string             `json:"invitee_email_normalized"`
	RoleCodes              []byte             `json:"role_codes"`
	TokenHash              string             `json:"token_hash"`
	Status                 string             `json:"status"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type TenantMembership struct {
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	RoleID    int64              `json:"role_id"`
	Source    string             `json:"source"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantRoleOverride struct {
	UserID    int64              `json:"user_id"`
	TenantID  int64              `json:"tenant_id"`
	RoleID    int64              `json:"role_id"`
	Effect    string             `json:"effect"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantSetting struct {
	TenantID                      int64              `json:"tenant_id"`
	FileQuotaBytes                int64              `json:"file_quota_bytes"`
	RateLimitLoginPerMinute       pgtype.Int4        `json:"rate_limit_login_per_minute"`
	RateLimitBrowserApiPerMinute  pgtype.Int4        `json:"rate_limit_browser_api_per_minute"`
	RateLimitExternalApiPerMinute pgtype.Int4        `json:"rate_limit_external_api_per_minute"`
	NotificationsEnabled          bool               `json:"notifications_enabled"`
	Features                      []byte             `json:"features"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
}

type Todo struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TenantID        int64              `json:"tenant_id"`
	CreatedByUserID int64              `json:"created_by_user_id"`
	Title           string             `json:"title"`
	Completed       bool               `json:"completed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeactivatedAt   pgtype.Timestamptz `json:"deactivated_at"`
	DefaultTenantID pgtype.Int8        `json:"default_tenant_id"`
}

type UserIdentity struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Provider           string             `json:"provider"`
	Subject            string             `json:"subject"`
	Email              string             `json:"email"`
	EmailVerified      bool               `json:"email_verified"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ExternalID         pgtype.Text        `json:"external_id"`
	ProvisioningSource pgtype.Text        `json:"provisioning_source"`
}

type UserRole struct {
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	TenantID          int64              `json:"tenant_id"`
	WebhookEndpointID int64              `json:"webhook_endpoint_id"`
	OutboxEventID     pgtype.Int8        `json:"outbox_event_id"`
	EventType         string             `json:"event_type"`
	Payload           []byte             `json:"payload"`
	Status            string             `json:"status"`
	AttemptCount      int32              `json:"attempt_count"`
	MaxAttempts       int32              `json:"max_attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	LastHttpStatus    pgtype.Int4        `json:"last_http_status"`
	LastError         pgtype.Text        `json:"last_error"`
	ResponsePreview   pgtype.Text        `json:"response_preview"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type WebhookEndpoint struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	TenantID         int64              `json:"tenant_id"`
	CreatedByUserID  pgtype.Int8        `json:"created_by_user_id"`
	Name             string             `json:"name"`
	Url              string             `json:"url"`
	EventTypes       []string           `json:"event_types"`
	SecretCiphertext string             `json:"secret_ciphertext"`
	SecretKeyVersion int32              `json:"secret_key_version"`
	Active           bool               `json:"active"`
	LastDeliveryAt   pgtype.Timestamptz `json:"last_delivery_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}
