// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    tenant_id,
    recipient_user_id,
    channel,
    template,
    subject,
    body,
    metadata,
    outbox_event_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, public_id, tenant_id, recipient_user_id, channel, template, subject, body, metadata, status, outbox_event_id, read_at, created_at, updated_at
`

type CreateNotificationParams struct {
	TenantID        pgtype.Int8 `json:"tenant_id"`
	RecipientUserID int64       `json:"recipient_user_id"`
	Channel         string      `json:"channel"`
	Template        string      `json:"template"`
	Subject         string      `json:"subject"`
	Body            string      `json:"body"`
	Metadata        []byte      `json:"metadata"`
	OutboxEventID   pgtype.Int8 `json:"outbox_event_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.RecipientUserID,
		arg.Channel,
		arg.Template,
		arg.Subject,
		arg.Body,
		arg.Metadata,
		arg.OutboxEventID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RecipientUserID,
		&i.Channel,
		&i.Template,
		&i.Subject,
		&i.Body,
		&i.Metadata,
		&i.Status,
		&i.OutboxEventID,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReadNotificationsBefore = `-- name: DeleteReadNotificationsBefore :execrows
DELETE FROM notifications
WHERE read_at IS NOT NULL
  AND updated_at < $1
`

func (q *Queries) DeleteReadNotificationsBefore(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadNotificationsBefore, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, public_id, tenant_id, recipient_user_id, channel, template, subject, body, metadata, status, outbox_event_id, read_at, created_at, updated_at
FROM notifications
WHERE recipient_user_id = $1
  AND ($2::bigint = 0 OR tenant_id = $2)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListNotificationsForUserParams struct {
	RecipientUserID int64 `json:"recipient_user_id"`
	Column2         int64 `json:"column_2"`
	Limit           int32 `json:"limit"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, arg.RecipientUserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.RecipientUserID,
			&i.Channel,
			&i.Template,
			&i.Subject,
			&i.Body,
			&i.Metadata,
			&i.Status,
			&i.OutboxEventID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET
    status = 'read',
    read_at = COALESCE(read_at, now()),
    updated_at = now()
WHERE public_id = $1
  AND recipient_user_id = $2
RETURNING id, public_id, tenant_id, recipient_user_id, channel, template, subject, body, metadata, status, outbox_event_id, read_at, created_at, updated_at
`

type MarkNotificationReadParams struct {
	PublicID        uuid.UUID `json:"public_id"`
	RecipientUserID int64     `json:"recipient_user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.PublicID, arg.RecipientUserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RecipientUserID,
		&i.Channel,
		&i.Template,
		&i.Subject,
		&i.Body,
		&i.Metadata,
		&i.Status,
		&i.OutboxEventID,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
