// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
UPDATE outbox_events
SET
    status = 'processing',
    locked_at = now(),
    locked_by = $1,
    attempts = attempts + 1,
    updated_at = now()
WHERE id IN (
    SELECT id
    FROM outbox_events
    WHERE status IN ('pending', 'failed')
      AND available_at <= now()
      AND attempts < max_attempts
    ORDER BY available_at, id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, public_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at, processed_at
`

type ClaimOutboxEventsParams struct {
	WorkerID  pgtype.Text `json:"worker_id"`
	BatchSize int32       `json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, arg.WorkerID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    tenant_id,
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    max_attempts
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, public_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at, processed_at
`

type CreateOutboxEventParams struct {
	TenantID      pgtype.Int8 `json:"tenant_id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   string      `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
	MaxAttempts   int32       `json:"max_attempts"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.TenantID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteProcessedOutboxEventsBefore = `-- name: DeleteProcessedOutboxEventsBefore :execrows
DELETE FROM outbox_events
WHERE status IN ('sent', 'dead')
  AND updated_at < $1
`

func (q *Queries) DeleteProcessedOutboxEventsBefore(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcessedOutboxEventsBefore, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEventDead = `-- name: MarkOutboxEventDead :one
UPDATE outbox_events
SET
    status = 'dead',
    locked_at = NULL,
    locked_by = NULL,
    last_error = left($1, 1000),
    updated_at = now()
WHERE id = $2
RETURNING id, public_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at, processed_at
`

type MarkOutboxEventDeadParams struct {
	LastError string `json:"last_error"`
	ID        int64  `json:"id"`
}

func (q *Queries) MarkOutboxEventDead(ctx context.Context, arg MarkOutboxEventDeadParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventDead, arg.LastError, arg.ID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markOutboxEventRetry = `-- name: MarkOutboxEventRetry :one
UPDATE outbox_events
SET
    status = 'failed',
    locked_at = NULL,
    locked_by = NULL,
    last_error = left($1, 1000),
    available_at = now() + $2,
    updated_at = now()
WHERE id = $3
RETURNING id, public_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at, processed_at
`

type MarkOutboxEventRetryParams struct {
	LastError string      `json:"last_error"`
	Backoff   interface{} `json:"backoff"`
	ID        int64       `json:"id"`
}

func (q *Queries) MarkOutboxEventRetry(ctx context.Context, arg MarkOutboxEventRetryParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventRetry, arg.LastError, arg.Backoff, arg.ID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markOutboxEventSent = `-- name: MarkOutboxEventSent :one
UPDATE outbox_events
SET
    status = 'sent',
    locked_at = NULL,
    locked_by = NULL,
    last_error = NULL,
    processed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, max_attempts, available_at, locked_at, locked_by, last_error, created_at, updated_at, processed_at
`

func (q *Queries) MarkOutboxEventSent(ctx context.Context, id int64) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxEventSent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}
