// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: roles.sql

package db

import (
	"context"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (
    user_id,
    role_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignUserRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const deleteUserRolesByUserID = `-- name: DeleteUserRolesByUserID :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) DeleteUserRolesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByUserID, userID)
	return err
}

const deleteUserRolesExcluding = `-- name: DeleteUserRolesExcluding :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND NOT (role_id = ANY($2::bigint[]))
`

type DeleteUserRolesExcludingParams struct {
	UserID  int64   `json:"user_id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) DeleteUserRolesExcluding(ctx context.Context, arg DeleteUserRolesExcludingParams) error {
	_, err := q.db.Exec(ctx, deleteUserRolesExcluding, arg.UserID, arg.Column2)
	return err
}

const getRolesByCode = `-- name: GetRolesByCode :many
SELECT
    id,
    code
FROM roles
WHERE code = ANY($1::text[])
ORDER BY code
`

type GetRolesByCodeRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) GetRolesByCode(ctx context.Context, dollar_1 []string) ([]GetRolesByCodeRow, error) {
	rows, err := q.db.Query(ctx, getRolesByCode, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesByCodeRow
	for rows.Next() {
		var i GetRolesByCodeRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleCodesByUserID = `-- name: ListRoleCodesByUserID :many
SELECT r.code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.code
`

func (q *Queries) ListRoleCodesByUserID(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
