// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: support_access.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSupportAccessSession = `-- name: CreateSupportAccessSession :one
INSERT INTO support_access_sessions (
    support_user_id,
    impersonated_user_id,
    tenant_id,
    reason,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, public_id, support_user_id, impersonated_user_id, tenant_id, reason, status, started_at, expires_at, ended_at, created_at, updated_at
`

type CreateSupportAccessSessionParams struct {
	SupportUserID      int64              `json:"support_user_id"`
	ImpersonatedUserID int64              `json:"impersonated_user_id"`
	TenantID           int64              `json:"tenant_id"`
	Reason             string             `json:"reason"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSupportAccessSession(ctx context.Context, arg CreateSupportAccessSessionParams) (SupportAccessSession, error) {
	row := q.db.QueryRow(ctx, createSupportAccessSession,
		arg.SupportUserID,
		arg.ImpersonatedUserID,
		arg.TenantID,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i SupportAccessSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SupportUserID,
		&i.ImpersonatedUserID,
		&i.TenantID,
		&i.Reason,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endSupportAccessSession = `-- name: EndSupportAccessSession :one
UPDATE support_access_sessions
SET
    status = 'ended',
    ended_at = COALESCE(ended_at, now()),
    updated_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING id, public_id, support_user_id, impersonated_user_id, tenant_id, reason, status, started_at, expires_at, ended_at, created_at, updated_at
`

func (q *Queries) EndSupportAccessSession(ctx context.Context, id int64) (SupportAccessSession, error) {
	row := q.db.QueryRow(ctx, endSupportAccessSession, id)
	var i SupportAccessSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SupportUserID,
		&i.ImpersonatedUserID,
		&i.TenantID,
		&i.Reason,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireSupportAccessSession = `-- name: ExpireSupportAccessSession :one
UPDATE support_access_sessions
SET
    status = 'expired',
    ended_at = COALESCE(ended_at, now()),
    updated_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING id, public_id, support_user_id, impersonated_user_id, tenant_id, reason, status, started_at, expires_at, ended_at, created_at, updated_at
`

func (q *Queries) ExpireSupportAccessSession(ctx context.Context, id int64) (SupportAccessSession, error) {
	row := q.db.QueryRow(ctx, expireSupportAccessSession, id)
	var i SupportAccessSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SupportUserID,
		&i.ImpersonatedUserID,
		&i.TenantID,
		&i.Reason,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupportAccessSessionByID = `-- name: GetSupportAccessSessionByID :one
SELECT
    sas.id,
    sas.public_id,
    sas.support_user_id,
    sas.impersonated_user_id,
    sas.tenant_id,
    sas.reason,
    sas.status,
    sas.started_at,
    sas.expires_at,
    sas.ended_at,
    sas.created_at,
    sas.updated_at,
    su.public_id AS support_user_public_id,
    su.email AS support_user_email,
    su.display_name AS support_user_display_name,
    iu.public_id AS impersonated_user_public_id,
    iu.email AS impersonated_user_email,
    iu.display_name AS impersonated_user_display_name,
    t.slug AS tenant_slug,
    t.display_name AS tenant_display_name
FROM support_access_sessions sas
JOIN users su ON su.id = sas.support_user_id
JOIN users iu ON iu.id = sas.impersonated_user_id
JOIN tenants t ON t.id = sas.tenant_id
WHERE sas.id = $1
LIMIT 1
`

type GetSupportAccessSessionByIDRow struct {
	ID                          int64              `json:"id"`
	PublicID                    uuid.UUID          `json:"public_id"`
	SupportUserID               int64              `json:"support_user_id"`
	ImpersonatedUserID          int64              `json:"impersonated_user_id"`
	TenantID                    int64              `json:"tenant_id"`
	Reason                      string             `json:"reason"`
	Status                      string             `json:"status"`
	StartedAt                   pgtype.Timestamptz `json:"started_at"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	EndedAt                     pgtype.Timestamptz `json:"ended_at"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	SupportUserPublicID         uuid.UUID          `json:"support_user_public_id"`
	SupportUserEmail            string             `json:"support_user_email"`
	SupportUserDisplayName      string             `json:"support_user_display_name"`
	ImpersonatedUserPublicID    uuid.UUID          `json:"impersonated_user_public_id"`
	ImpersonatedUserEmail       string             `json:"impersonated_user_email"`
	ImpersonatedUserDisplayName string             `json:"impersonated_user_display_name"`
	TenantSlug                  string             `json:"tenant_slug"`
	TenantDisplayName           string             `json:"tenant_display_name"`
}

func (q *Queries) GetSupportAccessSessionByID(ctx context.Context, id int64) (GetSupportAccessSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSupportAccessSessionByID, id)
	var i GetSupportAccessSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SupportUserID,
		&i.ImpersonatedUserID,
		&i.TenantID,
		&i.Reason,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupportUserPublicID,
		&i.SupportUserEmail,
		&i.SupportUserDisplayName,
		&i.ImpersonatedUserPublicID,
		&i.ImpersonatedUserEmail,
		&i.ImpersonatedUserDisplayName,
		&i.TenantSlug,
		&i.TenantDisplayName,
	)
	return i, err
}
