// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tenant_data_exports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantDataExport = `-- name: CreateTenantDataExport :one
INSERT INTO tenant_data_exports (
    tenant_id,
    requested_by_user_id,
    format,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
`

type CreateTenantDataExportParams struct {
	TenantID          int64              `json:"tenant_id"`
	RequestedByUserID pgtype.Int8        `json:"requested_by_user_id"`
	Format            string             `json:"format"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTenantDataExport(ctx context.Context, arg CreateTenantDataExportParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, createTenantDataExport,
		arg.TenantID,
		arg.RequestedByUserID,
		arg.Format,
		arg.ExpiresAt,
	)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantDataExportByIDForTenant = `-- name: GetTenantDataExportByIDForTenant :one
SELECT id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
FROM tenant_data_exports
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetTenantDataExportByIDForTenantParams struct {
	ID       int64 `json:"id"`
	TenantID int64 `json:"tenant_id"`
}

func (q *Queries) GetTenantDataExportByIDForTenant(ctx context.Context, arg GetTenantDataExportByIDForTenantParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, getTenantDataExportByIDForTenant, arg.ID, arg.TenantID)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantDataExportForTenant = `-- name: GetTenantDataExportForTenant :one
SELECT id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
FROM tenant_data_exports
WHERE public_id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetTenantDataExportForTenantParams struct {
	PublicID uuid.UUID `json:"public_id"`
	TenantID int64     `json:"tenant_id"`
}

func (q *Queries) GetTenantDataExportForTenant(ctx context.Context, arg GetTenantDataExportForTenantParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, getTenantDataExportForTenant, arg.PublicID, arg.TenantID)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenantDataExports = `-- name: ListTenantDataExports :many
SELECT id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
FROM tenant_data_exports
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListTenantDataExportsParams struct {
	TenantID int64 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListTenantDataExports(ctx context.Context, arg ListTenantDataExportsParams) ([]TenantDataExport, error) {
	rows, err := q.db.Query(ctx, listTenantDataExports, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantDataExport
	for rows.Next() {
		var i TenantDataExport
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TenantID,
			&i.RequestedByUserID,
			&i.OutboxEventID,
			&i.FileObjectID,
			&i.Format,
			&i.Status,
			&i.ErrorSummary,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTenantDataExportFailed = `-- name: MarkTenantDataExportFailed :one
UPDATE tenant_data_exports
SET
    status = 'failed',
    error_summary = left($2, 1000),
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
`

type MarkTenantDataExportFailedParams struct {
	ID   int64  `json:"id"`
	Left string `json:"left"`
}

func (q *Queries) MarkTenantDataExportFailed(ctx context.Context, arg MarkTenantDataExportFailedParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, markTenantDataExportFailed, arg.ID, arg.Left)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markTenantDataExportProcessing = `-- name: MarkTenantDataExportProcessing :one
UPDATE tenant_data_exports
SET
    status = 'processing',
    outbox_event_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
`

type MarkTenantDataExportProcessingParams struct {
	ID            int64       `json:"id"`
	OutboxEventID pgtype.Int8 `json:"outbox_event_id"`
}

func (q *Queries) MarkTenantDataExportProcessing(ctx context.Context, arg MarkTenantDataExportProcessingParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, markTenantDataExportProcessing, arg.ID, arg.OutboxEventID)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markTenantDataExportReady = `-- name: MarkTenantDataExportReady :one
UPDATE tenant_data_exports
SET
    status = 'ready',
    file_object_id = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
`

type MarkTenantDataExportReadyParams struct {
	ID           int64       `json:"id"`
	FileObjectID pgtype.Int8 `json:"file_object_id"`
}

func (q *Queries) MarkTenantDataExportReady(ctx context.Context, arg MarkTenantDataExportReadyParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, markTenantDataExportReady, arg.ID, arg.FileObjectID)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteExpiredTenantDataExports = `-- name: SoftDeleteExpiredTenantDataExports :execrows
UPDATE tenant_data_exports
SET
    status = 'deleted',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE expires_at <= now()
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteExpiredTenantDataExports(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExpiredTenantDataExports)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTenantDataExportFormat = `-- name: UpdateTenantDataExportFormat :one
UPDATE tenant_data_exports
SET
    format = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, public_id, tenant_id, requested_by_user_id, outbox_event_id, file_object_id, format, status, error_summary, expires_at, created_at, updated_at, completed_at, deleted_at
`

type UpdateTenantDataExportFormatParams struct {
	ID     int64  `json:"id"`
	Format string `json:"format"`
}

func (q *Queries) UpdateTenantDataExportFormat(ctx context.Context, arg UpdateTenantDataExportFormatParams) (TenantDataExport, error) {
	row := q.db.QueryRow(ctx, updateTenantDataExportFormat, arg.ID, arg.Format)
	var i TenantDataExport
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TenantID,
		&i.RequestedByUserID,
		&i.OutboxEventID,
		&i.FileObjectID,
		&i.Format,
		&i.Status,
		&i.ErrorSummary,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}
