// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tenant_admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantAdminTenant = `-- name: CreateTenantAdminTenant :one
INSERT INTO tenants (
    slug,
    display_name,
    active
) VALUES (
    $1,
    $2,
    true
)
RETURNING
    id,
    slug,
    display_name,
    active,
    created_at,
    updated_at
`

type CreateTenantAdminTenantParams struct {
	Slug        string `json:"slug"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateTenantAdminTenant(ctx context.Context, arg CreateTenantAdminTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenantAdminTenant, arg.Slug, arg.DisplayName)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTenantAdminLocalMembershipRole = `-- name: DeactivateTenantAdminLocalMembershipRole :execrows
UPDATE tenant_memberships
SET
    active = false,
    updated_at = now()
WHERE user_id = $1
  AND tenant_id = $2
  AND role_id = $3
  AND source = 'local_override'
  AND active = true
`

type DeactivateTenantAdminLocalMembershipRoleParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
	RoleID   int64 `json:"role_id"`
}

func (q *Queries) DeactivateTenantAdminLocalMembershipRole(ctx context.Context, arg DeactivateTenantAdminLocalMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateTenantAdminLocalMembershipRole, arg.UserID, arg.TenantID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateTenantAdminTenant = `-- name: DeactivateTenantAdminTenant :one
UPDATE tenants
SET
    active = false,
    updated_at = now()
WHERE slug = $1
RETURNING
    id,
    slug,
    display_name,
    active,
    created_at,
    updated_at
`

func (q *Queries) DeactivateTenantAdminTenant(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, deactivateTenantAdminTenant, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantAdminTenant = `-- name: GetTenantAdminTenant :one
SELECT
    t.id,
    t.slug,
    t.display_name,
    t.active,
    t.created_at,
    t.updated_at,
    COALESCE(COUNT(DISTINCT tm.user_id) FILTER (WHERE tm.active), 0)::bigint AS active_member_count
FROM tenants t
LEFT JOIN tenant_memberships tm ON tm.tenant_id = t.id
WHERE t.slug = $1
GROUP BY t.id
LIMIT 1
`

type GetTenantAdminTenantRow struct {
	ID                int64              `json:"id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ActiveMemberCount int64              `json:"active_member_count"`
}

func (q *Queries) GetTenantAdminTenant(ctx context.Context, slug string) (GetTenantAdminTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenantAdminTenant, slug)
	var i GetTenantAdminTenantRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveMemberCount,
	)
	return i, err
}

const listTenantAdminMembershipRows = `-- name: ListTenantAdminMembershipRows :many
SELECT
    u.id AS user_id,
    u.public_id AS user_public_id,
    u.email,
    u.display_name AS user_display_name,
    u.deactivated_at AS user_deactivated_at,
    t.id AS tenant_id,
    t.slug AS tenant_slug,
    t.display_name AS tenant_display_name,
    r.code AS role_code,
    tm.source,
    tm.active,
    tm.created_at,
    tm.updated_at
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
JOIN tenants t ON t.id = tm.tenant_id
JOIN roles r ON r.id = tm.role_id
WHERE t.slug = $1
ORDER BY u.email, r.code, tm.source
`

type ListTenantAdminMembershipRowsRow struct {
	UserID            int64              `json:"user_id"`
	UserPublicID      uuid.UUID          `json:"user_public_id"`
	Email             string             `json:"email"`
	UserDisplayName   string             `json:"user_display_name"`
	UserDeactivatedAt pgtype.Timestamptz `json:"user_deactivated_at"`
	TenantID          int64              `json:"tenant_id"`
	TenantSlug        string             `json:"tenant_slug"`
	TenantDisplayName string             `json:"tenant_display_name"`
	RoleCode          string             `json:"role_code"`
	Source            string             `json:"source"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTenantAdminMembershipRows(ctx context.Context, slug string) ([]ListTenantAdminMembershipRowsRow, error) {
	rows, err := q.db.Query(ctx, listTenantAdminMembershipRows, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantAdminMembershipRowsRow
	for rows.Next() {
		var i ListTenantAdminMembershipRowsRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserPublicID,
			&i.Email,
			&i.UserDisplayName,
			&i.UserDeactivatedAt,
			&i.TenantID,
			&i.TenantSlug,
			&i.TenantDisplayName,
			&i.RoleCode,
			&i.Source,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAdminTenants = `-- name: ListTenantAdminTenants :many
SELECT
    t.id,
    t.slug,
    t.display_name,
    t.active,
    t.created_at,
    t.updated_at,
    COALESCE(COUNT(DISTINCT tm.user_id) FILTER (WHERE tm.active), 0)::bigint AS active_member_count
FROM tenants t
LEFT JOIN tenant_memberships tm ON tm.tenant_id = t.id
GROUP BY t.id
ORDER BY t.slug
`

type ListTenantAdminTenantsRow struct {
	ID                int64              `json:"id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Active            bool               `json:"active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ActiveMemberCount int64              `json:"active_member_count"`
}

func (q *Queries) ListTenantAdminTenants(ctx context.Context) ([]ListTenantAdminTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenantAdminTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantAdminTenantsRow
	for rows.Next() {
		var i ListTenantAdminTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveMemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantAdminTenant = `-- name: UpdateTenantAdminTenant :one
UPDATE tenants
SET
    display_name = $2,
    active = $3,
    updated_at = now()
WHERE slug = $1
RETURNING
    id,
    slug,
    display_name,
    active,
    created_at,
    updated_at
`

type UpdateTenantAdminTenantParams struct {
	Slug        string `json:"slug"`
	DisplayName string `json:"display_name"`
	Active      bool   `json:"active"`
}

func (q *Queries) UpdateTenantAdminTenant(ctx context.Context, arg UpdateTenantAdminTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantAdminTenant, arg.Slug, arg.DisplayName, arg.Active)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantAdminLocalMembership = `-- name: UpsertTenantAdminLocalMembership :one
INSERT INTO tenant_memberships (
    user_id,
    tenant_id,
    role_id,
    source,
    active
) VALUES (
    $1,
    $2,
    $3,
    'local_override',
    true
)
ON CONFLICT (user_id, tenant_id, role_id, source) DO UPDATE
SET active = true,
    updated_at = now()
RETURNING
    user_id,
    tenant_id,
    role_id,
    source,
    active,
    created_at,
    updated_at
`

type UpsertTenantAdminLocalMembershipParams struct {
	UserID   int64 `json:"user_id"`
	TenantID int64 `json:"tenant_id"`
	RoleID   int64 `json:"role_id"`
}

func (q *Queries) UpsertTenantAdminLocalMembership(ctx context.Context, arg UpsertTenantAdminLocalMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, upsertTenantAdminLocalMembership, arg.UserID, arg.TenantID, arg.RoleID)
	var i TenantMembership
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.RoleID,
		&i.Source,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
